Repository mattermost-community/focalboard, pull requests merged in 2021-06, with the labels that each got.

#439 Introduce checkbox property type
  Makefile
  webapp/src/components/propertyValueElement.tsx
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/propertyMenu.tsx
  webapp/src/widgets/switch.scss
  webapp/src/widgets/switch.tsx
  webapp/webpack.dev.js
Labels: 2: Dev Review

#454 Add units tests for app/sharing.go
  server/app/sharing_test.go
Labels: 2: Dev Review

#415 Implement Multi Select Values
  webapp/src/blocks/card.ts
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/properties/multiSelect.tsx
  webapp/src/components/propertyValueElement.tsx
  webapp/src/components/table/table.scss
  webapp/src/components/table/table.tsx
  webapp/src/csvExporter.ts
  webapp/src/mutator.ts
  webapp/src/octoUtils.tsx
  webapp/src/viewModel/boardTree.ts
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/buttons/iconButton.scss
  webapp/src/widgets/buttons/iconButton.tsx
  webapp/src/widgets/label.scss
  webapp/src/widgets/label.tsx
  webapp/src/widgets/propertyMenu.tsx
  webapp/src/widgets/valueSelector.scss
  webapp/src/widgets/valueSelector.tsx
Labels: 3: Reviews Complete

#336 188 - Updating color for alerts
  webapp/src/components/dialog.scss
Labels: 2: Dev Review

#520 Bump Logr version to fix Windows build
  linux/go.sum
  linux/main.go
  mattermost-plugin/build/go.sum
  mattermost-plugin/go.sum
  mattermost-plugin/server/plugin.go
  server/go.mod
  server/go.sum
Labels: 2: Dev Review

#508 GH-418: Fix Resetting Search after adding new Property
  webapp/src/components/viewHeader/viewHeaderSearch.tsx
  webapp/src/viewModel/boardTree.ts
Labels: 2: Dev Review

#406 Person Property Type
  server/api/api.go
  server/app/user.go
  server/go.mod
  server/go.sum
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/services/store/storetests/users.go
  server/swagger/docs/html/.openapi-generator/VERSION
  server/swagger/docs/html/index.html
  server/swagger/swagger.yml
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/cardDetail/comment.tsx
  webapp/src/components/properties/user/__snapshots__/user.test.tsx.snap
  webapp/src/components/properties/user/user.scss
  webapp/src/components/properties/user/user.test.tsx
  webapp/src/components/properties/user/user.tsx
  webapp/src/components/propertyValueElement.tsx
  webapp/src/octoClient.ts
  webapp/src/pages/boardPage.tsx
  webapp/src/theme.ts
  webapp/src/user.tsx
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/propertyMenu.tsx
  webapp/src/widgets/valueSelector.tsx
Labels: 2: Dev Review

#496 Telemetry and metrics
  logging.json
  server/app/app.go
  server/app/auth.go
  server/app/blocks.go
  server/app/helper_test.go
  server/app/workspaces.go
  server/integrationtests/clienttestlib.go
  server/server/server.go
  server/services/metrics/metrics.go
  server/services/metrics/service.go
  server/services/mlog/levels.go
  server/services/mlog/mlog.go
  server/services/prometheus/intrumentor.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/workspaces.go
  server/services/store/store.go
  server/services/telemetry/telemetry.go
Labels: 3: Reviews Complete

#451 [GH-443] Create new window when reopening without existing windows
  mac/Focalboard/AppDelegate.swift
Labels: 2: Dev Review

#159 Add Docker volume persistence
  docker/Dockerfile
  docker/README.md
  docker/server_config.json
Labels: Lifecycle/1:stale

#557 Fix MySQL migration connection when the DSN doesn't contain any query parameters
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrate_test.go
Labels: 2: Dev Review

#553 Card Template > Creating a property & setting type only stores either property name or type
  webapp/src/components/cardDetail/cardDetailProperties.tsx
  webapp/src/mutator.ts
  webapp/src/widgets/propertyMenu.test.tsx
  webapp/src/widgets/propertyMenu.tsx
Labels: 3: Reviews Complete

#542 Auditing
  config.json
  logging.json
  server/api/admin.go
  server/api/api.go
  server/api/audit.go
  server/api/auth.go
  server/app/app.go
  server/app/helper_test.go
  server/auth/auth_test.go
  server/go.sum
  server/integrationtests/clienttestlib.go
  server/main/main.go
  server/model/block.go
  server/server/server.go
  server/services/audit/audit.go
  server/services/audit/record.go
  server/services/audit/record_test.go
  server/services/config/config.go
  server/services/mlog/mlog.go
  server/services/mlog/options.go
  webapp/package-lock.json
Labels: 2: Dev Review

#565 Ensures cgo is disabled for plugin compilation to avoid libc linking
  mattermost-plugin/Makefile
Labels: 2: Dev Review

#539 Multi Select Filter + Sort
  webapp/src/cardFilter.ts
  webapp/src/components/viewHeader/filterComponent.tsx
  webapp/src/components/viewHeader/filterEntry.tsx
  webapp/src/viewModel/boardTree.ts
Labels: 3: Reviews Complete

#589 Remove enterprise symlink
  .gitignore
  Makefile
  server/einterfaces/einterfaces.go
  server/go.mod
  server/go.sum
  server/server/enterprise.go
Labels: 3: Reviews Complete

#591 rename logger & audit config
  config.json
  server/integrationtests/clienttestlib.go
  server/main/main.go
  server/server/server.go
  server/services/config/config.go
Labels: 3: Reviews Complete

#554 Table unit tests
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/centerPanel.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableGroupHeaderRow.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableHeader.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableHeaderMenu.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRows.test.tsx.snap
  webapp/src/components/table/table.test.tsx
  webapp/src/components/table/table.tsx
  webapp/src/components/table/tableGroup.tsx
  webapp/src/components/table/tableGroupHeaderRow.test.tsx
  webapp/src/components/table/tableGroupHeaderRow.tsx
  webapp/src/components/table/tableHeader.test.tsx
  webapp/src/components/table/tableHeaderMenu.test.tsx
  webapp/src/components/table/tableRow.test.tsx
  webapp/src/components/table/tableRows.test.tsx
  webapp/src/components/table/tableRows.tsx
Labels: 2: Dev Review

#547 Solved #387 Bug: Comment box doesn't clear after sending
  webapp/src/components/markdownEditor.tsx
Labels: Lifecycle/1:stale

#582 Adds a link to the setup docs on the plugin's config header section
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
Labels: 2: Dev Review

#603 First pass linter cleanup
  server/.golangci.yml
  server/api/api.go
  server/api/audit.go
  server/api/auth.go
  server/app/auth.go
  server/app/auth_test.go
  server/app/blocks.go
  server/app/files.go
  server/app/helper_test.go
  server/app/sharing.go
  server/app/sharing_test.go
  server/app/workspaces.go
  server/auth/auth.go
  server/auth/auth_test.go
  server/client/client.go
  server/context/context.go
  server/integrationtests/clienttestlib.go
  server/main/main.go
  server/model/block.go
  server/model/sharing.go
  server/server/initHandlers.go
  server/server/server.go
  server/services/audit/audit.go
  server/services/auth/email.go
  server/services/auth/password.go
  server/services/auth/request_parser.go
  server/services/auth/request_parser_test.go
  server/services/metrics/metrics.go
  server/services/metrics/service.go
  server/services/mlog/levels.go
  server/services/mlog/mlog.go
  server/services/mlog/tlog.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/initialize.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/session.go
  server/services/store/sqlstore/sharing.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/sqlstore/user.go
  server/services/store/sqlstore/workspaces.go
  server/services/store/store.go
  server/services/store/storetests/system.go
  server/services/store/storetests/users.go
  server/services/telemetry/telemetry.go
  server/services/webhook/webhook.go
  server/web/webserver.go
  server/ws/websockets.go
Labels: 3: Reviews Complete

#609 Fixes web files not found when plugin directory is custom
  mattermost-plugin/server/plugin.go
Labels: 2: Dev Review

#610 Use path.Join in plugin's webpath property
  mattermost-plugin/server/plugin.go
Labels: 2: Dev Review

#573 Update _index.md
  website/site/content/guide/user/_index.md
Labels: 1: PM Review

#517 Expose 9092 port on docker container
  docker/Dockerfile
  docker/docker-compose-db-nginx.yml
  docker/docker-compose.yml
Labels: 2: Dev Review

#619 Add RPC API support to plugin
  linux/main.go
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  mattermost-plugin/server/plugin.go
  server/integrationtests/clienttestlib.go
  server/main/main.go
  server/server/server.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/sqlstore_test.go
Labels: 3: Reviews Complete
