Repository mattermost-community/focalboard, pull requests merged in 2021-04, with the labels that each got.

#245 Translations update from Weblate
  webapp/i18n/fr.json
  webapp/i18n/ja.json
  webapp/i18n/nl.json
  webapp/i18n/ru.json
  webapp/i18n/tr.json
  webapp/i18n/zh_Hans.json
Labels: 2: Dev Review

#275 264 - Updating comment area css
  webapp/src/components/cardDetail/comment.scss
  webapp/src/components/cardDetail/commentsList.scss
  webapp/src/components/markdownEditor.scss
  webapp/src/widgets/buttons/button.scss
Labels: 2: Dev Review

#317 Add macOS quarantine
  mac/Focalboard/Info.plist
Labels: 2: Dev Review, 2: QA Review

#168 recreate dockerfile
  docker/Dockerfile
Labels: Lifecycle/1:stale
