Repository mattermost-community/focalboard, pull requests merged in 2021-10, with the labels that each got.

#1384 Remove default `return`
  webapp/src/components/gallery/gallery.tsx
Labels: Contributor, hacktoberest-accepted

#1234 Fix kanban cards overlapping with header
  webapp/src/components/kanban/kanban.scss
Labels: 1: UX Review, Lifecycle/1:stale

#1390 Run all CI on PRs to be merged with release branches
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-plugin.yml
  .github/workflows/lint-server.yml
Labels: 3: Reviews Complete

#1382 gh-1371 - Add readtoken when in readonly mode
  webapp/src/app.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/components/workspace.tsx
  webapp/src/octoClient.ts
  webapp/src/utils.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1326 GH-Mobile banner css
  webapp/src/pages/boardPage.scss
  webapp/src/pages/boardPage.tsx
  webapp/src/userSettings.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1407 Progress for webpack watch mode
  webapp/package.json
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1413 [GH-864]: add tests unit for viewHeader
  webapp/src/components/viewHeader/__snapshots__/viewHeader.test.tsx.snap
  webapp/src/components/viewHeader/viewHeader.test.tsx
  webapp/src/testUtils.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1400 [GH-1331] Fix for URL property on kanban card
  webapp/src/components/kanban/kanbanCard.scss
  webapp/src/components/properties/link/link.tsx
  webapp/src/widgets/label.scss
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1327 MM-38807 Fix tiny icons caused by css pollution
  mattermost-plugin/webapp/loaders/globalScssClassLoader.js
  mattermost-plugin/webapp/src/plugin.scss
  webapp/src/widgets/icons/logo.tsx
Labels: 3: Reviews Complete

#1416 Typing adjustment - 1354
  webapp/src/octoClient.ts
  webapp/src/pages/registerPage.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1422 [GH-1352] Webapp Linter Fixes - fix linter warnings for file markdownEditor.tsx
  webapp/src/components/markdownEditor.tsx
Labels: 2: Dev Review, Contributor, Hacktoberfest, hacktoberfest-accepted

#1434 Fix failing unit test for viewHeader
  webapp/src/components/viewHeader/viewHeader.test.tsx
Labels: 3: Reviews Complete, Contributor, Hacktoberfest, hacktoberfest-accepted

#1391 Disable websockets in shared boards
  webapp/src/app.tsx
Labels: 2: Dev Review

#1428 [GH-861] add units test for filterValue
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/filterValue.test.tsx
  webapp/src/testUtils.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1403 [GH-866] add unit test for viewHeaderGroupByMenu
  webapp/src/components/viewHeader/__snapshots__/viewHeaderGroupByMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeaderGroupByMenu.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1374 gh-1360 Fix for tests using 'any' when wrapping components
  webapp/src/components/addContentMenuItem.test.tsx
  webapp/src/components/blockIconSelector.test.tsx
  webapp/src/components/cardDetail/cardDetailContents.test.tsx
  webapp/src/components/cardDetail/cardDetailProperties.test.tsx
  webapp/src/components/content/checkboxElement.test.tsx
  webapp/src/components/globalHeader/globalHeader.test.tsx
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.test.tsx
  webapp/src/components/properties/dateRange/dateRange.test.tsx
  webapp/src/components/properties/lastModifiedAt/lastModifiedAt.test.tsx
  webapp/src/components/properties/user/user.test.tsx
  webapp/src/components/propertyValueElement.test.tsx
  webapp/src/components/sidebar/sidebar.test.tsx
  webapp/src/components/sidebar/sidebarSettingsMenu.test.tsx
  webapp/src/components/table/calculation/calculationRow.test.tsx
  webapp/src/components/table/table.test.tsx
  webapp/src/components/table/tableGroupHeaderRow.test.tsx
  webapp/src/components/table/tableHeader.test.tsx
  webapp/src/components/table/tableHeaderMenu.test.tsx
  webapp/src/components/table/tableRow.test.tsx
  webapp/src/components/table/tableRows.test.tsx
  webapp/src/components/viewHeader/viewHeaderActionsMenu.test.tsx
  webapp/src/components/workspaceSwitcher/workspaceOptions.test.tsx
  webapp/src/components/workspaceSwitcher/workspaceSwitcher.test.tsx
  webapp/src/pages/dashboard/centerContent.test.tsx
  webapp/src/pages/dashboard/dashboardPage.test.tsx
  webapp/src/testUtils.tsx
  webapp/src/widgets/propertyMenu.test.tsx
Labels: 2: Dev Review

#1412 [GH-865] Add more tests unit to viewHeaderActionMenu
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeaderActionsMenu.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1417 [GH-993] Fix csv export header
  webapp/src/csvExporter.ts
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1411 Typing adjustment - 1357
  webapp/src/blocks/archive.ts
  webapp/src/telemetry/telemetryClient.ts
  webapp/src/testUtils.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1398 Fix #1397. Add show empty toggle to Dashboard
  webapp/i18n/en.json
  webapp/src/pages/dashboard/__snapshots__/centerContent.test.tsx.snap
  webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
  webapp/src/pages/dashboard/centerContent.tsx
  webapp/src/pages/dashboard/dashboardPage.scss
  webapp/src/userSettings.ts
Labels: CherryPick/Approved

#1430 Add the ability to import checklists from Trello
  import/trello/importTrello.ts
Labels: 2: Dev Review, 2: QA Review, Contributor, Hacktoberfest, hacktoberfest-accepted

#1414 [GH-863] add tests unit for newCardButtonTemplateItem
  webapp/src/components/viewHeader/__snapshots__/newCardButtonTemplateItem.test.tsx.snap
  webapp/src/components/viewHeader/newCardButtonTemplateItem.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1424 [GH-862] Add tests unit for newCardButton
  webapp/src/components/viewHeader/__snapshots__/newCardButton.test.tsx.snap
  webapp/src/components/viewHeader/newCardButton.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1446 [GH-860] Add tests unit for filterEntry
  webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
  webapp/src/components/viewHeader/filterEntry.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1369 Channels style UUID
  server/api/api.go
  server/app/auth.go
  server/app/auth_test.go
  server/app/files.go
  server/app/sharing_test.go
  server/app/workspaces.go
  server/auth/auth_test.go
  server/go.mod
  server/integrationtests/blocks_test.go
  server/integrationtests/sharing_test.go
  server/integrationtests/user_test.go
  server/server/server.go
  server/services/store/sqlstore/workspaces.go
  server/services/store/storetests/users.go
  server/services/store/storetests/workspaces.go
  server/utils/utils.go
  webapp/src/blocks/block.ts
  webapp/src/blocks/board.ts
  webapp/src/components/kanban/kanban.tsx
  webapp/src/components/markdownEditor.tsx
  webapp/src/components/propertyValueElement.tsx
  webapp/src/components/shareBoardComponent.tsx
  webapp/src/components/table/table.test.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/mutator.ts
  webapp/src/octoUtils.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 2: Dev Review

#1445 [GH-859] Add tests unit for filterComponent
  webapp/src/components/viewHeader/__snapshots__/filterComponent.test.tsx.snap
  webapp/src/components/viewHeader/filterComponent.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1454 update snapshots, remove tests for release-0.9.0
  webapp/src/components/__snapshots__/propertyValueElement.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeaderActionsMenu.test.tsx
  webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
Labels: 2: Dev Review

#1415 Typing adjustment - 1353
  webapp/src/hooks/sortable.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1444 make sure setValue receives empty string
  webapp/src/components/__snapshots__/propertyValueElement.test.tsx.snap
  webapp/src/components/propertyValueElement.test.tsx
  webapp/src/components/propertyValueElement.tsx
Labels: 2: Dev Review, CherryPick/Approved

#1457 GH-1448 - Only call history replace if a plugin
  webapp/src/app.tsx
Labels: 2: Dev Review, CherryPick/Approved

#1466 Move app history replace to happen only if not in plugin legacy mode
  webapp/src/app.tsx
Labels: 2: Dev Review, CherryPick/Approved

#1458 Add tests unit on emptycardButton
  webapp/src/components/viewHeader/__snapshots__/emptyCardButton.test.tsx.snap
  webapp/src/components/viewHeader/emptyCardButton.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1450 GH-1439: do not show outside dates in datepicker
  webapp/src/components/properties/dateRange/dateRange.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted
