Repository mattermost-community/focalboard, pull requests merged in 2021-12, with the labels that each got.

#1895 Adding explict logout logic
  server/api/api.go
  server/api/auth.go
  server/app/auth.go
  server/services/metrics/metrics.go
  webapp/src/components/sidebar/sidebarUserMenu.tsx
  webapp/src/octoClient.ts
  webapp/src/pages/errorPage.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1898 GH-1987 fix initial date property
  webapp/src/components/calendar/fullCalendar.tsx
Labels: 2: Dev Review, CherryPick/Approved

#1849 [GH-1823] Added E2E test for MM-T4284
  webapp/cypress.json
  webapp/cypress/integration/manageGroups.ts
Labels: 3: Reviews Complete, Contributor

#1901 Automated cherry pick of #1898
  webapp/src/components/calendar/fullCalendar.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1899 Automated cherry pick of #1895
  server/api/api.go
  server/api/auth.go
  server/app/auth.go
  server/services/metrics/metrics.go
  webapp/src/components/sidebar/sidebarUserMenu.tsx
  webapp/src/octoClient.ts
  webapp/src/pages/errorPage.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1890 Don't insert nulls into blocks_history table.
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/migrations/migrations_files/000015_blocks_history_no_nulls.down.sql
  server/services/store/sqlstore/migrations/migrations_files/000015_blocks_history_no_nulls.up.sql
  server/services/store/store.go
Labels: 3: Reviews Complete

#1912 Don't notify @mentioned users who are not members of channel
  mattermost-plugin/server/notifications.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/user_test.go
Labels: 3: Reviews Complete

#1758 Add a note to enable reliable websockets on plugin install
  website/site/content/download/mattermost/latest-plugin/_index.md
Labels: 3: Reviews Complete

#1937 Prevents the application from crashing if there is a null content order
  webapp/src/blocks/card.ts
Labels: 2: QA Review, CherryPick/Approved

#1896 Making markdown editor text selectable
  webapp/src/components/markdownEditor.scss
Labels: 2: QA Review, CherryPick/Approved

#1938 Automated cherry pick of #1937
  webapp/src/blocks/card.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1939 Automated cherry pick of #1896
  webapp/src/components/markdownEditor.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1923 Fix an Issue
  server/api/auth.go
  webapp/src/pages/registerPage.tsx
Labels: 3: Reviews Complete

#1906 GH-1878: Display Bot Badge in Auto Complete
  server/model/user.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  webapp/src/components/markdownEditorInput/entryComponent/entryComponent.scss
  webapp/src/components/markdownEditorInput/entryComponent/entryComponent.tsx
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/components/workspace.test.tsx
  webapp/src/user.tsx
Labels: 3: Reviews Complete

#1947 Automated cherry pick of #1925
  webapp/src/components/cardDetail/commentsList.scss
  webapp/src/components/markdownEditorInput/markdownEditorInput.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1944 Removed unused fields
  server/integrationtests/user_test.go
  server/model/user.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 3: Reviews Complete, CherryPick/Approved

#1951 Fixed a bug preventing new template being created from a card
  webapp/src/mutator.test.ts
  webapp/src/mutator.ts
Labels: CherryPick/Candidate

#1952 [GH-1946] Fix losing focus for the card title in the dialog
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, Contributor

#1956 [GH-1815]: Add e2e tests for empty board
  webapp/cypress/integration/createBoard.ts
Labels: Contributor

#1856 [GH-1730]: Clear search on view change
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/viewHeader/viewHeader.test.tsx
  webapp/src/components/viewHeader/viewHeaderSearch.test.tsx
  webapp/src/components/viewHeader/viewHeaderSearch.tsx
Labels: 3: Reviews Complete, Contributor

#1926 Fix MM-40428
  server/app/blocks.go
  server/model/blocktype.go
Labels: 3: Reviews Complete

#1964 fix mysql migration
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/migrations/migrations_files/000015_blocks_history_no_nulls.up.sql
Labels: 2: Dev Review

#1935 Gh 1841 batch patches
  server/api/api.go
  server/app/blocks.go
  server/app/blocks_test.go
  server/model/block.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
Labels: 2: Dev Review, CherryPick/Approved

#1968 Automated cherry pick of #1935
  server/api/api.go
  server/app/blocks.go
  server/app/blocks_test.go
  server/model/block.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1965 Include migration for content order on unique id migration
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/data_migrations_test.go
Labels: 3: Reviews Complete

#1969 Automated cherry pick of #1965
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/data_migrations_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1978 GH-1872 - Updating octo-icon font weight
  webapp/cypress/integration/createBoard.ts
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/styles/main.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#1979 Automated cherry pick of #1978
  webapp/cypress/integration/createBoard.ts
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/styles/main.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1959 GH-1907 - Updating person popover
  webapp/src/components/properties/user/__snapshots__/user.test.tsx.snap
  webapp/src/components/properties/user/user.scss
  webapp/src/components/properties/user/user.tsx
Labels: 2: Dev Review

#1983 Automated cherry pick of #1981
  webapp/src/components/properties/dateRange/dateRange.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1548 [GH-1542] Limit card title to 5 lines
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanban.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/kanban/kanbanCard.scss
  webapp/src/components/kanban/kanbanCard.tsx
Labels: 3: Reviews Complete, Lifecycle/1:stale, Contributor, Hacktoberfest, hacktoberfest-accepted

#1967 Splitting table component in smaller manageable chunks
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableHeaders.test.tsx.snap
  webapp/src/components/table/table.tsx
  webapp/src/components/table/tableHeaders.test.tsx
  webapp/src/components/table/tableHeaders.tsx
Labels: 2: QA Review

#1966 [GH-1826] Cypress test for group by different property
  webapp/cypress.json
  webapp/cypress/global.d.ts
  webapp/cypress/integration/createBoard.ts
  webapp/cypress/integration/groupByProperty.ts
  webapp/cypress/integration/manageGroups.ts
  webapp/cypress/support/commands.ts
  webapp/cypress/tsconfig.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
  webapp/src/components/__snapshots__/dialog.test.tsx.snap
  webapp/src/components/dialog.tsx
  webapp/src/components/viewHeader/__snapshots__/viewHeaderGroupByMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewHeader/viewHeaderGroupByMenu.test.tsx
  webapp/src/components/viewHeader/viewHeaderGroupByMenu.tsx
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/propertyMenu.tsx
Labels: 2: Dev Review, Contributor

#1986 Add workspace to teams and boards migrations
  server/model/board.go
  server/model/team.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/migrations/migrations_files/000015_add_teams_and_boards.down.sql
  server/services/store/sqlstore/migrations/migrations_files/000015_add_teams_and_boards.up.sql
Labels: 3: Reviews Complete

#1997 fix syntax errors for mysql
  server/services/store/sqlstore/blocks.go
Labels: 2: Dev Review

#1998 Remove noisy error for unit tests
  server/web/webserver.go
Labels: 2: Dev Review

#1885 [GH-1883] Fix error page button to follow base URL
  webapp/src/pages/errorPage.tsx
Labels: 3: Reviews Complete, Contributor

#2000 Test all supported databases in CI
  .github/workflows/ci.yml
  Makefile
  docker-testing/docker-compose-mysql.yml
  docker-testing/docker-compose-postgres.yml
  server/integrationtests/clienttestlib.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/helpers_test.go
  server/services/store/sqlstore/util.go
Labels: 2: Dev Review

#2006 Fix linter error
  webapp/src/pages/errorPage.tsx
Labels: 3: Reviews Complete

#2009 fix panic selecting insert_at
  server/services/store/sqlstore/blocks.go
Labels: 2: Dev Review

#2011 Permissions phase 1 - Store changes
  Makefile
  modd-servertest.conf
  modd.conf
  server/model/block.go
  server/model/blocktype.go
  server/model/board.go
  server/model/boards_and_blocks.go
  server/model/boards_and_blocks_test.go
  server/model/permission.go
  server/model/team.go
  server/model/workspace.go
  server/services/store/generators/transactional_store.go.tmpl
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/boards_and_blocks.go
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/data_migrations_test.go
  server/services/store/sqlstore/initializations/bindata.go
  server/services/store/sqlstore/initialize.go
  server/services/store/sqlstore/legacy_blocks.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sharing.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/sqlstore/team.go
  server/services/store/sqlstore/user.go
  server/services/store/sqlstore/workspaces.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/boards.go
  server/services/store/storetests/boards_and_blocks.go
  server/services/store/storetests/helpers.go
  server/services/store/storetests/session.go
  server/services/store/storetests/sharing.go
  server/services/store/storetests/system.go
  server/services/store/storetests/teams.go
  server/services/store/storetests/users.go
  server/services/store/storetests/workspaces.go
  server/utils/utils.go
Labels: 3: Reviews Complete
