Repository mattermost-community/focalboard, pull requests merged in 2021-07, with the labels that each got.

#658 Prevented concurrent writes to websocket
  server/ws/websockets.go
Labels: 3: Reviews Complete

#515 Adding MySQL to the documentation
  website/site/content/download/personal-edition/ubuntu.md
  website/site/content/guide/admin/_index.md
Labels: 3: Reviews Complete

#679 Ensure all code paths close *sql.Rows
  mattermost-plugin/server/plugin.go
  server/server/server.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/system.go
  server/services/store/sqlstore/user.go
  server/services/store/sqlstore/util.go
  server/services/store/sqlstore/workspaces.go
Labels: 2: Dev Review

#677 Prevent plugin from crashing if SiteURL is not set
  mattermost-plugin/server/plugin.go
Labels: 2: Dev Review

#643 GH-629 - Property Popover in Kanban view
  webapp/src/components/gallery/galleryCard.scss
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/widgets/tooltip.scss
  webapp/src/widgets/tooltip.tsx
Labels: 3: Reviews Complete

#686 fix remaining golangci linter warnings
  mattermost-plugin/server/plugin.go
  server/.golangci.yml
  server/api/api.go
  server/api/audit.go
  server/api/auth.go
  server/api/context.go
  server/app/blocks_test.go
  server/app/files.go
  server/client/client.go
  server/integrationtests/clienttestlib.go
  server/server/server.go
  server/services/auth/password_test.go
  server/services/config/config.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/initialize.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/user.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/sharing.go
  server/services/telemetry/telemetry.go
  server/ws/websockets.go
Labels: 2: Dev Review

#694 Fixed missing errors
  server/services/store/sqlstore/blocks.go
  server/services/store/storetests/helpers.go
Labels: 3: Reviews Complete

#695 Added missed test
  server/services/store/storetests/blocks.go
Labels: 3: Reviews Complete

#696 Fix linter errors in plugin
  mattermost-plugin/.golangci.yml
  mattermost-plugin/server/plugin.go
  server/.golangci.yml
  server/client/client.go
  server/services/store/sqlstore/blocks.go
  server/services/store/storetests/blocks.go
Labels: 3: Reviews Complete

#649 Remove showView and showBoard property drilling and migrate centerPanel to functional component
  CHANGELOG.md
  webapp/src/app.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarAddBoardMenu.tsx
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/components/workspace.tsx
  webapp/src/pages/boardPage.tsx
Labels: 3: Reviews Complete

#720 Lint server & plugin for CI
  .github/workflows/lint-plugin.yml
  .github/workflows/lint-server.yml
  Makefile
  mattermost-plugin/.golangci.yml
  server/.golangci.yml
  server/api/auth.go
  server/model/version.go
Labels: 2: Dev Review

#637 Description Section of Card can now Have Columns
  webapp/src/blocks/card.ts
  webapp/src/blocks/contentBlock.ts
  webapp/src/components/addContentMenuItem.tsx
  webapp/src/components/cardDetail/cardDetailContents.tsx
  webapp/src/components/contentBlock.scss
  webapp/src/components/contentBlock.tsx
  webapp/src/components/dialog.scss
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/markdownEditor.scss
  webapp/src/mutator.ts
  webapp/src/octoUtils.tsx
  webapp/src/styles/main.scss
  webapp/src/viewModel/cardTree.test.ts
  webapp/src/viewModel/cardTree.ts
Labels: 3: Reviews Complete

#717 Add mlog package to stack filter list
  server/services/mlog/mlog.go
Labels: 3: Reviews Complete

#732 Removing the forceRefresh from the router
  webapp/src/app.tsx
  webapp/src/octoListener.ts
  webapp/src/pages/boardPage.tsx
Labels: 2: Dev Review

#731 Add global templates to redux store
  mattermost-plugin/server/manifest.go
  webapp/src/components/sidebar/boardTemplateMenuItem.tsx
  webapp/src/components/sidebar/sidebarAddBoardMenu.tsx
  webapp/src/store/globalTemplates.ts
  webapp/src/store/index.ts
  webapp/src/viewModel/globalTemplateTree.ts
Labels: 3: Reviews Complete

#749 Refactor the websockets connection messages and lifecycle
  server/ws/websockets.go
  server/ws/websockets_test.go
  webapp/src/octoListener.ts
Labels: 2: Dev Review, 2: QA Review

#766 GH-633 - Updating active indicator for boards
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/workspace.tsx
  webapp/src/theme.ts
Labels: 2: Dev Review

#776 [GH-770] Use textarea for title in the card dialog
  webapp/cypress/integration/createBoard.js
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/widgets/editable.tsx
  webapp/src/widgets/editableArea.scss
  webapp/src/widgets/editableArea.tsx
Labels: 1: UX Review

#764 Adds dashboard placeholder route and component
  webapp/i18n/en.json
  webapp/src/app.tsx
  webapp/src/pages/dashboardPage.scss
  webapp/src/pages/dashboardPage.tsx
Labels: 2: Dev Review

#787 Add more unit tests for ./store/sqlstore/user.go
  server/services/store/storetests/users.go
Labels: 2: Dev Review

#788 Fix nil stringer error
  linux/go.sum
  mattermost-plugin/go.sum
  mattermost-plugin/server/plugin.go
  server/api/admin.go
  server/api/api.go
  server/api/auth.go
  server/go.mod
  server/go.sum
  server/main/main.go
Labels: 2: Dev Review

#768 [GH-431] Add unit tests for ./store/sqlstore/workspaces.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/sqlstore/workspaces.go
  server/services/store/storetests/workspaces.go
Labels: 3: Reviews Complete

#792 Opened markdown links in new tab
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 2: Dev Review

#806 [GH-805] - Add Makefile documentation
  Makefile
Labels: 3: Reviews Complete

#710 [GH-443] Add unit tests for ./services/webhook/webhook.go
  server/services/webhook/webhook_test.go
Labels: 3: Reviews Complete, Lifecycle/1:stale
