Repository mattermost-community/focalboard, pull requests merged in 2021-11, with the labels that each got.

#1704 [GH-855]: Add unit test for kanbanColumn
  webapp/src/components/kanban/__snapshots__/kanbanColumn.test.tsx.snap
  webapp/src/components/kanban/kanbanColumn.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1699 [GH-857]: Add unit tests for kanbanHiddenColumnItem
  webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
  webapp/src/components/kanban/kanbanHiddenColumnItem.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1706 webapp: make 'no options' message more explicit + translatable
  webapp/i18n/en.json
  webapp/i18n/fr.json
  webapp/src/widgets/valueSelector.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1705 [GH-91] Added Install/Build Instructions for Docker in Readme
  README.md
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1695 [GH-828]: Add unit tests for centerPanel
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/centerPanel.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1698 [GH-854]: Add unit tests for kanbanCard
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/kanban/kanbanCard.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1654 [GH-1647] Added localization for gallery option in view menu
  webapp/i18n/en.json
  webapp/src/components/viewMenu.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1675 Gh 1451 mobile sidebar
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/sidebar.test.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarBoardItem.test.tsx
  webapp/src/components/sidebar/sidebarBoardItem.tsx
Labels: 2: Dev Review, CherryPick/Approved

#1624 [GH 1348] add eslint comment to ignore todo for empty if block
  webapp/src/components/table/tableHeaderMenu.tsx
Labels: Lifecycle/1:stale, Contributor, Hacktoberfest, hacktoberfest-accepted

#1669 [GH-1436] start and end dates styling modified
  webapp/src/components/properties/dateRange/dateRange.scss
Labels: 2: Dev Review, Contributor, Hacktoberfest, hacktoberfest-accepted

#1683 GH-1646 - Fix bad positioning of registration error message
  webapp/src/pages/registerPage.scss
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1499 Fixed menu label hover
  webapp/src/components/sidebar/sidebarAddBoardMenu.scss
  webapp/src/components/sidebar/sidebarSettingsMenu.scss
  webapp/src/components/sidebar/sidebarUserMenu.scss
  webapp/src/widgets/menu/labelOption.scss
  webapp/src/widgets/menuWrapper.scss
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1339 [GH-1278] Confirm delete when deleting board
  webapp/cypress/integration/createBoard.js
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/dialog.scss
  webapp/src/components/dialog.tsx
  webapp/src/components/sidebar/__snapshots__/deleteBoardDialog.test.tsx.snap
  webapp/src/components/sidebar/deleteBoardDialog.scss
  webapp/src/components/sidebar/deleteBoardDialog.test.tsx
  webapp/src/components/sidebar/deleteBoardDialog.tsx
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/viewHeader/viewHeader.scss
  webapp/src/widgets/buttons/button.scss
  webapp/src/widgets/buttons/button.tsx
Labels: 1: UX Review, Contributor

#1743 Changed server not bind to any port to debug, as it's a plugin only expected path
  server/web/webserver.go
Labels: 3: Reviews Complete

#1738 Check nulls on board and active view when tracking telemetry events
  webapp/src/pages/boardPage.tsx
Labels: 2: Dev Review, CherryPick/Approved

#1734 [GH-1432]: Use Button component on welcomePage.tsx
  webapp/src/pages/welcome/__snapshots__/welcomePage.test.tsx.snap
  webapp/src/pages/welcome/welcomePage.tsx
  webapp/src/widgets/buttons/button.tsx
Labels: Contributor

#1739 Normalise and add safety checks to telemetry code
  webapp/src/components/cardDialog.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/components/viewMenu.tsx
Labels: 2: Dev Review, CherryPick/Approved

#1747 Automated cherry pick of #1739
  webapp/src/components/cardDialog.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/components/viewMenu.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1722 Modify store creation not to fail on template initialization failure
  server/services/store/sqlstore/sqlstore.go
Labels: 2: QA Review, CherryPick/Approved

#1682 [GH-1351] Webapp Linter Fixes - Investigate / Update using any Record<string, any>
  webapp/src/blocks/block.ts
  webapp/src/blocks/workspace.ts
  webapp/src/components/properties/dateRange/dateRange.tsx
  webapp/src/user.tsx
  webapp/src/widgets/editableDayPicker.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1751 [GH-837]: Add unit tests for topBar
  webapp/src/components/__snapshots__/topBar.test.tsx.snap
  webapp/src/components/topBar.test.tsx
Labels: Contributor

#1529 [GH-1510] make calculation options translatable
  webapp/i18n/en.json
  webapp/src/components/calculations/calculation.tsx
  webapp/src/components/calculations/options.test.tsx
  webapp/src/components/calculations/options.tsx
  webapp/src/components/kanban/calculation/calculationOptions.test.tsx
Labels: 3: Reviews Complete, Contributor, Hacktoberfest, hacktoberfest-accepted

#1746 Redirect to new routes when visiting a board with the legacy ones
  webapp/src/app.tsx
  webapp/src/pages/boardPage.tsx
  webapp/src/utils.ts
Labels: 2: QA Review, CherryPick/Approved

#1752 Fixes issue with dates and daylight savings
  webapp/src/components/properties/dateRange/dateRange.tsx
Labels: 3: Reviews Complete

#1757 Fix failing test in Main
  webapp/src/components/kanban/calculation/calculationOptions.test.tsx
Labels: 2: Dev Review

#1667 Server generated ids
  server/api/api.go
  server/app/blocks.go
  server/client/client.go
  server/integrationtests/blocks_test.go
  server/model/block.go
  server/model/block_test.go
  webapp/src/blocks/block.ts
  webapp/src/components/centerPanel.tsx
  webapp/src/components/sidebar/sidebarAddBoardMenu.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
Labels: 2: QA Review

#1773 GH-1685: Error if workspace is undefined
  webapp/src/store/initialLoad.ts
Labels: 2: Dev Review, CherryPick/Approved

#1718 [GH-853]: Add unit tests for kanban
  webapp/src/components/kanban/__snapshots__/kanban.test.tsx.snap
  webapp/src/components/kanban/kanban.test.tsx
Labels: Contributor

#1774 Automated cherry pick of #1773
  webapp/src/store/initialLoad.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1778 Fix #1777. v0.10 changelog
  CHANGELOG.md
Labels: CherryPick/Approved

#1582 [GH-438] Web-clipper POC
  experiments/webext/.gitignore
  experiments/webext/.parcelrc
  experiments/webext/README.md
  experiments/webext/icons/19.png
  experiments/webext/icons/38.png
  experiments/webext/icons/48.png
  experiments/webext/icons/96.png
  experiments/webext/manifest.json
  experiments/webext/package-lock.json
  experiments/webext/package.json
  experiments/webext/src/utils/Board.ts
  experiments/webext/src/utils/networking.ts
  experiments/webext/src/utils/settings.ts
  experiments/webext/src/views/OptionsApp.scss
  experiments/webext/src/views/OptionsApp.tsx
  experiments/webext/src/views/PopupApp.scss
  experiments/webext/src/views/PopupApp.tsx
  experiments/webext/src/views/options.html
  experiments/webext/src/views/options.tsx
  experiments/webext/src/views/popup.html
  experiments/webext/src/views/popup.tsx
  experiments/webext/tsconfig.json
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1779 Add utm_source and campaign for links to main site
  website/site/content/download/mattermost/_index.md
Labels: 3: Reviews Complete

#1580 Vertically Center Aligned createdBy, createdAt, lastModifiedBy and lastModifiedAt Properties
  webapp/src/components/properties/createdAt/createdAt.scss
  webapp/src/components/properties/createdAt/createdAt.tsx
  webapp/src/components/properties/lastModifiedAt/lastModifiedAt.scss
  webapp/src/components/properties/lastModifiedAt/lastModifiedAt.tsx
  webapp/src/components/properties/lastModifiedBy/lastModifiedBy.scss
  webapp/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
  webapp/src/components/properties/user/user.scss
Labels: 3: Reviews Complete, Contributor, hacktoberfest-accepted

#1785 Automated cherry pick of #1771
  webapp/src/components/kanban/kanban.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1753 Fix for feature flag handling
  mattermost-plugin/server/configuration.go
  mattermost-plugin/server/configuration_test.go
  mattermost-plugin/server/plugin.go
  server/server/server.go
Labels: 3: Reviews Complete

#1763 GH-1692: Show card preview in @mention notification DM
  mattermost-plugin/server/plugin.go
Labels: 3: Reviews Complete, CherryPick/Approved

#1790 Automated cherry pick of #1763
  mattermost-plugin/server/plugin.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1770 Fix GH-1727: Board calculations: Dates are cut off
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanban.test.tsx.snap
  webapp/src/components/kanban/calculation/__snapshots__/calculation.test.tsx.snap
  webapp/src/components/kanban/calculation/calculation.scss
  webapp/src/components/kanban/calculation/calculation.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1719 Fixed sort by date
  webapp/src/store/cards.ts
Labels: Contributor

#1783 Fixing styles on product switcher menu
  webapp/src/styles/main.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#1791 Automated cherry pick of #1783
  webapp/src/styles/main.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1768 Fix message
  webapp/i18n/en.json
  webapp/src/components/sidebar/deleteBoardDialog.tsx
Labels: Contributor

#1781 [GH-840]: add unit tests for workspace
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/workspace.test.tsx
Labels: Contributor

#1748 Fix GH-1690: Default card template on a board template adds a card to the template, not the board
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/cardDialog.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/gallery/galleryCard.test.tsx
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/mutator.test.ts
  webapp/src/mutator.ts
Labels: CherryPick/Approved

#1787 GH-1024 - Updating table row css
  webapp/src/components/table/table.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#1720 Show a refresh banner on plugin update
  mattermost-plugin/webapp/src/index.tsx
  webapp/i18n/en.json
  webapp/src/app.tsx
  webapp/src/components/newVersionBanner.scss
  webapp/src/components/newVersionBanner.tsx
  webapp/src/wsclient.ts
Labels: 2: QA Review, CherryPick/Approved

#1786 Only allow routes without workspace prefix if you are in non-plugin mode
  webapp/src/app.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1794 Updating unfurl UI
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.scss
Labels: 2: Dev Review, CherryPick/Approved

#1797 Automated cherry pick of #1794
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1776 Adds data migrations and the unique IDs migration
  linux/go.sum
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  mattermost-plugin/server/plugin.go
  server/go.mod
  server/go.sum
  server/server/server.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/data_migrations_test.go
  server/services/store/sqlstore/helpers_test.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/params.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/sqlstore/system.go
  server/services/store/store.go
  server/services/store/storetests/system.go
Labels: 2: QA Review

#1799 Fixing Adding content bug
  webapp/src/components/addContentMenuItem.tsx
  webapp/src/components/cardDetail/cardDetailContents.tsx
  webapp/src/components/cardDetail/cardDetailContext.tsx
  webapp/src/components/cardDetail/imagePaste.tsx
Labels: 2: Dev Review, 2: QA Review

#1684 [GH-1655] Card Delete : added Confirmation Dialog
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
  webapp/src/components/calculations/calculations.ts
  webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
  webapp/src/components/cardDetail/cardDetailProperties.test.tsx
  webapp/src/components/cardDetail/cardDetailProperties.tsx
  webapp/src/components/cardDialog.test.tsx
  webapp/src/components/cardDialog.tsx
  webapp/src/components/confirmationDialogBox.scss
  webapp/src/components/confirmationDialogBox.test.tsx
  webapp/src/components/confirmationDialogBox.tsx
  webapp/src/components/kanban/kanbanCard.test.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/widgets/buttons/button.scss
Labels: 1: UX Review, 2: Dev Review, Contributor, Hacktoberfest, hacktoberfest-accepted

#1808 fixing readme broken since #1663 completed
  README.md
Labels: Contributor

#1807 Shows the version change banner only on plugin update and tries to reconnect when the interface is refreshed
  mattermost-plugin/webapp/src/index.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
  webapp/src/wsclient.ts
Labels: CherryPick/Candidate

#1708 [GH-1694] Fix the issue where clicking on the + button at the top of a board group wouldn't open the newly-added card
  webapp/cypress/integration/createBoard.js
  webapp/src/components/kanban/kanbanColumnHeader.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1703 [GH-856]: Add unit tests for kanbanColumnHeader
  webapp/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/src/components/kanban/kanbanColumnHeader.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1829 GH-1519 - Fixing color on template picker
  webapp/src/components/emptyCenterPanel.scss
Labels: 2: Dev Review

#1842 Fix #1839. Update Mac App for v0.10.0
  mac/Focalboard.xcodeproj/project.pbxproj
  mac/Focalboard/Base.lproj/Main.storyboard
  mac/Focalboard/Globals.swift
  mac/Focalboard/WhatsNewViewController.swift
  mac/Focalboard/whatsnew.txt
Labels: CherryPick/Approved, CherryPick/Candidate

#1843 Automated cherry pick of #1842
  mac/Focalboard.xcodeproj/project.pbxproj
  mac/Focalboard/Base.lproj/Main.storyboard
  mac/Focalboard/Globals.swift
  mac/Focalboard/WhatsNewViewController.swift
  mac/Focalboard/whatsnew.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1800 425|Added unit tests for workspaces.go
  server/app/workspaces.go
  server/app/workspaces_test.go
Labels: Contributor

#1343 Update README.md
  website/README.md
Labels: 3: Reviews Complete

#1679 [GH-42] Cypress tests for login actions
  webapp/cypress.json
  webapp/cypress/config.json
  webapp/cypress/global.d.ts
  webapp/cypress/integration/createBoard.js
  webapp/cypress/integration/createBoard.ts
  webapp/cypress/integration/homepage.js
  webapp/cypress/integration/loginActions.ts
  webapp/cypress/support/commands.js
  webapp/cypress/support/commands.ts
  webapp/cypress/support/index.js
  webapp/cypress/support/index.ts
  webapp/cypress/tsconfig.json
  webapp/package.json
  webapp/src/pages/boardPage.tsx
  webapp/tsconfig.json
Labels: 3: Reviews Complete, Contributor, Hacktoberfest, hacktoberfest-accepted

#1637 [GH-830]: Add unit tests for dialog
  webapp/src/components/__snapshots__/dialog.test.tsx.snap
  webapp/src/components/dialog.test.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1590 [GH-1539] Implement searching for the individual words in workspaces
  webapp/src/pages/dashboard/__snapshots__/centerContent.test.tsx.snap
  webapp/src/pages/dashboard/centerContent.test.tsx
  webapp/src/pages/dashboard/centerContent.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#1853 Fixed issue with desktop app causing white screen
  webapp/src/app.tsx
Labels: CherryPick/Approved, CherryPick/Candidate

#1810 [GH-836]: Add unit tests for shareBoardComponent
  webapp/src/components/__snapshots__/shareBoardComponent.test.tsx.snap
  webapp/src/components/shareBoardComponent.test.tsx
Labels: Contributor

#1741 Implementation of Calendar MVP
  mattermost-plugin/server/configuration.go
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/blocks/boardView.ts
  webapp/src/components/calendar/__snapshots__/fullCalendar.test.tsx.snap
  webapp/src/components/calendar/fullCalendar.test.tsx
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/components/centerPanel.tsx
  webapp/src/components/properties/dateRange/dateRange.tsx
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewHeader/viewHeaderDisplayByMenu.tsx
  webapp/src/components/viewMenu.test.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/components/workspace.tsx
  webapp/src/csvExporter.ts
  webapp/src/mutator.ts
  webapp/src/store/views.ts
Labels: 1: UX Review, 2: Dev Review, 2: QA Review

#1862 GH-1837 - Updating link css
  webapp/src/components/markdownEditor.scss
Labels: CherryPick/Approved

#1869 GH-1805: Replace unfurl link with card title
  mattermost-plugin/server/plugin.go
Labels: 3: Reviews Complete

#1836 GH-1835: Show Autocomplete Textbox when At Mentioning Users in Comments or Content Section
  webapp/cypress/integration/createBoard.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/__snapshots__/markdownEditor.test.tsx.snap
  webapp/src/components/__snapshots__/viewTitle.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailContents.test.tsx.snap
  webapp/src/components/cardDetail/cardDetailContents.test.tsx
  webapp/src/components/cardDetail/commentsList.tsx
  webapp/src/components/cardDialog.test.tsx
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/content/__snapshots__/textElement.test.tsx.snap
  webapp/src/components/content/textElement.test.tsx
  webapp/src/components/contentBlock.test.tsx
  webapp/src/components/markdownEditor.test.tsx
  webapp/src/components/markdownEditor.tsx
  webapp/src/components/markdownEditorInput/markdownEditorInput.scss
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/components/viewTitle.test.tsx
  webapp/src/components/workspace.test.tsx
  webapp/webpack.common.js
Labels: 3: Reviews Complete

#1854 dist: build linux/darwin arm64 targets
  mattermost-plugin/Makefile
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
Labels: 3: Reviews Complete

#1865 CalendarView Remove Feature flag
  webapp/src/components/centerPanel.tsx
  webapp/src/components/viewMenu.tsx
Labels: 2: Dev Review

#1875 GH-1284 - Fixing alignment of properties on cards
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/properties/dateRange/dateRange.scss
  webapp/src/components/properties/user/__snapshots__/user.test.tsx.snap
  webapp/src/components/properties/user/user.tsx
Labels: 2: Dev Review

#1861 Properly generating patch diffs from two blocks
  webapp/src/blocks/__snapshots__/block.test.ts.snap
  webapp/src/blocks/block.test.ts
  webapp/src/blocks/block.ts
  webapp/src/components/content/checkboxElement.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1876 GH-1051 - Aligning card title with emojis
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/components/kanban/kanbanCard.scss
  webapp/src/components/table/table.scss
Labels: 2: Dev Review

#1892 GH-1864 Add + sign to add new event.
  webapp/src/components/calendar/__snapshots__/fullCalendar.test.tsx.snap
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/calendar/fullcalendar.scss
Labels: 3: Reviews Complete, CherryPick/Approved
