Repository mattermost-community/focalboard, pull requests merged in 2021-09, with the labels that each got.

#1069 Plugin telemetry
  .github/workflows/build-mac.yml
  .github/workflows/build-ubuntu.yml
  .github/workflows/build-win-wpf.yml
  .github/workflows/dev-release.yml
  .github/workflows/plugin-release.yml
  .github/workflows/prod-release.yml
  mattermost-plugin/server/plugin.go
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/webpack.config.js
  server/api/api.go
  server/app/clientConfig.go
  server/model/clientConfig.go
  server/services/config/config.go
  webapp/src/app.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/config/clientConfig.ts
  webapp/src/octoClient.ts
  webapp/src/telemetry/telemetry.ts
  webapp/src/telemetry/telemetryClient.test.ts
  webapp/src/telemetry/telemetryClient.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#1138 1112 - Updating button active state in viewHeader
  mattermost-plugin/webapp/src/plugin.scss
  webapp/src/components/viewHeader/viewHeader.scss
  webapp/src/widgets/buttons/button.scss
Labels: 3: Reviews Complete

#1134 GH-1133 add/reset languages, make single language source
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/sidebar/sidebarSettingsMenu.tsx
  webapp/src/constants.ts
  webapp/src/i18n.tsx
Labels: 1: PM Review, 2: Dev Review

#1110 Added support for subpaths in siteURL
  mattermost-plugin/webapp/src/index.tsx
  webapp/src/octoClient.ts
  webapp/src/wsclient.ts
Labels: 3: Reviews Complete

#1149 [GH-1130] Fixes 'Today' button not selecting date and entered date not being selected in calendar
  webapp/src/components/properties/dateRange/dateRange.test.tsx
  webapp/src/components/properties/dateRange/dateRange.tsx
Labels: 3: Reviews Complete

#1158 Workspace Switcher - include channels with no workspaces and boards
  server/services/store/sqlstore/workspaces.go
  webapp/src/components/workspaceSwitcher/workspaceOptions.tsx
Labels: 2: Dev Review

#1157 1095 - Updating global menu color for plugin
  mattermost-plugin/webapp/src/plugin.scss
Labels: 2: Dev Review, 2: QA Review

#1184 Not importing compass-icons on plugin mode
  webapp/package-lock.json
  webapp/package.json
  webapp/src/fonts/compass-icons/compass-icons.eot
  webapp/src/fonts/compass-icons/compass-icons.svg
  webapp/src/fonts/compass-icons/compass-icons.ttf
  webapp/src/fonts/compass-icons/compass-icons.woff
  webapp/src/fonts/compass-icons/compass-icons.woff2
  webapp/src/main.tsx
  webapp/src/styles/_compass-icons.scss
  webapp/src/styles/main.scss
Labels: CherryPick/Approved

#1185 Respect the mattermost icon when focalboard is used as a plugin
  mattermost-plugin/webapp/src/index.tsx
  webapp/src/utils.ts
Labels: CherryPick/Approved

#1174 GH-1136 - fix for when property value is an array
  webapp/src/components/__snapshots__/propertyValueElement.test.tsx.snap
  webapp/src/components/propertyValueElement.test.tsx
  webapp/src/components/propertyValueElement.tsx
Labels: 2: Dev Review, CherryPick/Candidate

#1179 Displayed channels names for DMs in user workspace list
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/workspaces.go
Labels: 3: Reviews Complete

#1147 @mention support
  NOTICE.txt
  linux/main.go
  mattermost-plugin/server/notifications.go
  mattermost-plugin/server/plugin.go
  server/app/app.go
  server/app/blocks.go
  server/go.mod
  server/integrationtests/clienttestlib.go
  server/main/main.go
  server/server/params.go
  server/server/server.go
  server/services/notify/notifylogger/logger_backend.go
  server/services/notify/notifymentions/delivery.go
  server/services/notify/notifymentions/extract.go
  server/services/notify/notifymentions/extract_test.go
  server/services/notify/notifymentions/mentions.go
  server/services/notify/notifymentions/mentions_backend.go
  server/services/notify/notifymentions/mentions_test.go
  server/services/notify/plugindelivery/message.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/user.go
  server/services/notify/plugindelivery/user_test.go
  server/services/notify/service.go
Labels: 2: Dev Review, Docs/Needed

#1178 Update en.json - UI capitalization
  webapp/cypress/integration/createBoard.js
  webapp/i18n/en.json
  webapp/src/components/cardDialog.tsx
  webapp/src/components/propertyValueElement.tsx
  webapp/src/components/shareBoardComponent.tsx
  webapp/src/components/sidebar/sidebarAddBoardMenu.tsx
  webapp/src/components/sidebar/sidebarUserMenu.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/components/workspace.tsx
  webapp/src/pages/registerPage.tsx
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/propertyMenu.tsx
  webapp/src/widgets/valueSelector.tsx
Labels: 2: Dev Review

#1194 Focalboard UI Fixes
  mattermost-plugin/webapp/src/plugin.scss
  webapp/src/components/kanban/kanban.scss
  webapp/src/components/viewTitle.scss
  webapp/src/styles/main.scss
  webapp/src/widgets/menu/menu.scss
Labels: 2: Dev Review

#1177 FTUE - Dashboard
  webapp/i18n/en.json
  webapp/src/app.tsx
  webapp/src/components/sidebar/sidebar.scss
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/workspaceSwitcher/__snapshots__/workspaceOptions.test.tsx.snap
  webapp/src/components/workspaceSwitcher/__snapshots__/workspaceSwitcher.test.tsx.snap
  webapp/src/components/workspaceSwitcher/workspaceOptions.scss
  webapp/src/components/workspaceSwitcher/workspaceOptions.tsx
  webapp/src/components/workspaceSwitcher/workspaceSwitcher.scss
  webapp/src/components/workspaceSwitcher/workspaceSwitcher.tsx
  webapp/src/pages/dashboard/centerContent.tsx
  webapp/src/pages/dashboard/dashboardPage.scss
  webapp/src/pages/dashboard/dashboardPage.tsx
  webapp/src/pages/dashboardPage.scss
  webapp/src/pages/dashboardPage.tsx
  webapp/src/store/workspace.ts
  webapp/src/styles/_typography.scss
  webapp/src/svg/dashboard-onboarding.tsx
  webapp/src/svg/search-illustration.tsx
  webapp/static/onboardingBg.jpg
Labels: 3: Reviews Complete, Documentation, Docs/Needed

#1180 Update import dependencies
  import/asana/package-lock.json
  import/notion/package-lock.json
  import/todoist/package-lock.json
  import/trello/package-lock.json
Labels: 3: Reviews Complete

#1193 MM-38342 plugin logging
  linux/go.mod
  linux/go.sum
  mattermost-plugin/build/manifest/main.go
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  mattermost-plugin/server/logtarget.go
  mattermost-plugin/server/manifest.go
  mattermost-plugin/server/plugin.go
  server/go.mod
  server/go.sum
  server/integrationtests/clienttestlib.go
  server/main/main.go
  server/services/audit/audit.go
Labels: 2: Dev Review

#1213 Propagate block changes to all of the cluster nodes in plugin mode
  mattermost-plugin/server/plugin.go
  server/ws/common.go
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_cluster.go
  server/ws/server.go
Labels: 2: Dev Review, 2: QA Review

#1211 1205 - Updating workspace switcher css
  webapp/src/components/sidebar/sidebar.scss
  webapp/src/components/workspaceSwitcher/workspaceOptions.scss
  webapp/src/components/workspaceSwitcher/workspaceSwitcher.scss
Labels: 2: Dev Review, 2: QA Review

#1187 Config for share board
  config.json
  mattermost-plugin/plugin.json
  mattermost-plugin/server/configuration.go
  mattermost-plugin/server/configuration_test.go
  mattermost-plugin/server/manifest.go
  mattermost-plugin/server/plugin.go
  mattermost-plugin/webapp/src/index.tsx
  server/api/api.go
  server/app/app.go
  server/app/app_test.go
  server/app/clientConfig.go
  server/app/clientConfig_test.go
  server/model/clientConfig.go
  server/server/server.go
  server/services/config/config.go
  server/utils/utils.go
  server/ws/adapter.go
  server/ws/plugin_adapter.go
  server/ws/server.go
  webapp/src/app.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewHeader/viewHeaderActionsMenu.test.tsx
  webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
  webapp/src/components/workspace.tsx
  webapp/src/config/clientConfig.ts
  webapp/src/store/clientConfig.ts
  webapp/src/store/index.ts
  webapp/src/wsclient.ts
Labels: 2: Dev Review, CherryPick/Candidate

#1216 ensure @mentions only sent to team members
  mattermost-plugin/server/notifications.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/user.go
  server/services/notify/plugindelivery/user_test.go
Labels: 3: Reviews Complete

#1255 Fix elevation-1 variable
  webapp/src/styles/focalboard-variables.scss
Labels: 2: Dev Review, CherryPick/Approved

#1292 GH-1244 add setting -webkit-user-select and others for MenuWrapper
  webapp/src/widgets/menuWrapper.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#1306 disable flakey test
  server/integrationtests/blocks_test.go
Labels: 3: Reviews Complete

#1297 Added MySQL migration for applying column level collation
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/migrations/migrations_files/000012_match_column_collation.down.sql
  server/services/store/sqlstore/migrations/migrations_files/000012_match_column_collation.up.sql
Labels: 2: QA Review, CherryPick/Approved

#1296 Allow no workspace and send to the dashboard if that happens
  webapp/src/app.tsx
  webapp/src/pages/boardPage.tsx
  webapp/src/store/initialLoad.ts
Labels: 2: QA Review, CherryPick/Approved

#1257 Adds modd based targets that watch both server and webapp
  Makefile
  modd-servertest.conf
  modd.conf
Labels: 3: Reviews Complete

#1300 Adds the watch-plugin make target to improve the development experience
  Makefile
  modd-watchplugin.conf
Labels: 2: Dev Review

#1314 Ignores manifest.go file on watch-plugin to avoid reboot loop
  modd-watchplugin.conf
Labels: 2: Dev Review

#1298 GH-1263 - Updating sidebar width
  webapp/src/components/sidebar/sidebar.scss
Labels: 2: Dev Review

#1299 Adds workspaceID to blocks and makes board page only reacts to the workspace updates
  server/app/blocks.go
  server/model/block.go
  server/services/store/sqlstore/blocks.go
  server/ws/plugin_adapter.go
  server/ws/server.go
  webapp/src/blocks/block.ts
  webapp/src/components/content/checkboxElement.test.tsx
  webapp/src/pages/boardPage.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1328 Remove indir directive as it's causing problems in OSX systems
  modd-servertest.conf
  modd-watchplugin.conf
  modd.conf
Labels: 2: Dev Review

#1114 [GH-1059] Fix empty placeholders in the card dialog
  webapp/src/components/__snapshots__/propertyValueElement.test.tsx.snap
  webapp/src/components/cardDetail/cardDetailProperties.tsx
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/components/properties/dateRange/__snapshots__/dateRange.test.tsx.snap
  webapp/src/components/properties/dateRange/dateRange.scss
  webapp/src/components/properties/dateRange/dateRange.test.tsx
  webapp/src/components/properties/dateRange/dateRange.tsx
  webapp/src/components/properties/link/__snapshots__/link.test.tsx.snap
  webapp/src/components/properties/link/link.tsx
  webapp/src/components/properties/multiSelect/multiSelect.tsx
  webapp/src/components/properties/user/__snapshots__/user.test.tsx.snap
  webapp/src/components/properties/user/user.tsx
  webapp/src/components/propertyValueElement.test.tsx
  webapp/src/components/propertyValueElement.tsx
  webapp/src/components/table/tableRow.tsx
  webapp/src/widgets/label.scss
  webapp/src/widgets/valueSelector.tsx
Labels: Lifecycle/1:stale

#1065 [GH-1057] Highlighting on hover for property values in the card dialog
  webapp/src/components/__snapshots__/propertyValueElement.test.tsx.snap
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/kanban/kanbanCard.scss
  webapp/src/components/properties/createdAt/createdAt.tsx
  webapp/src/components/properties/dateRange/__snapshots__/dateRange.test.tsx.snap
  webapp/src/components/properties/dateRange/dateRange.scss
  webapp/src/components/properties/dateRange/dateRange.tsx
  webapp/src/components/properties/lastModifiedAt/__snapshots__/lastModifiedAt.test.tsx.snap
  webapp/src/components/properties/lastModifiedAt/lastModifiedAt.tsx
  webapp/src/components/properties/lastModifiedBy/__snapshots__/lastModifiedBy.test.tsx.snap
  webapp/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
  webapp/src/components/properties/link/__snapshots__/link.test.tsx.snap
  webapp/src/components/properties/link/link.scss
  webapp/src/components/properties/link/link.tsx
  webapp/src/components/properties/user/__snapshots__/user.test.tsx.snap
  webapp/src/components/properties/user/user.tsx
  webapp/src/components/propertyValueElement.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/widgets/buttons/button.scss
  webapp/src/widgets/editable.tsx
Labels: Lifecycle/1:stale

#1329 Fix closing tab mattermost hang issue
  mattermost-plugin/webapp/src/index.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1317 GH-1312 - Update title when running a plugin
  webapp/src/pages/boardPage.tsx
Labels: 3: Reviews Complete, CherryPick/Candidate

#1231 Start Welcome Page
  mattermost-plugin/webapp/src/index.tsx
  webapp/cypress/integration/createBoard.js
  webapp/i18n/en.json
  webapp/src/app.tsx
  webapp/src/pages/boardPage.tsx
  webapp/src/pages/welcome/welcomePage.scss
  webapp/src/pages/welcome/welcomePage.tsx
  webapp/src/types/images.d.ts
  webapp/src/userSettings.ts
  webapp/src/widgets/buttons/button.scss
  webapp/static/boards-welcome.png
  webapp/webpack.common.js
Labels: 3: Reviews Complete, CherryPick/Approved

#1175 Update templates for issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/doc_improvement.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: 3: Reviews Complete

#1342 Update CONTRIBUTING.md with new Docs info
  CONTRIBUTING.md
Labels: 1: PM Review

#1323 [GH-1082] Add count and percent table calculations for checkbox
  webapp/src/components/calculations/calculations.test.tsx
  webapp/src/components/calculations/calculations.ts
  webapp/src/components/calculations/options.tsx
Labels: 3: Reviews Complete

#1324 Recovers inactive websockets connections on reconnect in plugin mode
  server/auth/auth.go
  server/auth/mocks/mockauth_interface.go
  server/ws/helpers_test.go
  server/ws/mocks/mockpluginapi.go
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_client.go
  server/ws/plugin_adapter_test.go
  webapp/src/utils.ts
  webapp/src/wsclient.ts
Labels: 2: Dev Review, CherryPick/Approved

#1220 add additional telemetry tracking
  mattermost-plugin/webapp/src/index.tsx
  webapp/src/blocks/board.ts
  webapp/src/blocks/boardView.ts
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/sidebar/boardTemplateMenuItem.tsx
  webapp/src/mutator.ts
  webapp/src/telemetry/telemetryClient.ts
Labels: 1: PM Review, 3: Reviews Complete

#1375 GH-1362: Fix missing return type on function
  webapp/src/components/cardDialog.tsx
  webapp/src/components/globalHeader/globalHeader.tsx
  webapp/src/components/table/tableRows.tsx
  webapp/src/components/viewHeader/viewHeaderSearch.tsx
  webapp/src/nativeApp.ts
  webapp/src/octoClient.ts
  webapp/src/pages/boardPage.tsx
  webapp/src/svg/dashboard-onboarding.tsx
  webapp/src/svg/search-illustration.tsx
  webapp/src/userSettings.ts
Labels: 2: Dev Review

#1376 gh-1364 - remove file causing lint warnings
  webapp/@custom_types/pgtools.d.ts
Labels: 2: Dev Review

#1377 Allowed dashboard to scroll
  webapp/src/pages/dashboard/dashboardPage.scss
Labels: 2: Dev Review

#1303 [GH-1291] Fix drag and drop for gallery card
  webapp/src/components/gallery/galleryCard.scss
Labels: 2: Dev Review
