Repository mattermost-community/focalboard, pull requests merged in 2021-08, with the labels that each got.

#811 Fix bug on save on unmount
  webapp/src/components/propertyValueElement.tsx
Labels: 2: Dev Review

#870 Match the user settings for icon prefill on card for template
  webapp/src/mutator.ts
Labels: 2: Dev Review

#825 [GH-815] Fix kanban board height
  webapp/src/components/kanban/kanban.scss
Labels: 3: Reviews Complete

#689 Update links to 0.7.3
  website/site/content/download/mattermost/latest-plugin/_index.md
Labels: Lifecycle/1:stale

#822 [GH-817] Fix for auto-size column in Firefox
  webapp/src/utils.ts
Labels: 3: Reviews Complete

#823 Add clear button to value selectors
  webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
  webapp/src/components/propertyValueElement.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
  webapp/src/styles/main.scss
  webapp/src/widgets/valueSelector.scss
  webapp/src/widgets/valueSelector.tsx
Labels: 3: Reviews Complete

#880 update text for shared board
  webapp/i18n/en.json
  webapp/src/components/shareBoardComponent.tsx
Labels: 1: PM Review, 1: UX Review

#877 Adding support for patch blocks
  server/api/api.go
  server/app/blocks.go
  server/client/client.go
  server/go.tools.mod
  server/go.tools.sum
  server/integrationtests/blocks_test.go
  server/model/block.go
  server/services/metrics/metrics.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/initializations/bindata.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  server/swagger/docs/html/.openapi-generator/VERSION
  server/swagger/docs/html/index.html
  server/swagger/swagger.yml
  webapp/src/blocks/block.ts
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/content/textElement.tsx
  webapp/src/components/table/tableRow.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewTitle.tsx
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
Labels: 3: Reviews Complete

#660 Implement Date ranges
  .vscode/settings.json
  webapp/i18n/en.json
  webapp/src/components/properties/dateRange/__snapshots__/dateRange.test.tsx.snap
  webapp/src/components/properties/dateRange/dateRange.scss
  webapp/src/components/properties/dateRange/dateRange.test.tsx
  webapp/src/components/properties/dateRange/dateRange.tsx
  webapp/src/components/propertyValueElement.tsx
  webapp/src/octoUtils.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
  webapp/src/widgets/editable.tsx
  webapp/src/widgets/editableDayPicker.scss
Labels: 1: PM Review, 2: Dev Review

#913 Updating focalboard icon and text
  webapp/src/components/sidebar/sidebar.scss
  webapp/src/components/sidebar/sidebarUserMenu.scss
  webapp/src/components/sidebar/sidebarUserMenu.tsx
  webapp/src/fonts/compass-icons/compass-icons.eot
  webapp/src/fonts/compass-icons/compass-icons.svg
  webapp/src/fonts/compass-icons/compass-icons.ttf
  webapp/src/fonts/compass-icons/compass-icons.woff
  webapp/src/fonts/compass-icons/compass-icons.woff2
  webapp/src/styles/_compass-icons.scss
  webapp/src/widgets/icons/logo.tsx
Labels: 3: Reviews Complete

#761 Table calculations
  server/services/store/storetests/blocks.go
  webapp/src/blocks/board.ts
  webapp/src/blocks/boardView.ts
  webapp/src/blocks/card.ts
  webapp/src/components/calculations/__snapshots__/calculation.test.tsx.snap
  webapp/src/components/calculations/__snapshots__/options.test.tsx.snap
  webapp/src/components/calculations/calculation.scss
  webapp/src/components/calculations/calculation.test.tsx
  webapp/src/components/calculations/calculation.tsx
  webapp/src/components/calculations/calculations.test.tsx
  webapp/src/components/calculations/calculations.ts
  webapp/src/components/calculations/options.test.tsx
  webapp/src/components/calculations/options.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/calculation/__snapshots__/calculationRow.test.tsx.snap
  webapp/src/components/table/calculation/calculationRow.scss
  webapp/src/components/table/calculation/calculationRow.test.tsx
  webapp/src/components/table/calculation/calculationRow.tsx
  webapp/src/components/table/table.scss
  webapp/src/components/table/table.tsx
  webapp/src/components/table/tableRow.tsx
  webapp/src/theme.ts
  webapp/src/utils.ts
  webapp/src/widgets/icons/chevronUp.tsx
Labels: 3: Reviews Complete

#926 fix css for theme name changes
  webapp/src/components/properties/dateRange/dateRange.scss
Labels: 3: Reviews Complete

#915 [GH 888] Always show the close button in the Dialog component's toolbar
  webapp/src/components/dialog.tsx
Labels: 3: Reviews Complete

#929 Fix simplified chinesse language
  webapp/src/i18n.tsx
Labels: CherryPick/Approved

#932 Fix flaky test
  webapp/src/components/cardDetail/cardDetailContents.test.tsx
Labels: 2: Dev Review

#947 Moving logo and title to the global header
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/plugin.scss
  webapp/src/components/globalHeader/globalHeader.scss
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarUserMenu.scss
  webapp/src/components/sidebar/sidebarUserMenu.tsx
  webapp/src/pages/boardPage.tsx
  webapp/src/widgets/icons/logo.scss
  webapp/src/widgets/icons/logo.tsx
Labels: CherryPick/Approved

#949 Fixed missing CSS vars
  webapp/src/components/calculations/__snapshots__/options.test.tsx.snap
  webapp/src/components/calculations/options.tsx
  webapp/src/components/properties/dateRange/dateRange.scss
  webapp/src/components/table/calculation/calculationRow.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#939 GH-937 - add overflow: hidden to prevent scrolling
  webapp/src/styles/main.scss
Labels: CherryPick/Approved

#952 Added ability for calculation menu to open wherever there is available space
  webapp/src/components/calculations/options.tsx
Labels: 2: Dev Review

#950 Fix global header menu z-index for focalboard
  mattermost-plugin/webapp/src/plugin.scss
Labels: 2: Dev Review, CherryPick/Approved

#954 Avoided double horizontal scrollbars
  webapp/src/components/centerPanel.scss
Labels: 2: Dev Review

#951 Using an icon name instead of the component for registerProduct
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/plugin.scss
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
Labels: 2: Dev Review, CherryPick/Approved

#962 Fix #934. Sidebar hide-unhide as plugin.
  webapp/src/components/sidebar/sidebar.scss
  webapp/src/components/sidebar/sidebar.tsx
Labels: 2: Dev Review, CherryPick/Approved

#968 GH-964: Allow overflow in Gallery View
  webapp/src/components/gallery/gallery.scss
Labels: 2: Dev Review, CherryPick/Approved

#961 GH-958 - fix for wrong filter deletion
  webapp/src/components/viewHeader/filterEntry.tsx
Labels: 2: Dev Review, CherryPick/Approved

#970 Cleanup the store on the initial load call
  webapp/src/store/boards.ts
  webapp/src/store/cards.ts
  webapp/src/store/comments.ts
  webapp/src/store/contents.ts
  webapp/src/store/views.ts
Labels: CherryPick/Approved

#971 Fix GH-955 and GH-936
  webapp/src/components/markdownEditor.tsx
  webapp/src/styles/main.scss
  webapp/src/theme.ts
Labels: 2: Dev Review, CherryPick/Approved

#972 Fix redirect problems on product switch
  webapp/src/pages/boardPage.tsx
Labels: 2: Dev Review, CherryPick/Approved

#380 [GH-314] Export native app user settings on change
  mac/Focalboard/ViewController.swift
  webapp/src/app.tsx
  webapp/src/i18n.tsx
  webapp/src/main.tsx
  webapp/src/nativeApp.ts
  webapp/src/pages/boardPage.tsx
  webapp/src/theme.ts
  webapp/src/userSettings.ts
Labels: 3: Reviews Complete

#985 GH-894 - Removing uppercase from column header
  webapp/src/widgets/label.scss
Labels: 2: Dev Review

#1000 Adjust image size to content column size
  webapp/src/components/contentBlock.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#984 GH-959 - Fixing board headers on scroll
  webapp/src/components/centerPanel.scss
  webapp/src/components/kanban/kanban.scss
  webapp/src/components/table/table.scss
  webapp/src/components/viewHeader/viewHeader.scss
Labels: 2: Dev Review

#983 GH-965 - Updating global nav right sidebar buttons
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/globalHeader/globalHeader.scss
  webapp/src/components/globalHeader/globalHeader.tsx
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.scss
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
  webapp/src/widgets/icons/settings.scss
Labels: 2: Dev Review

#1025 Fixing text selection in all inputs for Firefox
  webapp/src/styles/main.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#987 Add paste/drop images on cards
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/cardDetail/imagePaste.tsx
Labels: 2: Dev Review

#1023 GH-989 add boards to shared component link
  webapp/src/components/shareBoardComponent.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1022 GH-992 Show error if Read-Only board is not available
  webapp/src/pages/boardPage.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1012 GH-994 - Updating color for global header menu
  mattermost-plugin/webapp/src/plugin.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#1038 Fixing some color variables
  mattermost-plugin/webapp/src/plugin.scss
  webapp/src/widgets/icons/focalboard_logo.scss
  webapp/src/widgets/icons/help.scss
  webapp/src/widgets/icons/logo.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#1037 [GH-1033] Prevent opening card dialog when link for URL is clicked.
  webapp/src/components/properties/link/link.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1045 1004-add-board-menu
  webapp/src/components/sidebar/boardTemplateMenuItem.tsx
  webapp/src/widgets/menu/menu.tsx
Labels: 2: Dev Review

#1044 Fix border cut on kanban and gallery views
  webapp/src/components/centerPanel.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#1048 1005 - Updating padding on the share popup
  webapp/src/components/shareBoardComponent.scss
  webapp/src/components/shareBoardComponent.tsx
  webapp/src/components/sidebar/registrationLink.scss
Labels: 2: Dev Review, CherryPick/Approved

#1067 Remove duplicated restart on docker compose
  docker/docker-compose-db-nginx.yml
Labels: 3: Reviews Complete

#1020 Update focalboard to be compatible with mattermost v6
  .github/workflows/dev-release.yml
  .github/workflows/plugin-release.yml
  .github/workflows/prod-release.yml
  linux/go.sum
  mattermost-plugin/build/go.mod
  mattermost-plugin/build/go.sum
  mattermost-plugin/build/manifest/main.go
  mattermost-plugin/build/pluginctl/main.go
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  mattermost-plugin/plugin.json
  mattermost-plugin/server/main.go
  mattermost-plugin/server/manifest.go
  mattermost-plugin/server/plugin.go
  server/app/app.go
  server/app/files.go
  server/app/helper_test.go
  server/go.mod
  server/go.sum
  server/server/server.go
  server/services/metrics/metrics.go
  server/services/store/sqlstore/initializations/bindata.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/telemetry/mocks/ServerIface.go
Labels: 3: Reviews Complete

#1039 [GH-1011] Don't start editing of card description when the link is clicked
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 2: Dev Review, CherryPick/Approved

#1075 Fix Image Paste Messing with Content Block
  webapp/src/components/cardDetail/imagePaste.tsx
Labels: 3: Reviews Complete

#1070 1061 - Updating date picker
  webapp/src/components/properties/dateRange/dateRange.scss
Labels: 2: Dev Review

#1084 Updating cell alignment for table view
  webapp/src/components/table/table.scss
Labels: 2: Dev Review

#1062 update share url
  webapp/src/components/shareBoardComponent.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#1135 Add retry mechanism when opening WSClient in plugin mode
  mattermost-plugin/server/manifest.go
  webapp/src/wsclient.ts
Labels: 2: Dev Review

#1132 GH-1131 - fix for displaying global nav in focalboard
  mattermost-plugin/webapp/src/plugin.scss
Labels: 3: Reviews Complete, CherryPick/Approved
