Repository mattermost-community/focalboard, pull requests merged in 2022-07, with the labels that each got.

#2971 Showing only the right boards in the board switcher
  mattermost-plugin/server/plugin.go
  server/integrationtests/board_test.go
  server/integrationtests/pluginteststore.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review

#3263 Cherry-Pick: Adding the "contact admin" link (#3229)
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/cardLimitNotification.scss
  webapp/src/components/cardLimitNotification.tsx
  webapp/src/components/centerPanel.test.tsx
  webapp/src/telemetry/telemetryClient.ts
  webapp/src/widgets/__snapshots__/notification-box.test.tsx.snap
  webapp/src/widgets/notification-box.scss
  webapp/src/widgets/notification-box.test.tsx
  webapp/src/widgets/notification-box.tsx
Labels: 2: Dev Review

#3324 GH-2996 - Update text on Share Dialog
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/cardLimitNotification.tsx
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 2: Dev Review

#3321 Refactor "..." menu into component & add to Calendar view
  webapp/i18n/en.json
  webapp/src/components/calendar/__snapshots__/fullCalendar.test.tsx.snap
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/components/cardActionsMenu/__snapshots__/cardActionsMenu.test.tsx.snap
  webapp/src/components/cardActionsMenu/cardActionsMenu.test.tsx
  webapp/src/components/cardActionsMenu/cardActionsMenu.tsx
  webapp/src/components/cardDialog.tsx
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/kanban/kanbanCard.tsx
Labels: 1: UX Review

#3323 fix: delete `.action-cell` CSS bg color
  webapp/src/components/table/tableRow.scss
Labels: 2: Dev Review

#3337 Add loggin on cloud limits set
  server/app/cloud.go
Labels: 2: Dev Review, CherryPick/Candidate

#3340 Automated cherry pick of #3337
  server/app/cloud.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3244 User updates
  mattermost-plugin/server/configuration.go
  mattermost-plugin/server/configuration_test.go
  mattermost-plugin/server/plugin.go
  mattermost-plugin/server/plugin_test.go
  mattermost-plugin/webapp/src/index.tsx
  server/api/api.go
  server/app/clientConfig.go
  server/app/clientConfig_test.go
  server/model/clientConfig.go
  server/model/user.go
  server/services/config/config.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/content/textElement.test.tsx
  webapp/src/components/contentBlock.test.tsx
  webapp/src/components/markdownEditor.test.tsx
  webapp/src/components/markdownEditorInput/entryComponent/entryComponent.tsx
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/components/messages/cloudMessage.test.tsx
  webapp/src/components/properties/createdBy/createdBy.test.tsx
  webapp/src/components/properties/lastModifiedBy/lastModifiedBy.test.tsx
  webapp/src/components/properties/user/user.test.tsx
  webapp/src/components/properties/user/user.tsx
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/table.test.tsx
  webapp/src/components/viewTitle.test.tsx
  webapp/src/components/workspace.test.tsx
  webapp/src/config/clientConfig.ts
  webapp/src/store/clientConfig.ts
  webapp/src/test/testBlockFactory.ts
  webapp/src/user.tsx
  webapp/src/userSettings.ts
  webapp/src/utils.test.ts
  webapp/src/utils.ts
Labels: 2: Dev Review

#3344 [GH-3318] Fix flaky cypress test
  webapp/cypress/integration/cardURLProperty.ts
Labels: Contributor

#3332 Refactor `z-index` values to a SCSS map
  webapp/.stylelintrc.json
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/centerPanel.scss
  webapp/src/components/confirmationDialogBox.scss
  webapp/src/components/dialog.scss
  webapp/src/components/flashMessages.scss
  webapp/src/components/gallery/galleryCard.scss
  webapp/src/components/kanban/calculation/calculationOption.scss
  webapp/src/components/kanban/kanban.scss
  webapp/src/components/modal.scss
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/sidebar/sidebar.scss
  webapp/src/components/table/table.scss
  webapp/src/components/table/tableRow.scss
  webapp/src/components/topBar.scss
  webapp/src/components/tutorial_tour_tip/tutorial_tour_tip.scss
  webapp/src/components/workspace.scss
  webapp/src/styles/_z-index.scss
  webapp/src/styles/main.scss
  webapp/src/widgets/menu/menu.scss
  webapp/src/widgets/menu/subMenuOption.scss
  webapp/src/widgets/notificationBox/notificationBox.scss
  webapp/src/widgets/tooltip.scss
  webapp/src/widgets/valueSelector.scss
Labels: 2: Dev Review

#3341 Cloud Limit Fix - add BoardID to limited card
  server/model/block.go
Labels: 2: Dev Review

#3353 fix: render default LHS board icon
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.test.tsx
  webapp/src/components/sidebar/sidebarBoardItem.tsx
Labels: 1: UX Review, 2: Dev Review

#3315 Refactor websockets state and lifecycle
  mattermost-plugin/webapp/src/components/boardSelector.test.tsx
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  mattermost-plugin/webapp/src/components/boardsUnfurl/__snapshots__/boardsUnfurl.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.test.tsx
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoards.test.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
  mattermost-plugin/webapp/src/index.tsx
  server/api/api.go
  server/app/boards.go
  server/integrationtests/board_test.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  webapp/src/app.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
  webapp/src/components/withWebSockets.tsx
  webapp/src/hooks/websockets.tsx
  webapp/src/main.tsx
  webapp/src/octoClient.ts
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/pages/boardPage/websocketConnection.tsx
  webapp/src/store/boards.ts
  webapp/src/store/initialLoad.ts
  webapp/src/store/teams.ts
  webapp/src/wsclient.ts
Labels: 3: Reviews Complete

#3368 Fixed multiple styling fixes
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoardItem.test.tsx.snap
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoards.test.tsx.snap
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.scss
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoards.scss
  mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
  webapp/i18n/en.json
  webapp/src/components/shareBoard/shareBoard.test.tsx
Labels: 3: Reviews Complete

#3374 Fix mock early finish issue on test helpers
  mattermost-plugin/server/data_retention_test.go
  server/app/blocks_test.go
  server/app/files_test.go
  server/app/helper_test.go
  server/app/teams_test.go
  server/auth/auth_test.go
Labels: 2: Dev Review

#3382 Update Boards version to 7.3
  mac/Focalboard.xcodeproj/project.pbxproj
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review

#3393 fix: share modal user list overflow out of dialog
  webapp/src/components/shareBoard/shareBoard.scss
Labels: 1: UX Review, 2: Dev Review, CherryPick/Candidate

#3406 Updates the id of the migration lock
  server/services/store/sqlstore/migrate.go
Labels: 2: Dev Review, CherryPick/Approved

#3407 Automated cherry pick of #3406
  server/services/store/sqlstore/migrate.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3392 Adds more loglines to the database migrations and fixes some inconsistencies
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/migrate.go
Labels: 2: Dev Review, CherryPick/Approved

#3411 Automated cherry pick of #3393
  webapp/src/components/shareBoard/shareBoard.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3416 Openning the board in a new window from the RHS in channels
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3417 Removing unexpected roles from the team/user selector in share board modal
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3420 Replace query with exec on database update queries
  server/services/store/sqlstore/data_migrations.go
Labels: 2: Dev Review, CherryPick/Approved

#3428 Automated cherry pick of #3420
  server/services/store/sqlstore/data_migrations.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3421 Automated cherry pick of #3416
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3415 Improve the board creation from channels
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  mattermost-plugin/webapp/src/index.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/components/workspace.tsx
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx
  webapp/src/router.tsx
  webapp/src/types/index.d.ts
  webapp/src/utils.ts
Labels: 2: Dev Review, CherryPick/Approved

#3433 Automated cherry pick of #3415
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  mattermost-plugin/webapp/src/index.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/components/workspace.tsx
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx
  webapp/src/router.tsx
  webapp/src/types/index.d.ts
  webapp/src/utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3378 Handled err in acse of lack of user-channel membership
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#3434 Automated cherry pick of #3429
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3256 Store current input while user is changing.
  webapp/src/widgets/menu/textInputOption.tsx
  webapp/src/widgets/propertyMenu.test.tsx
  webapp/src/widgets/propertyMenu.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3438 Automated cherry pick of #3256
  webapp/src/widgets/menu/textInputOption.tsx
  webapp/src/widgets/propertyMenu.test.tsx
  webapp/src/widgets/propertyMenu.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3437 Move category creation and UUID update to a more performant data migration
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/migrations/000019_populate_categories.up.sql
  server/services/store/sqlstore/migrations/000020_populate_category_blocks.up.sql
Labels: 2: Dev Review, CherryPick/Approved

#3439 Automated cherry pick of #3437
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/migrations/000019_populate_categories.up.sql
  server/services/store/sqlstore/migrations/000020_populate_category_blocks.up.sql
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3390 Converted synthetic membership to natuaral for board's channel members
  server/app/boards.go
  server/app/boards_test.go
Labels: 2: Dev Review, CherryPick/Approved

#3440 Automated cherry pick of #3390
  server/app/boards.go
  server/app/boards_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3401 Update product adapter for changes in the UserService
  .github/workflows/lint-server.yml
  mattermost-plugin/build/gowork/main.go
  mattermost-plugin/product/api_adapter.go
Labels: 2: Dev Review

#3451 Manual cherry pick of #3378
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: Changelog/Not Needed, Docs/Not Needed

#3454 Add the creator of the board as a administrator of the board if it still belongs to the channel
  server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql
Labels: 3: Reviews Complete, CherryPick/Approved

#3455 Automated cherry pick of #3454
  server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3242 Board switcher keyboard shortcut navigation
  webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
  webapp/src/components/searchDialog/searchDialog.scss
  webapp/src/components/searchDialog/searchDialog.tsx
  webapp/src/constants.ts
Labels: 1: UX Review, 2: Dev Review, CherryPick/Approved

#3456 Automated cherry pick of #3242
  webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
  webapp/src/components/searchDialog/searchDialog.scss
  webapp/src/components/searchDialog/searchDialog.tsx
  webapp/src/constants.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3452 Automated cherry pick of #3432
  webapp/i18n/en.json
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/channelPermissionsRow.tsx
  webapp/src/components/shareBoard/shareBoard.test.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3450 Automated cherry pick of #3426
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/sidebar/sidebarCategory.scss
  webapp/src/components/sidebar/sidebarCategory.tsx
  webapp/src/widgets/menu/menu.tsx
  webapp/src/widgets/menu/menuUtil.ts
  webapp/src/widgets/menu/subMenuOption.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3468 fix(webapp): update template selector text
  webapp/i18n/en.json
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
  webapp/src/components/workspace.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3474 Automated cherry pick of #3468
  webapp/i18n/en.json
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
  webapp/src/components/workspace.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3441 Add enablePublicSharedBoards to admin guide
  website/site/content/guide/admin/_index.md
Labels: Contributor

#3473 reset when me changes
  webapp/src/pages/boardPage/boardPage.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3479 Add pull request template for Github
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: 1: PM Review, 2: Dev Review

#3335 Custom template's default card template works
  server/assets/templates-boardarchive/b7wnw9awd4pnefryhq51apbzb4c/board.jsonl
  server/assets/templates-boardarchive/bbn1888mprfrm5fjw9f1je9x3xo/board.jsonl
  server/assets/templates-boardarchive/bc41mwxg9ybb69pn9j5zna6d36c/board.jsonl
  server/assets/templates-boardarchive/bui5izho7dtn77xg3thkiqprc9r/board.jsonl
  server/model/blockid.go
Labels: 2: Dev Review, CherryPick/Approved

#3480 Remove contents of CODEOWNERS file
  .github/CODEOWNERS
Labels: 2: Dev Review

#3482 Move pull request template file to repo root
  pull_request_template.md
Labels: 2: Dev Review

#3481 Automated cherry pick of #3335
  server/assets/templates-boardarchive/b7wnw9awd4pnefryhq51apbzb4c/board.jsonl
  server/assets/templates-boardarchive/bbn1888mprfrm5fjw9f1je9x3xo/board.jsonl
  server/assets/templates-boardarchive/bc41mwxg9ybb69pn9j5zna6d36c/board.jsonl
  server/assets/templates-boardarchive/bui5izho7dtn77xg3thkiqprc9r/board.jsonl
  server/model/blockid.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3278 Translations update from Mattermost Weblate
  webapp/i18n/ar.json
  webapp/i18n/ca.json
  webapp/i18n/de.json
  webapp/i18n/el.json
  webapp/i18n/en_AU.json
  webapp/i18n/es.json
  webapp/i18n/et.json
  webapp/i18n/fa.json
  webapp/i18n/fr.json
  webapp/i18n/hr.json
  webapp/i18n/hu.json
  webapp/i18n/id.json
  webapp/i18n/it.json
  webapp/i18n/ja.json
  webapp/i18n/kk.json
  webapp/i18n/ko.json
  webapp/i18n/ml.json
  webapp/i18n/nl.json
  webapp/i18n/oc.json
  webapp/i18n/pl.json
  webapp/i18n/pt_BR.json
  webapp/i18n/ru.json
  webapp/i18n/sk.json
  webapp/i18n/sv.json
  webapp/i18n/tr.json
  webapp/i18n/uk.json
  webapp/i18n/vi.json
  webapp/i18n/zh_Hans.json
  webapp/i18n/zh_Hant.json
Labels: Lifecycle/1:stale

#3487 Update pull_request_template.md
  pull_request_template.md
Labels: 3: Reviews Complete

#3379 Fetching board member in parellel
  server/api/api.go
  server/app/auth.go
  server/services/permissions/mmpermissions/mocks/mockpluginapi.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/ws/mocks/mockpluginapi.go
  webapp/cypress/integration/cardURLProperty.ts
  webapp/src/octoClient.ts
  webapp/src/store/boards.ts
Labels: 2: Dev Review, CherryPick/Approved

#3485 Update websocket client to use the new websocket lifecycle hooks
  webapp/src/wsclient.ts
Labels: 2: Dev Review, CherryPick/Approved

#3476 Automated cherry pick of #3473
  webapp/src/pages/boardPage/boardPage.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3488 Automated cherry pick of #3379
  server/api/api.go
  server/app/auth.go
  server/services/permissions/mmpermissions/mocks/mockpluginapi.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/ws/mocks/mockpluginapi.go
  webapp/cypress/integration/cardURLProperty.ts
  webapp/src/octoClient.ts
  webapp/src/store/boards.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3489 Automated cherry pick of #3485
  webapp/src/wsclient.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3490 Update query to use alias
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#3491 Automated cherry pick of #3490
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3444 New button using default template in kanban view.
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
  webapp/src/components/cardDialog.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/kanban/kanban.test.tsx
  webapp/src/components/kanban/kanban.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/mutator.ts
Labels: 3: Reviews Complete, CherryPick/Approved
