Repository mattermost-community/focalboard, pull requests merged in 2022-01, with the labels that each got.

#2030 Update README.md
  README.md
Labels: Contributor

#2040 fix crash in DeleteBlock
  server/api/api.go
  server/app/blocks.go
  server/integrationtests/subscriptions_test.go
Labels: 2: QA Review, CherryPick/Candidate

#2043 make testing all databases the default
  Makefile
Labels: 2: Dev Review

#2037 Improved diff to markdown for card notifications
  server/go.mod
  server/go.sum
  server/services/notify/notifysubscriptions/diff2markdown.go
  server/services/notify/notifysubscriptions/diff2markdown_test.go
  server/services/notify/notifysubscriptions/diff2slackattachments.go
  server/services/notify/notifysubscriptions/notifier.go
Labels: 2: Dev Review

#2010 GH-2007 Use VisiblePropertyIds for view property order
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/gallery/gallery.tsx
  webapp/src/components/kanban/kanban.tsx
  webapp/src/components/table/tableHeaderMenu.tsx
  webapp/src/components/table/tableHeaders.tsx
  webapp/src/components/table/tableRow.tsx
  webapp/src/mutator.ts
Labels: 1: PM Review, 1: UX Review, 2: Dev Review

#2008 GH-1916 - Set to first date field when loading
  webapp/src/components/workspace.tsx
Labels: 2: Dev Review

#2021 Add unit tests for cardFilter
  webapp/src/blocks/filterGroup.ts
  webapp/src/cardFilter.test.ts
Labels: 2: Dev Review, Contributor

#2054 Fixed a bug where block IDs weren't being updated in `contentOrder`
  server/api/api.go
  server/model/block.go
  server/model/block_test.go
Labels: 2: Dev Review, 2: QA Review, CherryPick/Candidate

#2057 Update version to 0.14.0
  mac/Focalboard/Globals.swift
  mac/Focalboard/Info.plist
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
  webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
  win-wpf/AppxManifest.xml
Labels: 3: Reviews Complete

#2055 List all authors of a card diff in the notification
  server/model/notification.go
  server/services/notify/notifysubscriptions/diff.go
  server/services/notify/notifysubscriptions/diff2slackattachments.go
  server/services/notify/notifysubscriptions/notifier.go
  server/services/notify/notifysubscriptions/util.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/migrations/bindata.go
Labels: 2: Dev Review, CherryPick/Approved

#2061 Automated cherry pick of #2055
  server/model/notification.go
  server/services/notify/notifysubscriptions/diff.go
  server/services/notify/notifysubscriptions/diff2slackattachments.go
  server/services/notify/notifysubscriptions/notifier.go
  server/services/notify/notifysubscriptions/util.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/migrations/bindata.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#1913 Added better kanban edge scroll detection whilst dragging
  webapp/.eslintrc.json
  webapp/cypress/global.d.ts
  webapp/cypress/integration/createBoard.ts
  webapp/cypress/integration/manageGroups.ts
  webapp/cypress/support/api_commands.ts
  webapp/cypress/support/index.ts
  webapp/cypress/support/ui_commands.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/kanban/__snapshots__/kanban.test.tsx.snap
  webapp/src/components/kanban/kanban.tsx
Labels: 3: Reviews Complete, Contributor

#2058 Fixed bug of stale closure in markdown editor
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2076 fix comments being set backwards
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: CherryPick/Approved

#2078 Gh 2077 mac app update
  webapp/src/wsclient.ts
Labels: CherryPick/Approved, CherryPick/Candidate

#2072 Stayin' Alive: Log & recover from web server panics
  server/api/api.go
Labels: CherryPick/Approved

#2083 Automated cherry pick of #2072
  server/api/api.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2085 updated fix for comments display backwards
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: CherryPick/Approved

#2086 Automated cherry pick of #2085
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2087 GH-1960 - Fixing link color on card (Personal Server)
  webapp/src/components/markdownEditor.scss
Labels: CherryPick/Approved

#2090 Automated cherry pick of #2087
  webapp/src/components/markdownEditor.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2088 GH-1948 - Updating overflow on input fields
  webapp/src/components/cardDetail/cardDetail.scss
Labels: 2: QA Review, CherryPick/Approved

#2091 Automated cherry pick of #2088
  webapp/src/components/cardDetail/cardDetail.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2071 Fixing unique ID problems on content order with multiple colums
  server/model/block.go
  server/model/block_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#2093 Automated cherry pick of #2071
  server/model/block.go
  server/model/block_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2096 Fix card link in notifications
  server/services/notify/notifysubscriptions/diff2slackattachments.go
  server/services/notify/notifysubscriptions/notifier.go
Labels: 2: Dev Review, CherryPick/Approved

#2098 Automated cherry pick of #2096
  server/services/notify/notifysubscriptions/diff2slackattachments.go
  server/services/notify/notifysubscriptions/notifier.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2099 Fixed a bug where mentions don't show up in descripotions
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: 2: Dev Review, CherryPick/Candidate

#2108 Automated cherry pick of #2103
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/cardDetail/cardDetailProperties.tsx
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/propertyValueElement.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2110 Fix prop change formatting for date & multiselect
  server/model/properties.go
Labels: 2: Dev Review, CherryPick/Approved

#2112 Automated cherry pick of #2110
  server/model/properties.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2025 [GH-1754] Feature: card badges
  webapp/cypress.json
  webapp/cypress/global.d.ts
  webapp/cypress/integration/cardBadges.ts
  webapp/cypress/support/api_commands.ts
  webapp/src/components/__snapshots__/cardBadges.test.tsx.snap
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/cardBadges.scss
  webapp/src/components/cardBadges.test.tsx
  webapp/src/components/cardBadges.tsx
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/gallery.test.tsx
  webapp/src/components/gallery/gallery.tsx
  webapp/src/components/gallery/galleryCard.scss
  webapp/src/components/gallery/galleryCard.test.tsx
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/kanban/kanban.tsx
  webapp/src/components/kanban/kanbanCard.test.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeader.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeaderActionsMenu.test.tsx
  webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
  webapp/src/components/viewHeader/viewHeaderPropertiesMenu.test.tsx
  webapp/src/components/viewHeader/viewHeaderPropertiesMenu.tsx
  webapp/src/constants.ts
  webapp/src/test/testBlockFactory.ts
  webapp/src/testUtils.tsx
  webapp/src/utils.test.ts
  webapp/src/utils.ts
  webapp/src/widgets/icons/check.scss
  webapp/src/widgets/icons/message.tsx
  webapp/src/widgets/icons/text.scss
  webapp/src/widgets/menu/switchOption.tsx
  webapp/src/widgets/menuWrapper.tsx
Labels: 1: PM Review, 1: UX Review, Contributor

#2122 Fix default schema type for focalboard blocks history
  server/services/store/sqlstore/initializations/bindata.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/migrations/migrations_files/000015_blocks_history_no_nulls.up.sql
Labels: 2: Dev Review, CherryPick/Approved

#2124 Automated cherry pick of #2122
  server/services/store/sqlstore/initializations/bindata.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/migrations/migrations_files/000015_blocks_history_no_nulls.up.sql
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2051 remove BoardsUnfurl feature flag
  mattermost-plugin/server/plugin.go
  mattermost-plugin/webapp/src/index.tsx
Labels: 2: Dev Review

#2109 Moving the history instance creation after the plugin initialization (to honor the SiteURL config)
  mattermost-plugin/webapp/webpack.config.js
  webapp/src/app.tsx
  webapp/src/components/__snapshots__/shareBoardComponent.test.tsx.snap
  webapp/src/components/shareBoardComponent.test.tsx
  webapp/src/components/shareBoardComponent.tsx
  webapp/src/pages/welcome/__snapshots__/welcomePage.test.tsx.snap
  webapp/src/pages/welcome/welcomePage.test.tsx
  webapp/src/pages/welcome/welcomePage.tsx
  webapp/src/utils.ts
Labels: 3: Reviews Complete, CherryPick/Candidate

#2116 Resolve usernames for `person` property type
  server/model/properties.go
  server/services/notify/notifysubscriptions/diff.go
Labels: 3: Reviews Complete

#2137 Fix #2136. Show release month+year for version.
  webapp/src/components/__snapshots__/topBar.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/sidebarUserMenu.tsx
  webapp/src/components/topBar.tsx
  webapp/src/constants.ts
  webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
Labels: 2: Dev Review

#2144 Fix board page interactions
  server/model/board.go
  server/services/store/storetests/boards.go
  webapp/src/blocks/board.ts
  webapp/src/components/addContentMenuItem.tsx
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/cardDetail/cardDetailContents.tsx
  webapp/src/components/cardDetail/cardDetailContext.tsx
  webapp/src/components/cardDetail/commentsList.test.tsx
  webapp/src/components/cardDetail/commentsList.tsx
  webapp/src/components/cardDetail/imagePaste.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/content/textElement.tsx
  webapp/src/components/sidebar/sidebarAddBoardMenu.tsx
  webapp/src/components/table/tableRow.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/components/viewTitle.test.tsx
  webapp/src/components/viewTitle.tsx
  webapp/src/mutator.ts
  webapp/src/octoClient.test.ts
  webapp/src/octoClient.ts
  webapp/src/pages/boardPage.tsx
  webapp/src/store/views.ts
  webapp/src/wsclient.ts
Labels: 3: Reviews Complete

#2132 GH-2130: Remove subscriptions feature flag
  mattermost-plugin/server/plugin.go
  server/services/config/config.go
  webapp/src/components/cardDialog.tsx
Labels: 2: Dev Review, CherryPick/Approved

#2135 Update to v0.12.1
  mac/Focalboard/Info.plist
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
  webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
  win-wpf/AppxManifest.xml
Labels: 3: Reviews Complete

#2145 Automated cherry pick of #2132
  mattermost-plugin/server/plugin.go
  server/services/config/config.go
  webapp/src/components/cardDialog.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2105 Fixed a typo
  website/site/config.toml
Labels: Contributor

#2104 Fix app tests
  server/app/blocks.go
  server/app/blocks_test.go
  server/app/helper_test.go
  server/app/sharing_test.go
  server/app/teams.go
  server/app/teams_test.go
  server/app/workspaces_test.go
Labels: 3: Reviews Complete

#2133 Persistent user config
  mattermost-plugin/server/plugin.go
  server/api/api.go
  server/app/user.go
  server/model/user.go
  server/server/server.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/services/store/storetests/users.go
  server/swagger/swagger.yml
  webapp/i18n/en.json
  webapp/src/app.tsx
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
  webapp/src/pages/welcome/__snapshots__/welcomePage.test.tsx.snap
  webapp/src/pages/welcome/welcomePage.scss
  webapp/src/pages/welcome/welcomePage.test.tsx
  webapp/src/pages/welcome/welcomePage.tsx
  webapp/src/store/users.ts
  webapp/src/user.tsx
  webapp/src/userSettings.ts
Labels: 2: Dev Review

#2152 Remove link to deleted css file
  webapp/html-templates/page.ejs
Labels: 3: Reviews Complete, Contributor

#2162 Fix mac m1 chip build, get architecture during make mac-app. Fixes #2160
  Makefile
Labels: 2: Dev Review, Contributor

#2161 Disable `max-lines` ESLint rule
  webapp/.eslintrc.json
Labels: 2: Dev Review

#2166 Don't log error msg when multiple nodes try processing a notification hint
  server/services/notify/notifysubscriptions/notifier.go
  server/services/store/sqlstore/notificationhints.go
Labels: 2: Dev Review

#2126 Adding gif support for boards
  server/api/api.go
  webapp/src/components/content/imageElement.tsx
Labels: 1: PM Review, 2: Dev Review

#2170 MM-40542: Verify config setting in api
  server/api/api.go
  server/integrationtests/sharing_test.go
Labels: 2: Dev Review

#2199 GH-1900 - change log from error to debug
  server/ws/plugin_adapter.go
Labels: 2: Dev Review

#1845 Milotype translations
  README.md
  website/site/layouts/partials/hero.html
Labels: 1: PM Review, Lifecycle/1:stale, Contributor

#2193 Add `chown` for nobody in the docker run example
  docker/README.md
Labels: 2: Dev Review, Contributor

#2181 [Growth Spike] Implement registry for channel intro button
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
  webapp/src/telemetry/telemetryClient.ts
Labels: 2: Dev Review

#2168 Update property template mutators to use boards API
  webapp/src/blocks/__snapshots__/board.test.ts.snap
  webapp/src/blocks/board.test.ts
  webapp/src/blocks/board.ts
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
Labels: 2: Dev Review

#2202 Add links to linode
  website/site/content/download/personal-edition/ubuntu.md
Labels: Contributor
