Repository mattermost-community/focalboard, pull requests merged in 2022-10, with the labels that each got.

#3892 Preserve old handleServeFile endpoint behavior after refactor
  server/api/files.go
Labels: 2: Dev Review

#3906 fix[GH-3764]: webpack extension
  webapp/webpack.common.js
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#3911 Update linux gomod
  linux/go.mod
  linux/go.sum
Labels: 2: Dev Review

#3888 Gh 3884 Fix Multiperson property
  webapp/src/properties/multiperson/multiperson.tsx
  webapp/src/properties/person/person.tsx
  webapp/src/utils.ts
Labels: 2: Dev Review, CherryPick/Approved

#3890 Update to version 7.5.0
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review

#3917 Update modal copy with "excludes guests" changes
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  webapp/i18n/en.json
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3908 RHS scroll: Fixed
  mattermost-plugin/webapp/src/components/rhsChannelBoards.scss
Labels: 2: Dev Review, CherryPick/Approved

#3786 Remove synthetic/implicit memberships for guests
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#3921 Automated cherry pick of #3908
  mattermost-plugin/webapp/src/components/rhsChannelBoards.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3922 Automated cherry pick of #3786
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3850 Escape button close the boardSelector dialog
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardSelector.test.tsx
  mattermost-plugin/webapp/src/components/boardSelector.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3905 [GH-1950] : Fix border-collapse user agent stylesheet
  webapp/src/styles/_markdown.scss
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#3928 Automated cherry pick of #3850
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardSelector.test.tsx
  mattermost-plugin/webapp/src/components/boardSelector.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3920 GH-3916 fix property change
  webapp/src/components/cardDetail/cardDetailProperties.test.tsx
  webapp/src/components/cardDetail/cardDetailProperties.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3927 fix: Person autocomplete in table
  webapp/src/components/table/table.scss
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#3930 Automated cherry pick of #3920
  webapp/src/components/cardDetail/cardDetailProperties.test.tsx
  webapp/src/components/cardDetail/cardDetailProperties.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3925 Pins the roles submenu to the user permission row
  webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/widgets/menu/menu.tsx
  webapp/src/widgets/menu/menuUtil.ts
Labels: 2: Dev Review, CherryPick/Approved

#3900 fix javascript error when curren group is delete
  webapp/src/components/kanban/kanban.tsx
  webapp/src/components/kanban/kanbanColumnHeader.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#3926 Fix misaligned 'viewer' role on share board/template dialog
  webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/userPermissionsRow.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#3913 Adding confirmation modal when setting the board to public with Editor or Commenter role
  webapp/i18n/en.json
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3907 Fix bug where workspace era uploaded files won't load on team era codebase
  server/api/files.go
  server/app/files.go
Labels: 2: Dev Review, CherryPick/Approved

#3935 Automated cherry pick of #3913
  webapp/i18n/en.json
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3931 fix[GH-3918]: add color on person class
  webapp/src/properties/person/person.scss
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#3949 Fix useHasPermission minimumRole cascade check
  webapp/src/hooks/permissions.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3954 fix adding members to public board by editor
  server/api/members.go
  server/integrationtests/board_test.go
  server/integrationtests/permissions_test.go
Labels: 2: Dev Review, CherryPick/Approved

#3923 Fix position of flash message popup see #3898
  webapp/src/components/flashMessages.scss
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#3962 MM-47403: Add hooks to the product
  mattermost-plugin/product/boards_product.go
  mattermost-plugin/server/manifest.go
Labels: 3: Reviews Complete

#3961 add setting admin role when add member
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/properties/multiperson/multiperson.tsx
  webapp/src/properties/person/person.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3963 Added handling of duplicate key conflicts
  server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
Labels: 2: Dev Review, CherryPick/Approved

#3967 Automated cherry pick of #3963
  server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3966 Automated cherry pick of #3961
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/properties/multiperson/multiperson.tsx
  webapp/src/properties/person/person.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3952 fixed typo in modal
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/confirmAddUserForNotifications.test.tsx.snap
  webapp/src/components/confirmAddUserForNotifications.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#3973 Automated cherry pick of #3972
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/properties/multiperson/multiperson.tsx
  webapp/src/properties/person/person.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3759 Added the markdown in channel boardSelector RHS for description
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoardItem.test.tsx.snap
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.test.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
Labels: 2: Dev Review

#3985 fix migration syntax
  server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
Labels: CherryPick/Approved

#3986 Automated cherry pick of #3985
  server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3989 Automated cherry pick of #3988
  server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3998 GH-3992 fix for missing templates, error when 'system' not found as user.
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#3999 Automated cherry pick of #3998
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3977 Add `export board archive` in the side bar context menu
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/sidebarBoardItem.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#4010 Gh 3974 guest autocomplete
  webapp/src/properties/multiperson/multiperson.tsx
  webapp/src/properties/person/person.tsx
Labels: 2: Dev Review

#4015 MM-46275 Rename product container to 'boards' for consistency
  mattermost-plugin/webapp/webpack.config.js
Labels: 3: Reviews Complete

#4016 MM-46725 Add build-product target to compile the Boards product
  Makefile
  mattermost-plugin/Makefile
  mattermost-plugin/webapp/package.json
  mattermost-plugin/webapp/webpack.config.js
Labels: 3: Reviews Complete

#3996 [GH-3947]: Added confirmation dialog when deleting a card in calendar/galley view
  webapp/i18n/en.json
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/gallery/galleryCard.test.tsx
  webapp/src/components/gallery/galleryCard.tsx
Labels: 2: Dev Review, Contributor, Hacktoberfest, hacktoberfest-accepted

#4002 Fix collation and charset after migrations (every run)
  mattermost-plugin/server/manifest.go
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/data_migrations_test.go
  server/services/store/sqlstore/helpers_test.go
  server/services/store/sqlstore/migrate.go
Labels: 3: Reviews Complete

#4011 Gh 3953 remove channel link duplicate
  server/services/store/sqlstore/boards_and_blocks.go
  server/services/store/storetests/boards_and_blocks.go
Labels: 2: Dev Review

#4033 Set correct plugin id when in product mode
  mattermost-plugin/webapp/src/index.tsx
Labels: 2: Dev Review

#4029 make sure users.props contains a hash!
  server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
Labels: CherryPick/Candidate, Contributor, Hacktoberfest, hacktoberfest-accepted

#4035 Don't replace newlines with symbol when adding comment or text.
  server/services/notify/notifysubscriptions/diff2slackattachments.go
Labels: 2: Dev Review

#4027 Gh 3942 - fix bug with Boards bot, update link text
  server/app/boards.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mattermostauthlayer/mattermostauthlayer_test.go
Labels: 2: Dev Review

#4039 Stopped reacting to initial text changes and not being a controlled component
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: 2: Dev Review, CherryPick/Approved

#4041 Automated cherry pick of #4039
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4043 Update URL to docs page for migrating and reference `.boardarchive`
  import/asana/README.md
  import/asana/importAsana.ts
  import/jira/README.md
  import/jira/importJira.ts
  import/jira/jiraImporter.ts
  import/nextcloud-deck/README.md
  import/nextcloud-deck/importDeck.ts
  import/notion/README.md
  import/notion/importNotion.ts
  import/todoist/README.md
  import/todoist/importTodoist.ts
  import/trello/README.md
  import/trello/importTrello.ts
  webapp/src/constants.ts
Labels: 2: Dev Review

#4045 MM-47562 Serve images from the correct URL in product mode
  mattermost-plugin/webapp/webpack.config.js
Labels: 3: Reviews Complete

#4048 GH-4047 Handle all potential displayValue types
  webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
  webapp/src/properties/types.tsx
Labels: 2: Dev Review, CherryPick/Candidate

#4042 GH-4007 Fix for welcome screen flashing
  webapp/src/store/users.ts
Labels: 3: Reviews Complete, CherryPick/Candidate

#4006 Personal Server - remove same function on disconnect as added on reconnect.
  webapp/src/pages/boardPage/boardPage.tsx
Labels: 3: Reviews Complete, CherryPick/Candidate

#4051 Automated cherry pick of #4048
  webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
  webapp/src/properties/types.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4052 Automated cherry pick of #4042
  webapp/src/store/users.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3929 Add mariadb tests and update database migration for compatibility
  .github/workflows/ci.yml
  Makefile
  docker-testing/docker-compose-mariadb.yml
  server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql
  server/services/store/sqlstore/migrationstests/fixtures/test18AddTeamsAndBoardsSQLMigrationFixtures.sql
  server/services/store/sqlstore/migrationstests/migration_18_test.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/util.go
Labels: 2: Dev Review, CherryPick/Candidate

#4056 Automated cherry pick of #3929
  .github/workflows/ci.yml
  Makefile
  docker-testing/docker-compose-mariadb.yml
  server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql
  server/services/store/sqlstore/migrationstests/fixtures/test18AddTeamsAndBoardsSQLMigrationFixtures.sql
  server/services/store/sqlstore/migrationstests/migration_18_test.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/util.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4060 Fix GetMemberForBoard from returning a null member
  server/services/permissions/mmpermissions/mmpermissions.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#4061 Automated cherry pick of #4060
  server/services/permissions/mmpermissions/mmpermissions.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4049 MM-47562/MM-47631 Just rely on Webpack for image paths in product mode
  mattermost-plugin/webapp/webpack.config.js
Labels: 2: Dev Review

#4055 MM-46392 - load boards memberships on rhs component mount
  mattermost-plugin/webapp/src/components/rhsChannelBoards.test.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
  webapp/src/store/boards.ts
  webapp/src/store/initialLoad.ts
Labels: 3: Reviews Complete

#4058 [GH-3939] - Updated Margin for GuestBadge
  webapp/src/widgets/guestBadge.scss
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#4050 Fix Bug #533 - Filter menu does not disappear when clicked for a second time (Board > Filter)
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/widgets/buttons/button.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#4076 MM-47873 Replace react-router import with react-router-dom
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 2: Dev Review

#4080 Fix collation for personal server
  server/services/store/sqlstore/data_migrations.go
Labels: 2: Dev Review

#4025 Display board statistics
  mattermost-plugin/product/api_adapter.go
  mattermost-plugin/server/api_adapter.go
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
  server/api/api.go
  server/api/statistics.go
  server/app/cloud.go
  server/client/client.go
  server/integrationtests/clienttestlib.go
  server/integrationtests/permissions_test.go
  server/integrationtests/statistics_test.go
  server/model/board_statistics.go
  server/model/mocks/mockservicesapi.go
  server/model/services_api.go
  server/services/permissions/localpermissions/localpermissions.go
  server/services/permissions/mmpermissions/mmpermissions.go
  server/services/permissions/permissions.go
  server/services/store/sqlstore/blocks.go
  webapp/i18n/en.json
  webapp/src/octoClient.ts
  webapp/src/statistics/index.ts
Labels: 2: Dev Review

#4026 MM-47238 Add MM_BOARDS_DEV_SERVER_URL environment variable for MPA
  mattermost-plugin/webapp/webpack.config.js
Labels: 3: Reviews Complete

#4063 GH 3830 - fix person/multi-person overflow
  webapp/src/properties/multiperson/multiperson.scss
  webapp/src/properties/person/person.scss
Labels: 2: Dev Review

#4089 Disable patches on unmount on readOnly mode
  webapp/src/properties/baseTextEditor.tsx
Labels: 2: Dev Review, CherryPick/Approved

#4069 [GH-1007] Fix popup menus visibility
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoardItem.test.tsx.snap
  webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/calendar/__snapshots__/fullCalendar.test.tsx.snap
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/components/cardActionsMenu/cardActionsMenuIcon.scss
  webapp/src/components/cardActionsMenu/cardActionsMenuIcon.tsx
  webapp/src/components/cardDetail/__snapshots__/cardDetailContentsMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/comment.test.tsx.snap
  webapp/src/components/contentBlock.scss
  webapp/src/components/contentBlock.tsx
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/gallery/galleryCard.scss
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
  webapp/src/components/kanban/kanbanCard.scss
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/components/shareBoard/__snapshots__/channelPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/teamPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/emptyCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterComponent.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButtonTemplateItem.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderGroupByMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderSortMenu.test.tsx.snap
  webapp/src/widgets/menuWrapper.scss
  webapp/src/widgets/menuWrapper.tsx
Labels: 1: PM Review, 2: Dev Review, Contributor, Hacktoberfest, hacktoberfest-accepted

#4091 fix code for portuguese to match codes in i18n.tsx
  webapp/src/constants.ts
Labels: 2: Dev Review

#4090 Automated cherry pick of #4089
  webapp/src/properties/baseTextEditor.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
