Repository mattermost-community/focalboard, pull requests merged in 2022-11, with the labels that each got.

#4022 Remove margin on hover if table readonly
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
  webapp/src/components/table/tableRow.scss
  webapp/src/components/table/tableRow.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#4114 [GH-4086] Doc: Personal server setup guide out of date
  .gitignore
  README.md
Labels: 2: Dev Review, 2. Editor Review, Contributor

#4098 fix: convert `multiSelect` prop value to [] if required
  webapp/src/store/cards.ts
Labels: 2: Dev Review, CherryPick/Approved

#4118 Automated cherry pick of #4098
  webapp/src/store/cards.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4117 fix: don't send multiple `viewBoard` telemetries
  webapp/src/components/centerPanel.tsx
Labels: 2: Dev Review

#4115 Minor UI Changes
  mattermost-plugin/webapp/src/components/rhsChannelBoards.scss
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/cardBadges.scss
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableGroupHeaderRow.test.tsx.snap
  webapp/src/components/table/table.scss
  webapp/src/components/table/tableGroupHeaderRow.tsx
  webapp/src/widgets/icons/text.scss
  webapp/src/widgets/menu/menu.scss
Labels: 2: Dev Review

#4110 Fix to respect System Console settings
  mattermost-plugin/server/boards/boardsapp_test.go
  mattermost-plugin/server/boards/boardsapp_util.go
  mattermost-plugin/server/boards/configuration.go
  mattermost-plugin/server/boards/configuration_test.go
  server/app/auth.go
  server/app/boards_test.go
  server/app/onboarding_test.go
  server/app/user.go
  server/integrationtests/pluginteststore.go
  server/services/config/config.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/services/store/storetests/users.go
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#4124 Automated cherry pick of #4110
  mattermost-plugin/server/boards/boardsapp_test.go
  mattermost-plugin/server/boards/boardsapp_util.go
  mattermost-plugin/server/boards/configuration.go
  mattermost-plugin/server/boards/configuration_test.go
  server/app/auth.go
  server/app/boards_test.go
  server/app/onboarding_test.go
  server/app/user.go
  server/integrationtests/pluginteststore.go
  server/services/config/config.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/services/store/storetests/users.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4023 Fix misaligned Product tour for share button (Closes: #3946)
  webapp/src/components/onboardingTour/shareBoard/shareBoard.scss
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#4145 Fix issues when retrieving boards
  mattermost-plugin/server/manifest.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#4152 Updated the filter condition for notContains
  webapp/src/cardFilter.test.ts
  webapp/src/cardFilter.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#4155 Automated cherry pick of #4145
  mattermost-plugin/server/manifest.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4116 MM-47793 Change product dev server to not use deprecated options
  mattermost-plugin/webapp/webpack.config.js
Labels: 3: Reviews Complete

#4158 Implicit memberships in SearchBoardForUserInTeam
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#4159 Automated cherry pick of #4158
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4153 Case-insensitive filter for text
  webapp/src/cardFilter.test.ts
  webapp/src/cardFilter.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#4164 Automated cherry pick of #4153
  webapp/src/cardFilter.test.ts
  webapp/src/cardFilter.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4163 Added logic for system board category to show last
  webapp/src/store/sidebar.ts
Labels: 2: Dev Review, CherryPick/Approved

#4133 Fix a bug where board didn;t show up in LHS when someone added me on it
  server/app/boards.go
  server/app/boards_test.go
Labels: CherryPick/Approved

#4166 Automated cherry pick of #4163
  webapp/src/store/sidebar.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4167 Automated cherry pick of #4133
  server/app/boards.go
  server/app/boards_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4161 Fix for category not being set by UI, set to existing Category.
  server/app/category.go
Labels: 2: Dev Review, CherryPick/Approved

#3943 Delete children when deleting boards and cards
  server/go.mod
  server/go.sum
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/boards_and_blocks.go
  server/services/store/sqlstore/legacy_blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/util.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/util.go
  server/utils/callbackqueue.go
Labels: 3: Reviews Complete

#4169 Automated cherry pick of #4161
  server/app/category.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4172 Fix themes on differen teams
  mattermost-plugin/webapp/src/index.tsx
Labels: 2: Dev Review, CherryPick/Approved

#4171 Automated cherry pick of #3943
  server/go.mod
  server/go.sum
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/boards_and_blocks.go
  server/services/store/sqlstore/legacy_blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/util.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/util.go
  server/utils/callbackqueue.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4174 Don't add templates to default category
  server/app/boards.go
Labels: 2: Dev Review, CherryPick/Approved

#4175 Automated cherry pick of #4172
  mattermost-plugin/webapp/src/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4176 Automated cherry pick of #4174
  server/app/boards.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4177 Update template version
  server/app/templates.go
Labels: 2: Dev Review, CherryPick/Approved

#4178 Automated cherry pick of #4177
  server/app/templates.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4183 Automated cherry pick of #4182
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4185 Update to version 7.6.0
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review

#4194 GH-4193 - Updating table view structure for drag
  webapp/src/components/table/table.scss
  webapp/src/components/table/tableRow.scss
Labels: 3: Reviews Complete, Do Not Merge

#4186 Set down migrations as noops and add CI job
  .github/workflows/lint-server.yml
  server/services/store/sqlstore/migrations/000001_init.down.sql
  server/services/store/sqlstore/migrations/000002_system_settings_table.down.sql
  server/services/store/sqlstore/migrations/000003_blocks_rootid.down.sql
  server/services/store/sqlstore/migrations/000004_auth_table.down.sql
  server/services/store/sqlstore/migrations/000005_blocks_modifiedby.down.sql
  server/services/store/sqlstore/migrations/000006_sharing_table.down.sql
  server/services/store/sqlstore/migrations/000007_workspaces_table.down.sql
  server/services/store/sqlstore/migrations/000008_teams.down.sql
  server/services/store/sqlstore/migrations/000009_blocks_history.down.sql
  server/services/store/sqlstore/migrations/000010_blocks_created_by.down.sql
  server/services/store/sqlstore/migrations/000011_match_collation.down.sql
  server/services/store/sqlstore/migrations/000012_match_column_collation.down.sql
  server/services/store/sqlstore/migrations/000013_millisecond_timestamps.down.sql
  server/services/store/sqlstore/migrations/000014_add_not_null_constraint.down.sql
  server/services/store/sqlstore/migrations/000015_blocks_history_no_nulls.down.sql
  server/services/store/sqlstore/migrations/000016_subscriptions_table.down.sql
  server/services/store/sqlstore/migrations/000017_add_file_info.down.sql
  server/services/store/sqlstore/migrations/000019_populate_categories.down.sql
  server/services/store/sqlstore/migrations/000020_populate_category_blocks.down.sql
  server/services/store/sqlstore/migrations/000021_create_boards_members_history.down.sql
  server/services/store/sqlstore/migrations/000022_create_default_board_role.down.sql
  server/services/store/sqlstore/migrations/000023_persist_category_collapsed_state.down.sql
  server/services/store/sqlstore/migrations/000024_mark_existsing_categories_collapsed.down.sql
  server/services/store/sqlstore/migrations/000025_indexes_update.down.sql
  server/services/store/sqlstore/migrations/000026_create_preferences_table.down.sql
  server/services/store/sqlstore/migrations/000029_add_category_type_field.down.sql
Labels: 3: Reviews Complete

#4148 GH-3541 docker data permissions & cleanup
  docker/Dockerfile
  docker/README.md
  docker/config.json
  docker/docker-compose-db-nginx.yml
  docker/docker-compose.yml
  docker/server_config.json
Labels: 2: Dev Review

#4151 [GH-3410] Healthcheck Endpoint with Server Metadata
  server/api/cards.go
  server/api/system.go
  server/api/system_test.go
  server/api/users.go
  server/app/server_metadata.go
  server/app/server_metadata_test.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/store.go
  server/swagger/docs/html/.openapi-generator/VERSION
  server/swagger/docs/html/index.html
  server/swagger/swagger.yml
Labels: Contributor

#4200 Set board category if not set
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/sidebar.test.tsx
  webapp/src/components/sidebar/sidebar.tsx
Labels: 3: Reviews Complete

#4213 Require build tag to include sqlite
  Makefile
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/data_retention.go
  server/services/store/sqlstore/sqlite.go
Labels: 2: Dev Review

#4215 Automated cherry pick of #4213
  Makefile
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/data_retention.go
  server/services/store/sqlstore/sqlite.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4216 Automated cherry pick of #4213
  Makefile
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/data_retention.go
  server/services/store/sqlstore/sqlite.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4217 Update version to 7.5.1
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 3: Reviews Complete

#4220 Automated cherry pick of #4218
  linux/Makefile
  linux/go.mod
  linux/go.sum
  modd-servertest.conf
  modd.conf
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4208 migrations: update morph dependecy and apply changes
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  server/go.mod
  server/go.sum
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrationstests/boards_migrator_test.go
Labels: 3: Reviews Complete

#3876 [MM-45052] Add error checking in insights API
  server/api/insights.go
Labels: 3: Reviews Complete

#4211 fix: `toString` `propertyValue` for lowercasing
  webapp/src/store/cards.ts
Labels: 2: Dev Review, CherryPick/Approved

#4232 Manually de-duplicate result set for SearchBoardsForUserInTeam
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#4233 Cherry-pick MM-48549 for cloud
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review

#4209 Updating board template picker ui
  webapp/i18n/en.json
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.scss
  webapp/src/components/kanban/kanbanCard.scss
  webapp/src/widgets/buttons/button.scss
Labels: 3: Reviews Complete

#4223 CSS fix for readonly user
  webapp/src/components/table/tableRow.scss
Labels: 1: UX Review, 2: Dev Review

#4053 File attachment in the card
  mattermost-plugin/server/boards/configuration.go
  server/api/files.go
  server/app/clientConfig.go
  server/client/client.go
  server/integrationtests/file_test.go
  server/model/clientConfig.go
  server/services/config/config.go
  webapp/i18n/en.json
  webapp/src/blocks/attachmentBlock.tsx
  webapp/src/blocks/block.ts
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/cardDetail/attachment.scss
  webapp/src/components/cardDetail/attachment.tsx
  webapp/src/components/cardDetail/cardDetail.test.tsx
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/cardDialog.scss
  webapp/src/components/cardDialog.tsx
  webapp/src/components/content/__snapshots__/attachmentElement.test.tsx.snap
  webapp/src/components/content/attachmentElement.scss
  webapp/src/components/content/attachmentElement.test.tsx
  webapp/src/components/content/attachmentElement.tsx
  webapp/src/config/clientConfig.ts
  webapp/src/file.ts
  webapp/src/fileIcons.ts
  webapp/src/octoClient.test.ts
  webapp/src/octoClient.ts
  webapp/src/octoUtils.tsx
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/store/attachments.ts
  webapp/src/store/clientConfig.ts
  webapp/src/store/index.ts
Labels: 3: Reviews Complete

#4247 Updates boards registration as product to use name instead of ID
  mattermost-plugin/product/api_adapter.go
  mattermost-plugin/webapp/src/index.tsx
Labels: 2: Dev Review

#4207 Optimised Sorting of comments inside cards
  webapp/src/store/comments.ts
Labels: 2: Dev Review

#4252 Automated cherry pick of #4247
  mattermost-plugin/product/api_adapter.go
  mattermost-plugin/webapp/src/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4246 Not opening template picker if there are no boards
  webapp/src/components/workspace.tsx
Labels: 3: Reviews Complete

#4244 Adding only boards with explicit access to default category
  server/app/boards_test.go
  server/app/category_boards.go
  server/app/category_boards_test.go
  server/app/category_test.go
  server/app/import_test.go
  server/app/onboarding_test.go
Labels: 2: Dev Review

#4147 Improvements for multi-select property
  webapp/src/properties/multiselect/multiselect.test.tsx
  webapp/src/widgets/valueSelector.scss
  webapp/src/widgets/valueSelector.tsx
Labels: 3: Reviews Complete, Contributor

#4071 [GH-4070] Fix focus on new table row
  webapp/src/components/centerPanel.tsx
Labels: Contributor, Hacktoberfest, hacktoberfest-accepted

#4258 Update production release workflow for MPA
  .github/workflows/prod-release.yml
Labels: 2: Dev Review

#4260 Remove extra run tag for plugin check
  .github/workflows/prod-release.yml
Labels: CherryPick/Approved

#4261 Automated cherry pick of #4260
  .github/workflows/prod-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4262 don't exclude server from build
  .github/workflows/prod-release.yml
Labels: CherryPick/Approved

#4263 Automated cherry pick of #4262
  .github/workflows/prod-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4265 Automated cherry pick of #4264
  .github/workflows/prod-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4266 Fix prod workflow
  .github/workflows/prod-release.yml
Labels: CherryPick/Approved

#4267 Automated cherry pick of #4266
  .github/workflows/prod-release.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4271 Bump matter-most server version
  linux/go.mod
  linux/go.sum
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  server/go.mod
  server/go.sum
Labels: 2: Dev Review
