Repository mattermost-community/focalboard, pull requests merged in 2022-03, with the labels that each got.

#2192 Doc: Update index.md
  website/site/content/guide/user/_index.md
Labels: 1: PM Review, Lifecycle/1:stale, Documentation, Contributor

#2425 Permissions branch: Fix unit tests and CI errors (part 1)
  Makefile
  server/api/api.go
  server/app/blocks.go
  server/app/blocks_test.go
  server/app/files_test.go
  server/integrationtests/blocks_test.go
  server/integrationtests/clienttestlib.go
  server/services/store/sqlstore/blocks.go
Labels: 3: Reviews Complete

#2400 Fixing some small memory leaks
  Makefile
  webapp/src/components/cardDetail/imagePaste.tsx
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
  webapp/src/pages/welcome/welcomePage.test.tsx
  webapp/src/widgets/menuWrapper.tsx
Labels: 3: Reviews Complete

#2429 Permissions branch: Fixes all the linter errors
  server/.golangci.yml
  server/api/api.go
  server/app/boards.go
  server/app/files_test.go
  server/app/onboarding.go
  server/app/onboarding_test.go
  server/app/templates.go
  server/client/client.go
  server/integrationtests/board_test.go
  server/integrationtests/boards_and_blocks_test.go
  server/integrationtests/clienttestlib.go
  server/model/boards_and_blocks.go
  server/model/boards_and_blocks_test.go
  server/model/category.go
  server/model/database.go
  server/model/permission.go
  server/services/auth/email.go
  server/services/permissions/mmpermissions/mmpermissions_test.go
  server/services/store/generators/transactional_store.go.tmpl
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/boards_and_blocks.go
  server/services/store/sqlstore/category.go
  server/services/store/sqlstore/category_boards.go
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/data_migrations_test.go
  server/services/store/sqlstore/legacy_blocks.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/notificationhints.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sharing.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/subscriptions.go
  server/services/store/sqlstore/system.go
  server/services/store/sqlstore/team.go
  server/services/store/sqlstore/util.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/boards.go
  server/services/store/storetests/boards_and_blocks.go
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_cluster.go
  server/ws/server.go
Labels: 2: Dev Review

#2367 [GH-1304] Add Toggle to hide empty groups for TableView
  webapp/i18n/en.json
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.test.tsx
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/viewHeader/__snapshots__/viewHeaderGroupByMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeader.test.tsx
  webapp/src/components/viewHeader/viewHeaderGroupByMenu.test.tsx
  webapp/src/components/viewHeader/viewHeaderGroupByMenu.tsx
  webapp/src/mutator.ts
Labels: 1: PM Review, 2: Dev Review, Contributor

#2428 Fixing template picker delete alignment
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
Labels: 3: Reviews Complete

#2280 GH-2243 - Centering dialog modals
  webapp/src/components/dialog.scss
Labels: 2: Dev Review

#2431 Fix for #2430. Bypass Welcome screen for Personal Desktop.
  webapp/src/app.tsx
  webapp/src/pages/welcome/welcomePage.tsx
  webapp/src/store/users.ts
Labels: 3: Reviews Complete

#2321 Error page
  mattermost-plugin/webapp/src/error_boundary.tsx
  webapp/.eslintrc.json
  webapp/cypress/integration/loginActions.ts
  webapp/cypress/plugins/index.js
  webapp/cypress/support/index.ts
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/app.tsx
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/errors.ts
  webapp/src/pages/errorPage.scss
  webapp/src/pages/errorPage.tsx
  webapp/src/store/initialLoad.ts
  webapp/src/svg/error-illustration.tsx
Labels: 2: Dev Review

#2416 don't allow last admin change/deleted
  webapp/i18n/en.json
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
Labels: 2: Dev Review

#2432 Update Share Button
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/centerPanel.tsx
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/shareBoardButton.test.tsx
  webapp/src/components/shareBoard/shareBoardButton.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/telemetry/telemetryClient.ts
Labels: 1: UX Review, 2: Dev Review

#2424 Replace go migrate with morph permissions
  mattermost-plugin/go.sum
  server/go.mod
  server/go.sum
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/util.go
Labels: 2: Dev Review

#2354 Shows "(Deleted User)" instead of UUID when user not found
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 3: Reviews Complete, CherryPick/Approved, Contributor

#2465 Automated cherry pick of #2354
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2472 Allow always team 0 (global) templates fetch
  server/api/api.go
Labels: 2: Dev Review

#2473 Fix problem with viewId 0 in the URL
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx
Labels: 2: Dev Review

#2444 Update CHANGELOG.md for v0.15
  CHANGELOG.md
Labels: CherryPick/Approved

#2453 Fixed a bug where images of the welcome board were not copied over.
  server/app/onboarding.go
  server/app/onboarding_test.go
Labels: 2: QA Review, CherryPick/Candidate

#2492 GH-2212 - Update global link on board
  webapp/src/components/topBar.scss
  webapp/src/styles/main.scss
Labels: CherryPick/Approved, AutomatedCherryPick

#2480 GH-2387 - Fixing link in comments
  webapp/src/components/cardDetail/comment.scss
Labels: 2: Dev Review, CherryPick/Approved, AutomatedCherryPick

#2495 Automated cherry pick of #2492
  webapp/src/components/topBar.scss
  webapp/src/styles/main.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2498 Automated cherry pick of #2480
  webapp/src/components/cardDetail/comment.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2501 Permissions branch: Fix webapp compile error, missing enableSharedBoards
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/viewHeader/viewHeader.test.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
Labels: 2: Dev Review

#2497 GH-2496 - Updating board title truncation issue
  webapp/src/components/centerPanel.scss
Labels: 2: QA Review, CherryPick/Approved, AutomatedCherryPick

#2503 Automated cherry pick of #2497
  webapp/src/components/centerPanel.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2466 GH-2258 - set min-height on empty date to allow click
  webapp/src/components/properties/dateRange/dateRange.scss
Labels: 2: Dev Review, CherryPick/Approved

#2504 Automated cherry pick of #2466
  webapp/src/components/properties/dateRange/dateRange.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2114 [MM-40214] Implement App Bar component
  mattermost-plugin/Makefile
  mattermost-plugin/public/app-bar-icon.png
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
Labels: 2: QA Review

#2474 Fix problem with viewId 0 in the URL
  webapp/src/pages/boardPage.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2510 Automated cherry pick of #2474
  webapp/src/pages/boardPage.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2478 GH-2456 - Updating url property
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/properties/link/link.scss
Labels: 2: Dev Review, 2: QA Review

#2499 GH-2257: Don't display template page if readonly and access revoked
  webapp/src/pages/boardPage.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2479 GH-2447 - Updating label overflow
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/styles/main.scss
  webapp/src/widgets/label.scss
  webapp/src/widgets/valueSelector.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, AutomatedCherryPick

#2515 Automated cherry pick of #2499
  webapp/src/pages/boardPage.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2511 Gh-2437 - Updating share board modal
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/cardDetail/commentsList.scss
  webapp/src/components/cardDialog.scss
  webapp/src/components/cardDialog.tsx
  webapp/src/components/dialog.scss
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2522 Automated cherry pick of #2511
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/cardDetail/commentsList.scss
  webapp/src/components/cardDialog.scss
  webapp/src/components/cardDialog.tsx
  webapp/src/components/dialog.scss
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2509 updated/synced prior PR
  webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailContentsMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/comment.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableHeaderMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/emptyCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterComponent.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButtonTemplateItem.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderGroupByMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderSortMenu.test.tsx.snap
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/menu/menu.scss
  webapp/src/widgets/menu/menu.tsx
  webapp/src/widgets/menu/subMenuOption.tsx
  webapp/src/widgets/menu/textInputOption.tsx
  webapp/src/widgets/propertyMenu.tsx
Labels: 2: Dev Review, CherryPick/Approved

#2523 Automated cherry pick of #2509
  webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailContentsMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/comment.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableHeaderMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/emptyCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterComponent.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButtonTemplateItem.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderGroupByMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderSortMenu.test.tsx.snap
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/menu/menu.scss
  webapp/src/widgets/menu/menu.tsx
  webapp/src/widgets/menu/subMenuOption.tsx
  webapp/src/widgets/menu/textInputOption.tsx
  webapp/src/widgets/propertyMenu.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2526 Minor updates to the contributor's guide
  docs/index.md
Labels: 1: PM Review, 2: Dev Review

#2525 Dismiss tour from overlay
  webapp/src/components/cardDialog.test.tsx
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/onboardingTour/addProperties/add_properties.tsx
  webapp/src/components/pulsating_dot/pulsating_dot.scss
Labels: 2: Dev Review, CherryPick/Approved

#2518 Error page improvements
  webapp/i18n/en.json
  webapp/src/errors.ts
  webapp/src/pages/errorPage.tsx
Labels: 2: Dev Review, CherryPick/Approved

#2532 Automated cherry pick of #2518
  webapp/i18n/en.json
  webapp/src/errors.ts
  webapp/src/pages/errorPage.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2531 Automated cherry pick of #2525
  webapp/src/components/cardDialog.test.tsx
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/onboardingTour/addProperties/add_properties.tsx
  webapp/src/components/pulsating_dot/pulsating_dot.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2477 [GH-2396] Fix scroll jump for kanban board
  webapp/src/components/calculations/__snapshots__/options.test.tsx.snap
  webapp/src/components/calculations/options.tsx
  webapp/src/components/kanban/__snapshots__/kanban.test.tsx.snap
  webapp/src/components/kanban/calculation/__snapshots__/calculation.test.tsx.snap
  webapp/src/components/kanban/calculation/__snapshots__/calculationOptions.test.tsx.snap
  webapp/src/components/kanban/kanban.tsx
Labels: Contributor

#2530 Permissions branch: No sqlstore calls after app shutdown
  server/app/app.go
  server/app/blocks.go
  server/app/boards_and_blocks.go
  server/app/helper_test.go
  server/app/initialize.go
  server/server/server.go
  server/services/store/sqlstore/blocks.go
  server/services/store/storetests/blocks.go
  server/utils/callbackqueue.go
  server/utils/callbackqueue_test.go
  server/ws/server.go
Labels: 2: Dev Review

#2550 Shareboard cleanup
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/workspace.tsx
Labels: 2: Dev Review

#2568 Permissions branch: Fix sqlite table lock (CI)
  mattermost-plugin/server/plugin.go
  server/integrationtests/clienttestlib.go
  server/services/store/sqlstore/helpers_test.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/util.go
Labels: 2: Dev Review

#2599 Sqlite in-memory database for unit tests
  config.json
  server/services/store/sqlstore/util.go
  webapp/cypress/config.json
  webapp/cypress/support/api_commands.ts
Labels: 2: Dev Review

#2630 Revert in-memory unit tests for sqlite
  server/services/permissions/localpermissions/localpermissions.go
  server/services/store/sqlstore/util.go
Labels: 2: Dev Review

#2577 Generate templates archive at build time
  .github/workflows/lint-server.yml
  .gitignore
  Makefile
  mattermost-plugin/Makefile
  server/app/helper_test.go
  server/app/import.go
  server/app/initialize.go
  server/app/templates.go
  server/app/templates_test.go
  server/assets/assets.go
  server/assets/build-template-archive/main.go
  server/assets/templates-boardarchive/b7wnw9awd4pnefryhq51apbzb4c/board.jsonl
  server/assets/templates-boardarchive/bbn1888mprfrm5fjw9f1je9x3xo/76fwrj36hptg6dywka4k5mt3sph.png
  server/assets/templates-boardarchive/bbn1888mprfrm5fjw9f1je9x3xo/board.jsonl
  server/assets/templates-boardarchive/bc41mwxg9ybb69pn9j5zna6d36c/board.jsonl
  server/assets/templates-boardarchive/bd65qbzuqupfztpg31dgwgwm5ga/board.jsonl
  server/assets/templates-boardarchive/brs9cdimfw7fodyi7erqt747rhc/7y5kr8x8ybpnwdykjfuz57rggrh.png
  server/assets/templates-boardarchive/brs9cdimfw7fodyi7erqt747rhc/board.jsonl
  server/assets/templates-boardarchive/bui5izho7dtn77xg3thkiqprc9r/77pe9r4ckbin438ph3f18bpatua.png
  server/assets/templates-boardarchive/bui5izho7dtn77xg3thkiqprc9r/7pbp4qg415pbstc6enzeicnu3qh.png
  server/assets/templates-boardarchive/bui5izho7dtn77xg3thkiqprc9r/board.jsonl
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/74nt9eqzea3ydjjpgjtsxcjgrxc.gif
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/74uia99m9btr8peydw7oexn37tw.gif
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/78jws5m1myf8pufewzkaa6i11sc.gif
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/7d6hrtig3zt8f9cnbo1um5oxx3y.gif
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/7dybb6t8fj3nrdft7nerhuf784y.png
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/7ek6wbpp19jfoujs1goh6kttbby.gif
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/7iw4rxx7jj7bypmdotd9z469cyh.png
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/7knxbyuiedtdafcgmropgkrtybr.gif
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/board.jsonl
  server/assets/templates-boardarchive/version.json
  server/model/block.go
  server/model/import_export.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 3: Reviews Complete

#2700 GH-2692 - Fix archive import
  server/api/api.go
  server/api/archive.go
  server/app/import.go
  server/app/import_test.go
  server/app/templates_test.go
Labels: 2: Dev Review
