Repository mattermost-community/focalboard, pull requests merged in 2022-04, with the labels that each got.

#2703 GH-2443 - Fix broken Follow button
  server/app/boards.go
  server/app/subscriptions.go
  server/services/notify/notifysubscriptions/subscriptions_backend.go
  server/services/notify/service.go
  webapp/src/octoClient.ts
  webapp/src/pages/boardPage/websocketConnection.tsx
  webapp/src/wsclient.ts
Labels: 2: Dev Review

#2704 GH-2638 - Fix Import scripts
  import/asana/importAsana.ts
  import/jira/jiraImporter.test.ts
  import/jira/jiraImporter.ts
  import/nextcloud-deck/importDeck.ts
  import/notion/importNotion.ts
  import/todoist/importTodoist.ts
  import/trello/importTrello.ts
  import/util/archive.ts
Labels: 2: Dev Review

#2706 GH-2534: Don't show error page for Personal Server when not logged in
  webapp/cypress/integration/loginActions.ts
  webapp/src/pages/errorPage.tsx
Labels: 2: Dev Review

#2719 Refactor errorResponse to set the logger to debug if the response cod…
  server/api/api.go
Labels: Contributor

#2664 Adding file size limit
  mattermost-plugin/server/plugin.go
  server/api/api.go
  server/app/app.go
  server/integrationtests/clienttestlib.go
  server/integrationtests/file_test.go
  server/services/config/config.go
  webapp/cypress/integration/cardBadges.ts
  webapp/cypress/integration/cardURLProperty.ts
  webapp/cypress/integration/createBoard.ts
  webapp/cypress/integration/groupByProperty.ts
  webapp/cypress/integration/loginActions.ts
  webapp/cypress/integration/manageGroups.ts
  webapp/cypress/support/api_commands.ts
  webapp/i18n/en.json
  webapp/package.json
  webapp/src/components/addContentMenuItem.tsx
  webapp/src/components/cardDetail/cardDetailContext.tsx
  webapp/src/components/cardDetail/imagePaste.tsx
  webapp/src/components/content/contentRegistry.tsx
  webapp/src/components/content/imageElement.tsx
Labels: 2: Dev Review

#2718 Don't notify non-board members of card changes
  mattermost-plugin/server/notifications.go
  mattermost-plugin/server/plugin.go
  server/services/notify/notifymentions/mentions_backend.go
  server/services/notify/notifysubscriptions/notifier.go
  server/services/notify/notifysubscriptions/store.go
  server/services/notify/notifysubscriptions/subscriptions_backend.go
  server/services/notify/plugindelivery/mention_deliver.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/user.go
  server/services/notify/plugindelivery/user_test.go
Labels: 2: Dev Review

#2747 Don't warn when appears in card followed by text that is not a username
  server/services/notify/notifymentions/mentions_backend.go
Labels: 2: Dev Review

#2748 GH-2745 Don't init default templates when unit testing
  Makefile
  server/app/blocks.go
  server/app/templates.go
  server/integrationtests/board_test.go
  server/integrationtests/permissions_test.go
  server/model/user.go
  server/server/server.go
  server/services/store/sqlstore/templates.go
  server/utils/debug.go
Labels: 2: Dev Review

#2571 Fixing delete/undelete boards
  server/api/api.go
  server/app/boards.go
  server/client/client.go
  server/integrationtests/blocks_test.go
  server/integrationtests/board_test.go
  server/integrationtests/permissions_test.go
  server/model/block.go
  server/services/permissions/mmpermissions/mmpermissions.go
  server/services/permissions/mmpermissions/mmpermissions_test.go
  server/services/permissions/mocks/mockstore.go
  server/services/permissions/permissions.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/boards.go
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
Labels: 2: Dev Review

#2756 Add unit test for GetAllBlocksForBoard; remove integration test GetSubtree
  server/integrationtests/blocks_test.go
  server/integrationtests/board_test.go
Labels: 2: Dev Review

#2760 Use the right single user ID on the WS implementation
  server/ws/server.go
  server/ws/server_test.go
Labels: 2: Dev Review

#2764 Add coalesce to template version migration
  server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql
Labels: 2: Dev Review

#2763 Fix configuration for prometheus address
  config.json
  docker/config.json
  server-config.json
  server/services/config/config.go
Labels: 2: Dev Review

#2768 GH-2759 - fix path to file api
  webapp/src/octoClient.ts
Labels: 2: Dev Review

#2766 update link for teams
  mattermost-plugin/webapp/src/index.tsx
Labels: 2: Dev Review

#2778 GH-2744 Fix export with hash sign (#) in block title breaks export to CSV
  server/client/client.go
  server/integrationtests/clienttestlib.go
  server/integrationtests/export_test.go
  webapp/src/csvExporter.ts
Labels: 2: Dev Review

#2779 Remove export archive from plugin header
  server/api/archive.go
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
Labels: 2: Dev Review

#2761 fix: hide 'Copy link' for `single-user` installs
  webapp/src/components/cardDialog.tsx
  webapp/src/components/gallery/gallery.test.tsx
  webapp/src/components/gallery/galleryCard.test.tsx
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/kanban/kanbanCard.tsx
Labels: Contributor

#2772 GH2575 - Focus title when card is created
  webapp/cypress/integration/createBoard.ts
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: 2: Dev Review, Contributor

#2622 GH-2449 Limits gallery card and calendar title to 5 lines
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/gallery/galleryCard.scss
  webapp/src/components/gallery/galleryCard.tsx
Labels: Contributor

#2781 Update focalboard endpoints to v2 namespace
  experiments/webext/src/utils/networking.ts
  server/admin-scripts/reset-password.sh
  server/api/api.go
  server/api/archive.go
  server/api/auth.go
  server/client/client.go
  server/main/doc.go
  server/swagger/README.md
  server/swagger/docs/html/index.html
  server/swagger/swagger.yml
  webapp/cypress/support/api_commands.ts
  webapp/src/octoClient.ts
  website/site/content/guide/admin/_index.md
Labels: 2: Dev Review

#2758 Implement permissions specs for mentions.
  mattermost-plugin/server/notifications.go
  mattermost-plugin/server/plugin.go
  server/app/blocks.go
  server/app/boards.go
  server/services/notify/notifymentions/delivery.go
  server/services/notify/notifymentions/mentions_backend.go
  server/services/notify/notifymentions/store.go
  server/services/notify/notifysubscriptions/store.go
  server/services/notify/notifysubscriptions/subscriptions_backend.go
  server/services/notify/plugindelivery/mention_deliver.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/user.go
  server/services/notify/plugindelivery/user_test.go
  server/services/notify/service.go
  server/utils/callbackqueue.go
Labels: 2: Dev Review

#2752 Applying migration changes
  mattermost-plugin/webapp/src/index.tsx
  server/api/api.go
  server/app/category_blocks.go
  server/app/category_boards.go
  server/integrationtests/permissions_test.go
  server/model/board.go
  server/model/category_blocks.go
  server/model/category_boards.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/category_boards.go
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql
  server/services/store/sqlstore/migrations/000018_populate_categories.up.sql
  server/services/store/sqlstore/migrations/000019_populate_category_blocks.down.sql
  server/services/store/sqlstore/migrations/000019_populate_category_blocks.up.sql
  server/services/store/sqlstore/migrations/000020_create_boards_members_history.up.sql
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/ws/adapter.go
  server/ws/common.go
  server/ws/plugin_adapter.go
  server/ws/server.go
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/sidebar/sidebar.test.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarBoardItem.test.tsx
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/sidebar/sidebarCategory.test.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
  webapp/src/components/sidebar/utils.ts
  webapp/src/components/workspace.test.tsx
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
  webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx
  webapp/src/store/sidebar.ts
  webapp/src/test/testBlockFactory.ts
  webapp/src/utils.ts
  webapp/src/wsclient.ts
Labels: 2: Dev Review

#2762 GH 2393 Move calculationColumns from board to view
  server/app/import.go
  server/assets/templates-boardarchive/b7wnw9awd4pnefryhq51apbzb4c/board.jsonl
  server/assets/templates-boardarchive/bbn1888mprfrm5fjw9f1je9x3xo/board.jsonl
  server/assets/templates-boardarchive/bc41mwxg9ybb69pn9j5zna6d36c/board.jsonl
  server/assets/templates-boardarchive/bd65qbzuqupfztpg31dgwgwm5ga/board.jsonl
  server/assets/templates-boardarchive/brs9cdimfw7fodyi7erqt747rhc/board.jsonl
  server/assets/templates-boardarchive/bui5izho7dtn77xg3thkiqprc9r/board.jsonl
  server/assets/templates-boardarchive/buixxjic3xjfkieees4iafdrznc/board.jsonl
  server/model/board.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql
  server/services/store/storetests/boards.go
  webapp/src/blocks/__snapshots__/board.test.ts.snap
  webapp/src/blocks/board.test.ts
  webapp/src/blocks/board.ts
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/table/calculation/calculationRow.test.tsx
  webapp/src/components/table/calculation/calculationRow.tsx
  webapp/src/mutator.ts
Labels: 2: Dev Review

#2817 revert ServerRoot path change
  mattermost-plugin/server/plugin.go
Labels: 2: Dev Review

#2818 GH-2812 Hide delete template and edit template icons unless user has permission
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
Labels: 2: Dev Review

#2821 GH-2798 - make board private when created from template
  server/services/store/sqlstore/boards_and_blocks.go
Labels: 2: Dev Review

#2823 make all duplicated boards private
  server/services/store/sqlstore/boards_and_blocks.go
Labels: 2: Dev Review

#2795 Fix focusing title
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: Contributor

#2827 GH-2808: fix some logging issues with share board.
  server/api/api.go
  server/integrationtests/sharing_test.go
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 2: Dev Review

#2820 GH-2796 - Check my membership for sidebar items
  webapp/src/components/sidebar/sidebar.test.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/store/boards.ts
Labels: 2: Dev Review

#2835 GH-2506 Calendar View
  webapp/src/components/calendar/fullCalendar.tsx
Labels: 2: Dev Review

#2844 Bump versions of github actions, golangci-lint, and Go
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-plugin.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
Labels: 2: Dev Review

#2848 Include plugin unit tests in CI via makefile; fix unit tests
  Makefile
  mattermost-plugin/server/configuration_test.go
  mattermost-plugin/server/plugin_test.go
  server/api/api.go
  server/integrationtests/clienttestlib.go
Labels: 2: Dev Review

#2834 Standardize err not found
  mattermost-plugin/server/notifications.go
  server/app/boards.go
  server/app/sharing.go
  server/app/teams.go
  server/auth/auth.go
  server/auth/auth_test.go
  server/model/error.go
  server/services/notify/notifymentions/delivery.go
  server/services/notify/notifymentions/mentions_backend.go
  server/services/notify/notifymentions/store.go
  server/services/notify/notifysubscriptions/notifier.go
  server/services/notify/notifysubscriptions/store.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/subscription_deliver.go
  server/services/notify/plugindelivery/user.go
  server/services/notify/plugindelivery/user_test.go
  server/services/permissions/localpermissions/helpers_test.go
  server/services/permissions/localpermissions/localpermissions.go
  server/services/permissions/mmpermissions/mmpermissions.go
  server/services/store/generators/main.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/category.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/notificationhints.go
  server/services/store/sqlstore/subscriptions.go
  server/services/store/sqlstore/system.go
  server/services/store/sqlstore/util.go
  server/services/store/store.go
  server/services/store/storetests/boards.go
  server/services/store/storetests/notificationhints.go
  server/services/store/storetests/subscriptions.go
  server/services/store/storetests/users.go
Labels: 2: Dev Review

#2847 Various UI Fixes
  webapp/src/components/__snapshots__/addContentMenuItem.test.tsx.snap
  webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/__snapshots__/dialog.test.tsx.snap
  webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorItem.test.tsx.snap
  webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailContentsMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/comment.test.tsx.snap
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/cardDialog.tsx
  webapp/src/components/dialog.scss
  webapp/src/components/dialog.tsx
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
  webapp/src/components/properties/user/user.scss
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableHeaderMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/emptyCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterComponent.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButtonTemplateItem.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderGroupByMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderSortMenu.test.tsx.snap
  webapp/src/styles/main.scss
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/menu/menu.scss
  webapp/src/widgets/menu/textOption.tsx
Labels: 2: Dev Review, CherryPick/Approved, AutomatedCherryPick

#2905 Added the dependency for useCallback in onChangeInSelect function
  webapp/src/components/propertyValueElement.tsx
Labels: Contributor

#2910 GH-2895 Call notification engine when duplicating boards
  server/app/app.go
  server/app/boards.go
Labels: 2: Dev Review

#2912 Reduce log level when delivering notifications with permissions error
  server/services/notify/notifymentions/mentions_backend.go
Labels: 2: Dev Review

#2909 GH-2894- Fix missing readonly token
  server/api/api.go
Labels: 2: Dev Review

#2862 Add membership check when getting team listeners
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_test.go
Labels: 2: Dev Review

#2855 Fix for undefined className prop issue in Editable component
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorPreview.test.tsx.snap
  webapp/src/components/content/__snapshots__/checkboxElement.test.tsx.snap
  webapp/src/components/content/__snapshots__/contentElement.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanban.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableGroupHeaderRow.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRows.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeader.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderSearch.test.tsx.snap
  webapp/src/widgets/editable.tsx
Labels: Contributor

#2854 Handle jsonb fields on postgres with binary_parameters set
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/util.go
Labels: 2: Dev Review

#2919 Fix Main page LInks
  website/site/layouts/partials/intro.html
Labels: Contributor

#2831 Fixing redo on card contents
  webapp/src/components/addContentMenuItem.test.tsx
  webapp/src/components/addContentMenuItem.tsx
  webapp/src/components/cardDetail/cardDetailContents.tsx
  webapp/src/components/cardDetail/cardDetailContext.tsx
  webapp/src/components/cardDetail/imagePaste.tsx
Labels: 3: Reviews Complete

#2915 GH-2890 Copy files when duplicating boards
  server/app/blocks.go
  server/app/boards.go
  server/app/onboarding_test.go
  server/model/boards_and_blocks.go
Labels: 2: Dev Review

#2859 Implement Boards Data Retention - Take 2
  mattermost-plugin/Makefile
  mattermost-plugin/go.mod
  mattermost-plugin/server/configuration.go
  mattermost-plugin/server/configuration_test.go
  mattermost-plugin/server/data_retention.go
  mattermost-plugin/server/data_retention_test.go
  mattermost-plugin/server/plugin.go
  mattermost-plugin/server/plugin_test.go
  server/server/server.go
  server/services/config/config.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/data_retention.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/store.go
  server/services/store/storetests/data_retention.go
Labels: 2: Dev Review

#2906 Initialise the store with a single user flag and pass it to the migrations
  linux/main.go
  server/integrationtests/clienttestlib.go
  server/main/main.go
  server/server/server.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql
  server/services/store/sqlstore/params.go
  server/services/store/sqlstore/sqlstore.go
Labels: 2: Dev Review

#2935 GH-2872 - Implement private icon on Share button
  webapp/src/blocks/board.ts
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/centerPanel.tsx
  webapp/src/components/shareBoard/__snapshots__/shareBoardButton.test.tsx.snap
  webapp/src/components/shareBoard/shareBoardButton.test.tsx
  webapp/src/components/shareBoard/shareBoardButton.tsx
Labels: 2: Dev Review

#2934 GH-2877 - Style Autocomplete Modal
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 1: UX Review, 2: Dev Review

#2924 Fixed bug ehere start tour param was not sent when restarting touyr
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.test.tsx
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
Labels: 2: Dev Review

#2928 Add migration to ensure all boards are either open or private
  server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql
Labels: 2: Dev Review

#2942 Move teamless data migration with the rest of data migrations and update teamless boards query
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql
Labels: 3: Reviews Complete

#2900 fix: personal server invite link omitted base URL
  webapp/src/components/sidebar/__snapshots__/registrationLink.test.tsx.snap
  webapp/src/components/sidebar/registrationLink.test.tsx
  webapp/src/components/sidebar/registrationLink.tsx
Labels: 2: Dev Review, Contributor

#2974 Remove timeout from MySQL migrations
  server/services/store/sqlstore/migrate.go
Labels: 2: Dev Review, CherryPick/Approved
