Repository mattermost-community/focalboard, pull requests merged in 2022-08, with the labels that each got.

#3430 Only show the channel unlink option if you have the right permissions
  webapp/src/components/shareBoard/channelPermissionsRow.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3453 Showing the right confirmation modals on channel-board linking
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  webapp/i18n/en.json
  webapp/src/components/confirmationDialogBox.scss
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3497 Automated cherry pick of #3430
  webapp/src/components/shareBoard/channelPermissionsRow.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3500 Automated cherry pick of #3453
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  webapp/i18n/en.json
  webapp/src/components/confirmationDialogBox.scss
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3501 GH-3461 - Updating boards default icon
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3508 Automated cherry pick of #3501
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3525 Upgrade dependencies: mmserver, plugin-api, opengraph
  .dockerignore
  Makefile
  build/gowork/main.go
  linux/go.mod
  linux/go.sum
  mattermost-plugin/Makefile
  mattermost-plugin/build/go.mod
  mattermost-plugin/build/go.sum
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  server/go.mod
  server/go.sum
  server/model/error.go
Labels: 2: Dev Review

#3494 Automated cherry pick of #3444
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
  webapp/src/components/cardDialog.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/kanban/kanban.test.tsx
  webapp/src/components/kanban/kanban.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/mutator.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3527 Automated cherry pick of #3427
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3528 Avoid panic in request error handling
  server/api/api.go
Labels: 2: Dev Review

#3486 fix: Calendar card "..." action menu overlapping behind adjacent cards
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/styles/_z-index.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3536 update min server version to 7.2
  mattermost-plugin/plugin.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3533 Automated cherry pick of #3486
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/styles/_z-index.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3504 CSS fix for top bar menu clip for custom template
  webapp/src/components/viewMenu.scss
Labels: 2: Dev Review, CherryPick/Approved

#3534 Exclude enterprise from go.work by default
  Makefile
Labels: 2: Dev Review

#3388 Added logic to add board member to my memberships is it is for me
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/store/boards.ts
Labels: 2: Dev Review, CherryPick/Approved

#3483 i18n hardcoded strings from `boardPage/UndoRedoHotKeys.tsx` in webapp
  webapp/i18n/en.json
  webapp/src/pages/boardPage/undoRedoHotKeys.tsx
Labels: Contributor

#3529 Showing properly channel association in DMs and GMs
  server/api/api.go
  webapp/src/components/shareBoard/channelPermissionsRow.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3538 Automated cherry pick of #3504
  webapp/src/components/viewMenu.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3507 GH-3350 - Updating language for linking modals
  mattermost-plugin/webapp/src/components/boardSelector.scss
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  mattermost-plugin/webapp/src/components/boardSelectorItem.scss
  webapp/i18n/en.json
  webapp/i18n/en_AU.json
  webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
  webapp/src/components/confirmationDialogBox.scss
  webapp/src/components/confirmationDialogBox.tsx
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/channelPermissionsRow.tsx
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/widgets/menu/menu.scss
Labels: 2: Dev Review, CherryPick/Approved

#3540 Automated cherry pick of #3529
  server/api/api.go
  webapp/src/components/shareBoard/channelPermissionsRow.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3556 Show the active board even when the category is hidden
  webapp/src/components/sidebar/__snapshots__/sidebarCategory.test.tsx.snap
  webapp/src/components/sidebar/sidebarCategory.test.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3552 Fix panic caused by returning nil,nil in GetMemberForBoard
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#3558 Automated cherry pick of #3556
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarCategory.test.tsx.snap
  webapp/src/components/sidebar/sidebarCategory.test.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3506 Removing the Admin role option from team minimum role
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: 2: Dev Review

#3539 Automated cherry pick of #3388
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/store/boards.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3570 Additional fix for GetMemberForBoard returning nil,nil
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: CherryPick/Approved

#3571 Automated cherry pick of #3570
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3499 Keep on sync the current team id with mattermost since the beginning
  mattermost-plugin/webapp/src/index.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3557 Show boards with syntetic membership
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#3583 Automated cherry pick of #3557
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3553 Allow to search only for linkable boards
  mattermost-plugin/webapp/src/components/boardSelector.test.tsx
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  server/api/api.go
  server/integrationtests/permissions_test.go
  webapp/src/octoClient.ts
Labels: 2: Dev Review, CherryPick/Approved

#3522 Add Version banner to hold help link.
  webapp/cypress/support/api_commands.ts
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/src/components/messages/versionMessage.scss
  webapp/src/components/messages/versionMessage.test.tsx
  webapp/src/components/messages/versionMessage.tsx
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/store/users.ts
  webapp/src/telemetry/telemetryClient.ts
Labels: 1: PM Review, 2: Dev Review, CherryPick/Approved

#3585 Automated cherry pick of #3553
  mattermost-plugin/webapp/src/components/boardSelector.test.tsx
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  server/api/api.go
  server/integrationtests/permissions_test.go
  webapp/src/octoClient.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3582 Automated cherry pick of #3499
  mattermost-plugin/webapp/src/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3005 [MM-43781] Feature: boards insights
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
  server/api/api.go
  server/app/insights.go
  server/app/insights_test.go
  server/client/client.go
  server/model/board_insights.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board_insights.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/services/store/storetests/board_insights.go
  webapp/src/insights/index.ts
  webapp/src/octoClient.ts
Labels: Contributor

#3581 Various UI fixes
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelectorItem.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardSelectorItem.scss
  mattermost-plugin/webapp/src/components/boardSelectorItem.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
  webapp/src/components/table/table.scss
Labels: 2: Dev Review, CherryPick/Approved

#3607 fix bad translation causing parse errors
  webapp/i18n/en.json
  webapp/i18n/en_AU.json
Labels: 2: Dev Review

#3586 Automated cherry pick of #3522
  webapp/cypress/support/api_commands.ts
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/src/components/messages/versionMessage.scss
  webapp/src/components/messages/versionMessage.test.tsx
  webapp/src/components/messages/versionMessage.tsx
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/store/users.ts
  webapp/src/telemetry/telemetryClient.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3606 Automated cherry pick of #3602
  mattermost-plugin/webapp/src/index.tsx
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/types/index.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3579 Persist category state
  mattermost-plugin/server/manifest.go
  server/model/category.go
  server/services/store/sqlstore/category.go
  server/services/store/sqlstore/migrations/000023_persist_category_collapsed_state.down.sql
  server/services/store/sqlstore/migrations/000023_persist_category_collapsed_state.up.sql
  server/services/store/sqlstore/migrations/000024_mark_existsing_categories_collapsed.down.sql
  server/services/store/sqlstore/migrations/000024_mark_existsing_categories_collapsed.up.sql
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/storetests/category.go
  server/services/store/storetests/categoryBoards.go
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/sidebar.test.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
  webapp/src/store/sidebar.ts
  webapp/src/test/testBlockFactory.ts
Labels: CherryPick/Approved

#3587 [GH-2965] Don't close property selector menu when item is clicked
  webapp/cypress/integration/cardBadges.ts
  webapp/src/components/cardDetail/__snapshots__/cardDetailContentsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/filterComponent.tsx
  webapp/src/components/viewHeader/filterEntry.tsx
  webapp/src/components/viewHeader/filterValue.test.tsx
  webapp/src/components/viewHeader/filterValue.tsx
  webapp/src/components/viewHeader/viewHeaderPropertiesMenu.test.tsx
  webapp/src/components/viewHeader/viewHeaderPropertiesMenu.tsx
  webapp/src/widgets/menu/colorOption.tsx
  webapp/src/widgets/menu/switchOption.tsx
  webapp/src/widgets/menu/textOption.tsx
  webapp/src/widgets/menuWrapper.tsx
Labels: Contributor

#3613 Update teamless boards migration to check for deleted entities
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/migrate.go
Labels: 2: Dev Review, CherryPick/Approved

#3618 Automated cherry pick of #3613
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/migrate.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3626 Add category to the board search
  webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.scss
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.test.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3622 GH-3564: Change boards search to "all" words
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/board.go
Labels: 2: Dev Review, CherryPick/Approved

#3594 Restricted scope of board-category change WS event to correct user
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_cluster.go
Labels: CherryPick/Approved

#3627 Automated cherry pick of #3626
  webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.scss
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.test.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3603 Automated cherry pick of #3581
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelectorItem.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardSelectorItem.scss
  mattermost-plugin/webapp/src/components/boardSelectorItem.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
  webapp/src/components/table/table.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3617 GH-3544 - Updating scrollbar color for sidebar
  webapp/src/components/sidebar/sidebar.scss
Labels: 2: Dev Review, CherryPick/Approved

#3395 Duplicate board retain category
  server/app/boards.go
  server/app/onboarding_test.go
  server/client/client.go
  server/integrationtests/board_test.go
  server/model/category.go
  webapp/src/components/sidebar/sidebarBoardItem.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3631 Automated cherry pick of #3395
  server/app/boards.go
  server/app/onboarding_test.go
  server/client/client.go
  server/integrationtests/board_test.go
  server/model/category.go
  webapp/src/components/sidebar/sidebarBoardItem.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3624 Rest API reorganization
  server/api/api.go
  server/api/archive.go
  server/api/auth.go
  server/api/blocks.go
  server/api/boards.go
  server/api/boards_and_blocks.go
  server/api/categories.go
  server/api/channels.go
  server/api/config.go
  server/api/files.go
  server/api/insights.go
  server/api/limits.go
  server/api/members.go
  server/api/onboarding.go
  server/api/search.go
  server/api/sharing.go
  server/api/subscriptions.go
  server/api/system.go
  server/api/teams.go
  server/api/templates.go
  server/api/users.go
  server/client/client.go
  server/integrationtests/clienttestlib.go
  server/integrationtests/permissions_test.go
  server/integrationtests/user_test.go
  server/model/auth.go
Labels: 2: Dev Review

#3609 GH-3597 Make sure template exists before creating card
  webapp/src/components/viewHeader/newCardButton.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3633 Automated cherry pick of #3611
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
  webapp/src/components/table/tableRow.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3632 Automated cherry pick of #3609
  webapp/src/components/viewHeader/newCardButton.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3629 Automated cherry pick of #3594
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_cluster.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3623 GH-3621- Make query case insensitive
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#3636 Automated cherry pick of #3619
  mattermost-plugin/webapp/package.json
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
  webapp/src/components/onboardingTour/index.ts
  webapp/src/components/onboardingTour/manageBoards/manageBoards.scss
  webapp/src/components/onboardingTour/manageBoards/manageBoards.tsx
  webapp/src/components/onboardingTour/manageCategories/manageCategories.scss
  webapp/src/components/onboardingTour/manageCategories/manageCategories.tsx
  webapp/src/components/onboardingTour/searchForBoards/searchForBoards.scss
  webapp/src/components/onboardingTour/searchForBoards/searchForBoards.tsx
  webapp/src/components/onboardingTour/sidebarCategories/sidebarCategories.scss
  webapp/src/components/onboardingTour/sidebarCategories/sidebarCategories.tsx
  webapp/src/components/onboardingTour/tourTipRenderer/tourTipRenderer.tsx
  webapp/src/components/searchDialog/searchDialog.tsx
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarCategory.test.tsx.snap
  webapp/src/components/sidebar/sidebar.test.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/sidebar/sidebarCategory.scss
  webapp/src/components/sidebar/sidebarCategory.test.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3630 Automated cherry pick of #3617
  webapp/src/components/sidebar/sidebar.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3628 Automated cherry pick of #3622
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/board.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3637 Automated cherry pick of #3623
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3634 Move rest API for changepassword to personal server route
  server/api/auth.go
Labels: 2: Dev Review

#3639 don't display channel roles if board is a template
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3598 Making more robust websocket notifications on synthetic memberships
  server/app/boards.go
Labels: 3: Reviews Complete, CherryPick/Approved

#3644 Automated cherry pick of #3598
  server/app/boards.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3643 Automated cherry pick of #3639
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3648 More robust RHS handling of websocket events
  mattermost-plugin/webapp/src/components/rhsChannelBoards.test.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
  server/ws/plugin_adapter.go
  webapp/src/store/boards.ts
Labels: 2: Dev Review, CherryPick/Approved

#3635 Adds data migration to clean badly assigned boards
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/legacy_blocks.go
  server/services/store/sqlstore/migrate.go
Labels: 2: Dev Review, CherryPick/Approved

#3651 fix: don't re-.push() the URL if already on teamId
  mattermost-plugin/webapp/src/index.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3653 Automated cherry pick of #3651
  mattermost-plugin/webapp/src/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3652 Automated cherry pick of #3635
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/legacy_blocks.go
  server/services/store/sqlstore/migrate.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3612 Create _index.md
  website/site/content/guide/admin/_index.md
Labels: 1: PM Review

#3657 Fixing create-board from board selector in desktop app
  webapp/src/components/workspace.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3662 Automated cherry pick of #3657
  webapp/src/components/workspace.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3665 Updated the text and changed position for sidebar Search For boards Tour
  webapp/i18n/en.json
  webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
  webapp/src/components/onboardingTour/manageBoards/manageBoards.tsx
  webapp/src/components/onboardingTour/manageCategories/manageCategories.tsx
  webapp/src/components/onboardingTour/searchForBoards/searchForBoards.scss
  webapp/src/components/onboardingTour/searchForBoards/searchForBoards.tsx
  webapp/src/components/onboardingTour/sidebarCategories/sidebarCategories.tsx
  webapp/src/components/searchDialog/searchDialog.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3671 Automated cherry pick of #3665
  webapp/i18n/en.json
  webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
  webapp/src/components/onboardingTour/manageBoards/manageBoards.tsx
  webapp/src/components/onboardingTour/manageCategories/manageCategories.tsx
  webapp/src/components/onboardingTour/searchForBoards/searchForBoards.scss
  webapp/src/components/onboardingTour/searchForBoards/searchForBoards.tsx
  webapp/src/components/onboardingTour/sidebarCategories/sidebarCategories.tsx
  webapp/src/components/searchDialog/searchDialog.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3673 fix: always try the `lastBoardId` when switching teams
  webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3672 Only allow viewer role in temaPermissionRow for templates
  webapp/src/components/shareBoard/__snapshots__/teamPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/teamPermissionsRow.test.tsx
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3674 Automated cherry pick of #3673
  webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3681 fix: `Viewer` only on a template, not board
  webapp/src/components/shareBoard/__snapshots__/teamPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: 2: Dev Review

#3684 Remove manageBoards Tour Point
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/onboardingTour/index.ts
  webapp/src/components/onboardingTour/manageBoards/manageBoards.scss
  webapp/src/components/onboardingTour/manageBoards/manageBoards.tsx
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarCategory.test.tsx.snap
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3686 Automated cherry pick of #3684
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/onboardingTour/index.ts
  webapp/src/components/onboardingTour/manageBoards/manageBoards.scss
  webapp/src/components/onboardingTour/manageBoards/manageBoards.tsx
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarCategory.test.tsx.snap
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3682 Fix Templates with empty name are shown as empty on the template list
  webapp/i18n/en.json
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
Labels: 3: Reviews Complete, Contributor

#3692 fix: return `{}` user props in single-user mode (port of #3691)
  server/api/api.go
Labels: 2: Dev Review

#3691 fix: return empty props in single-user mode
  server/api/users.go
Labels: 2: Dev Review

#3700 Register API router in product mode
  mattermost-plugin/product/api_adapter.go
  mattermost-plugin/server/api_adapter.go
  mattermost-plugin/server/boards/boardsapp.go
  server/model/mocks/mockservicesapi.go
  server/model/services_api.go
  server/services/permissions/mmpermissions/mocks/mockpluginapi.go
  server/ws/mocks/mockpluginapi.go
Labels: 3: Reviews Complete

#3689 Multiple UI Improvements - (Table improvements, sidebar consistent)
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelectorItem.test.tsx.snap
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/viewTitle.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/boardsSwitcher/boardsSwitcher.scss
  webapp/src/components/flashMessages.scss
  webapp/src/components/modal.scss
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/sidebar.scss
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/components/sidebar/sidebarCategory.scss
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableGroupHeaderRow.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRows.test.tsx.snap
  webapp/src/components/table/table.scss
  webapp/src/components/table/tableGroupHeaderRow.test.tsx
  webapp/src/components/table/tableGroupHeaderRow.tsx
  webapp/src/components/table/tableRow.scss
  webapp/src/components/table/tableRow.tsx
  webapp/src/styles/main.scss
  webapp/src/widgets/buttons/iconButton.scss
  webapp/src/widgets/icons/compassIcon.tsx
  webapp/src/widgets/icons/options.scss
Labels: 2: Dev Review

#3670 Add foundation tests
  server/go.mod
  server/go.sum
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/data_migrations_test.go
  server/services/store/sqlstore/helpers_test.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrate_test.go
  server/services/store/sqlstore/migrationstests/boards_migrator_test.go
  server/services/store/sqlstore/migrationstests/deleted_membership_boards_migration_test.go
  server/services/store/sqlstore/migrationstests/fixtures/deletedMembershipBoardsMigrationFixtures.sql
  server/services/store/sqlstore/migrationstests/fixtures/test18AddTeamsAndBoardsSQLMigrationFixtures.sql
  server/services/store/sqlstore/migrationstests/helpers_test.go
  server/services/store/sqlstore/migrationstests/migration_18_test.go
  server/services/store/sqlstore/params.go
  server/services/store/sqlstore/sqlstore.go
Labels: 3: Reviews Complete

#3711 Print log server information on plugin run
  mattermost-plugin/product/boards_product.go
  mattermost-plugin/server/plugin.go
  server/main/main.go
  server/model/version.go
Labels: 2: Dev Review, CherryPick/Candidate

#3705 Update app bar tooltip text to `Toggle Linked Boards`
  mattermost-plugin/webapp/src/index.tsx
  webapp/i18n/en.json
Labels: 2: Dev Review

#3706 Revert "Add category to the board search (#3626)"
  webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.scss
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.test.tsx
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
Labels: 2: Dev Review

#3718 GH-3589 - Make sure websocket is ready, fix for Cypress failures
  webapp/src/wsclient.ts
Labels: 2: Dev Review

#3719 Don't allow changing BoardID when patching blocks
  server/model/block.go
  server/services/store/storetests/blocks.go
  webapp/src/blocks/block.ts
Labels: 2: Dev Review

#3720 Add `disable_notify` to all block APIs that can trigger notifications.
  server/api/blocks.go
  server/app/blocks.go
  server/app/blocks_test.go
Labels: 2: Dev Review

#3703 Added role so that the non-admin will not be able to unlink the board
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoardItem.test.tsx.snap
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.scss
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.test.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoards.scss
  webapp/src/components/__snapshots__/addContentMenuItem.test.tsx.snap
  webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
  webapp/src/components/cardActionsMenu/__snapshots__/cardActionsMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailContentsMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/comment.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/teamPermissionsRow.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableHeaderMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/emptyCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterComponent.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButtonTemplateItem.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderGroupByMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderSortMenu.test.tsx.snap
  webapp/src/styles/_typography.scss
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/menu/menu.scss
  webapp/src/widgets/menu/textOption.tsx
  webapp/src/widgets/menuWrapper.scss
Labels: 2: Dev Review

#3717 Post message channel change
  mattermost-plugin/server/boards/notifications.go
  server/app/boards.go
  server/model/services_api.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
Labels: 2: Dev Review

#3696 Fixed the new button error in kanban
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.test.tsx
  webapp/src/components/kanban/kanban.test.tsx
  webapp/src/components/kanban/kanban.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3726 Automated cherry pick of #3696
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.test.tsx
  webapp/src/components/kanban/kanban.test.tsx
  webapp/src/components/kanban/kanban.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3727 Add Preferences service API for product and plugin
  mattermost-plugin/product/api_adapter.go
  mattermost-plugin/product/boards_product.go
  mattermost-plugin/server/api_adapter.go
  server/model/mocks/mockservicesapi.go
  server/model/services_api.go
  server/services/store/mockstore/mockstore.go
Labels: 2: Dev Review

#3733 Set FOCALBOARD_UNIT_TESTING for integration tests
  server/integrationtests/clienttestlib.go
Labels: 3: Reviews Complete

#3731 stack banners if multiple displayed
  webapp/src/pages/boardPage/boardPage.scss
Labels: 2: Dev Review

#3732 Updates db indexes to improve performance
  server/services/store/sqlstore/migrations/000025_indexes_update.down.sql
  server/services/store/sqlstore/migrations/000025_indexes_update.up.sql
  server/services/store/storetests/blocks.go
Labels: 3: Reviews Complete, CherryPick/Approved

#3736 Automated cherry pick of #3732
  server/services/store/sqlstore/migrations/000025_indexes_update.down.sql
  server/services/store/sqlstore/migrations/000025_indexes_update.up.sql
  server/services/store/storetests/blocks.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2882 Adding the permissions for commenter + viewer roles
  server/api/blocks.go
  server/integrationtests/permissions_test.go
  server/model/permission.go
  server/services/permissions/localpermissions/localpermissions.go
  server/services/permissions/mmpermissions/mmpermissions.go
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/cardDetail/commentsList.test.tsx
  webapp/src/components/cardDetail/commentsList.tsx
  webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/userPermissionsRow.test.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/constants.ts
  webapp/src/hooks/permissions.tsx
Labels: 2: Dev Review

#3725 Adds a check that errors on store start if MariaDB is detected
  server/services/store/sqlstore/sqlstore.go
Labels: 2: Dev Review, CherryPick/Approved

#3737 Automated cherry pick of #3725
  server/services/store/sqlstore/sqlstore.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3713 Adding menu options in sidebar, and improving order
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardSelector.scss
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
  webapp/src/components/__snapshots__/dialog.test.tsx.snap
  webapp/src/components/boardsSwitcher/boardsSwitcher.scss
  webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
  webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
  webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.scss
  webapp/src/components/createCategory/__snapshots__/createCategory.test.tsx.snap
  webapp/src/components/createCategory/createCategory.scss
  webapp/src/components/createCategory/createCategory.test.tsx
  webapp/src/components/createCategory/createCategory.tsx
  webapp/src/components/dialog.scss
  webapp/src/components/dialog.tsx
  webapp/src/components/searchDialog/searchDialog.scss
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/sidebar.test.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
  webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialog.test.tsx.snap
  webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialogWrapper.test.tsx.snap
  webapp/src/widgets/menu/menu.scss
Labels: 2: Dev Review

#3743 GH-3293 - Fix issue with deleted members not being updated via websocket
  webapp/src/store/boards.ts
Labels: 3: Reviews Complete

#3729 Close template selector if same board/view clicked
  webapp/src/components/sidebar/__snapshots__/sidebarCategory.test.tsx.snap
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarCategory.test.tsx
  webapp/src/components/sidebar/sidebarCategory.tsx
  webapp/src/components/workspace.tsx
Labels: 2: Dev Review

#3755 getBlocks store API with query options
  server/model/block.go
  server/services/permissions/mmpermissions/mocks/mockpluginapi.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/ws/mocks/mockpluginapi.go
Labels: 3: Reviews Complete

#3758 Added functionality to close boardSelector after linking board
  mattermost-plugin/webapp/src/components/boardSelector.tsx
Labels: 2: Dev Review

#2852 GH-2520 make cut/undo/redo work in comments
  webapp/cypress/integration/createBoard.ts
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/__snapshots__/markdownEditor.test.tsx.snap
  webapp/src/components/__snapshots__/viewTitle.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailContents.test.tsx.snap
  webapp/src/components/content/__snapshots__/textElement.test.tsx.snap
  webapp/src/components/markdownEditor.tsx
  webapp/src/components/markdownEditorInput/markdownEditorInput.scss
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: Lifecycle/1:stale, Contributor

#3757 GH-3704 - Fix for not copying all content items.
  webapp/src/store/contents.ts
Labels: 2: Dev Review

#3761 Fix @-mentions in boards & for guests
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Labels: 2: Dev Review
