Repository mattermost-community/focalboard, pull requests merged in 2022-06, with the labels that each got.

#3151 Update en.json: Bug fix and consistency
  webapp/cypress/integration/cardBadges.ts
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/topBar.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorItem.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
  webapp/src/components/calculations/options.tsx
  webapp/src/components/cardDetail/__snapshots__/cardDetail.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/cardDetail/cardDetailContents.tsx
  webapp/src/components/cardDetail/cardDetailProperties.test.tsx
  webapp/src/components/cardDetail/cardDetailProperties.tsx
  webapp/src/components/cardLimitNotification.tsx
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/hiddenCardCount/hiddenCardCount.tsx
  webapp/src/components/onboardingTour/copyLink/__snapshots__/copyLink.test.tsx.snap
  webapp/src/components/onboardingTour/copyLink/copy_link.tsx
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/sidebar/deleteBoardDialog.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/topBar.tsx
  webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeaderPropertiesMenu.test.tsx
  webapp/src/components/viewHeader/viewHeaderPropertiesMenu.tsx
  webapp/src/components/viewLimitDialog/viewLimitDialog.tsx
  webapp/src/components/workspace.tsx
  webapp/src/errors.ts
  webapp/src/pages/dashboard/__snapshots__/centerContent.test.tsx.snap
  webapp/src/pages/dashboard/centerContent.tsx
  webapp/src/pages/welcome/__snapshots__/welcomePage.test.tsx.snap
  webapp/src/pages/welcome/welcomePage.tsx
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/propertyMenu.tsx
Labels: 2: Dev Review

#3160 Fixed for new button new button not working
  webapp/src/components/centerPanel.tsx
  webapp/src/mutator.ts
  webapp/src/octoUtils.tsx
Labels: 2: Dev Review

#3153 Translations update from Mattermost Weblate
  webapp/i18n/hr.json
  webapp/i18n/ml.json
Labels: Do Not Merge/Mattermod

#3162 Fixing Issue 3124
  webapp/src/components/centerPanel.tsx
  webapp/src/store/limits.ts
Labels: 2: Dev Review

#3167 Checks if the cards property on the limits payload is nil before dere…
  server/app/cloud.go
  server/app/cloud_test.go
Labels: 2: Dev Review

#3171 [GH-3170] Fix overflow for ValueSelector menu
  webapp/src/widgets/valueSelector.scss
Labels: 3: Reviews Complete, Contributor

#3157 fix: delete `.action-cell` CSS bg color
  webapp/src/components/table/tableRow.scss
Labels: 1: UX Review

#3181 Fix limits selector and stores limitsEnabled value to avoid race condition
  webapp/src/components/centerPanel.tsx
  webapp/src/components/workspace.tsx
  webapp/src/store/limits.ts
Labels: 2: Dev Review

#3146 GH-3143 Fix for calendar popout transparency
  webapp/src/components/calendar/fullcalendar.scss
Labels: 2: Dev Review

#3197 update version to v7.0.1
  mac/Focalboard/Info.plist
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
  webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
Labels: 2: Dev Review

#3196 Migration fixes
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrations/000017_placeholder.down.sql
  server/services/store/sqlstore/migrations/000017_placeholder.up.sql
  server/services/store/sqlstore/migrations/000018_add_teams_and_boards.down.sql
  server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql
  server/services/store/sqlstore/migrations/000019_populate_categories.down.sql
  server/services/store/sqlstore/migrations/000019_populate_categories.up.sql
  server/services/store/sqlstore/migrations/000020_populate_category_blocks.down.sql
  server/services/store/sqlstore/migrations/000020_populate_category_blocks.up.sql
  server/services/store/sqlstore/migrations/000021_create_boards_members_history.down.sql
  server/services/store/sqlstore/migrations/000021_create_boards_members_history.up.sql
  server/services/store/sqlstore/migrations/000022_create_default_board_role.down.sql
  server/services/store/sqlstore/migrations/000022_create_default_board_role.up.sql
Labels: 2: Dev Review

#3182 [MM-44657] Client side code for insights
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
  webapp/src/insights/index.ts
  webapp/src/octoClient.ts
Labels: 2: Dev Review

#3172 Git attributes for linguist
  .gitattributes
Labels: Contributor

#3180 Added a Dialog notification after clicking on the Cards hidden button
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
  webapp/src/components/cardLimitNotification.tsx
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/gallery/gallery.test.tsx
  webapp/src/components/gallery/gallery.tsx
  webapp/src/components/hiddenCardCount/hiddenCardCount.scss
  webapp/src/components/hiddenCardCount/hiddenCardCount.tsx
  webapp/src/components/kanban/kanban.test.tsx
  webapp/src/components/kanban/kanban.tsx
  webapp/src/components/table/table.test.tsx
  webapp/src/components/table/table.tsx
  webapp/src/widgets/notification-box.scss
Labels: 2: Dev Review

#3215 Translations update from Mattermost Weblate
  webapp/i18n/sv.json
  webapp/i18n/zh_Hans.json
Labels: Do Not Merge/Mattermod

#3227 Personal server fixes for cloud message
  webapp/src/components/centerPanel.tsx
  webapp/src/components/messages/__snapshots__/cloudMessage.test.tsx.snap
  webapp/src/components/messages/cloudMessage.test.tsx
  webapp/src/components/messages/cloudMessage.tsx
  webapp/src/store/users.ts
  webapp/src/userSettings.ts
Labels: 2: Dev Review

#3212 [GH-3211] Fix switching of views
  webapp/src/components/workspace.tsx
Labels: Contributor

#3213 Adds limits implementation to the server
  linux/go.mod
  linux/go.sum
  mattermost-plugin/server/plugin.go
  mattermost-plugin/webapp/src/index.tsx
  server/api/api.go
  server/app/app.go
  server/app/auth_test.go
  server/app/blocks.go
  server/app/blocks_test.go
  server/app/boards.go
  server/app/boards_and_blocks.go
  server/app/cloud.go
  server/app/cloud_test.go
  server/app/import.go
  server/client/client.go
  server/go.mod
  server/go.sum
  server/model/block.go
  server/model/cloud.go
  server/model/error.go
  server/server/params.go
  server/server/server.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/cloud.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/sqlstore/util.go
  server/services/store/store.go
  server/services/store/storetests/cloud.go
  server/utils/utils.go
  server/ws/adapter.go
  server/ws/common.go
  server/ws/plugin_adapter.go
  server/ws/server.go
  webapp/src/hooks/cardListener.tsx
  webapp/src/octoClient.ts
  webapp/src/octoUtils.test.ts
  webapp/src/pages/boardPage/websocketConnection.tsx
  webapp/src/store/globalTemplates.ts
  webapp/src/wsclient.ts
Labels: 3: Reviews Complete

#3230 fixes for personal server app notification (#3227)
  webapp/src/components/messages/__snapshots__/cloudMessage.test.tsx.snap
  webapp/src/components/messages/cloudMessage.test.tsx
  webapp/src/components/messages/cloudMessage.tsx
  webapp/src/store/users.ts
  webapp/src/userSettings.ts
Labels: 2: Dev Review

#3229 Adding the "contact admin" link
  webapp/i18n/en.json
  webapp/src/components/cardLimitNotification.scss
  webapp/src/components/cardLimitNotification.tsx
  webapp/src/telemetry/telemetryClient.ts
  webapp/src/widgets/notification-box.tsx
Labels: 2: Dev Review

#3237 fix: handles null or empty clientConfig
  webapp/src/route.tsx
Labels: Contributor

#3234 GH-2951 Only display confirm on type change
  webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
  webapp/src/components/cardDetail/cardDetailProperties.test.tsx
  webapp/src/components/cardDetail/cardDetailProperties.tsx
Labels: 2: Dev Review

#3250 [GH-2966] Disable card detail properties hover state for shared readonly view
  webapp/src/components/__snapshots__/propertyValueElement.test.tsx.snap
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/properties/createdAt/createdAt.tsx
  webapp/src/components/properties/createdBy/__snapshots__/createdBy.test.tsx.snap
  webapp/src/components/properties/dateRange/dateRange.test.tsx
  webapp/src/components/properties/lastModifiedAt/__snapshots__/lastModifiedAt.test.tsx.snap
  webapp/src/components/properties/lastModifiedAt/lastModifiedAt.tsx
  webapp/src/components/properties/lastModifiedBy/__snapshots__/lastModifiedBy.test.tsx.snap
  webapp/src/components/properties/link/__snapshots__/link.test.tsx.snap
  webapp/src/components/properties/link/link.tsx
  webapp/src/components/properties/multiSelect/__snapshots__/multiSelect.test.tsx.snap
  webapp/src/components/properties/multiSelect/multiSelect.tsx
  webapp/src/components/properties/select/__snapshots__/select.test.tsx.snap
  webapp/src/components/properties/select/select.tsx
  webapp/src/components/properties/user/__snapshots__/user.test.tsx.snap
  webapp/src/components/properties/user/user.scss
  webapp/src/components/properties/user/user.tsx
  webapp/src/components/propertyValueElement.tsx
  webapp/src/components/propertyValueUtils.ts
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/widgets/switch.scss
  webapp/src/widgets/switch.tsx
Labels: 3: Reviews Complete, Contributor

#3174 Porting the card limits frontend to main branch
  webapp/i18n/en.json
  webapp/src/app.tsx
  webapp/src/blocks/block.ts
  webapp/src/boardUtils.ts
  webapp/src/boardsCloudLimits/index.ts
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
  webapp/src/components/cardBadges.test.tsx
  webapp/src/components/cardLimitNotification.tsx
  webapp/src/components/centerPanel.scss
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/content/checkboxElement.test.tsx
  webapp/src/components/content/contentElement.test.tsx
  webapp/src/components/content/imageElement.test.tsx
  webapp/src/components/content/textElement.test.tsx
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/gallery.scss
  webapp/src/components/gallery/gallery.test.tsx
  webapp/src/components/gallery/gallery.tsx
  webapp/src/components/hiddenCardCount/hiddenCardCount.scss
  webapp/src/components/hiddenCardCount/hiddenCardCount.tsx
  webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
  webapp/src/components/kanban/kanban.scss
  webapp/src/components/kanban/kanban.test.tsx
  webapp/src/components/kanban/kanban.tsx
  webapp/src/components/kanban/kanbanHiddenColumnItem.test.tsx
  webapp/src/components/kanban/kanbanHiddenColumnItem.tsx
  webapp/src/components/messages/cloudMessage.test.tsx
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/table.test.tsx
  webapp/src/components/table/table.tsx
  webapp/src/components/workspace.test.tsx
  webapp/src/components/workspace.tsx
  webapp/src/octoClient.ts
  webapp/src/store/cards.ts
  webapp/src/store/index.ts
  webapp/src/store/initialLoad.ts
  webapp/src/store/limits.ts
  webapp/src/store/users.ts
  webapp/src/telemetry/telemetryClient.ts
  webapp/src/test/testBlockFactory.ts
  webapp/src/user.tsx
  webapp/src/widgets/__snapshots__/notification-box.test.tsx.snap
  webapp/src/widgets/editable.scss
  webapp/src/widgets/editableDayPicker.scss
  webapp/src/widgets/icons/alert.tsx
  webapp/src/widgets/notification-box.scss
  webapp/src/widgets/notification-box.test.tsx
  webapp/src/widgets/notification-box.tsx
Labels: 2: Dev Review

#3249 GH-3050 - Fix deleting empty property
  server/integrationtests/boards_and_blocks_test.go
  server/model/boards_and_blocks.go
  server/model/boards_and_blocks_test.go
Labels: 2: Dev Review

#3086 Feature: board insights - against 7.0 release
  linux/go.mod
  linux/go.sum
  mattermost-plugin/build/go.mod
  mattermost-plugin/build/go.sum
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
  server/api/api.go
  server/app/insights.go
  server/app/insights_test.go
  server/app/user.go
  server/client/client.go
  server/go.mod
  server/go.sum
  server/model/board_insights.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board_insights.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/sqlstore/user.go
  server/services/store/sqlstore/workspaces.go
  server/services/store/store.go
  server/services/store/storetests/board_insights.go
  webapp/src/insights/index.ts
  webapp/src/octoClient.ts
Labels: 2: QA Review

#3251 Added the scroll to all the view in the drop down for view switcher
  webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
  webapp/src/components/viewMenu.scss
  webapp/src/components/viewMenu.tsx
Labels: 1: UX Review, 2: Dev Review

#3257 add cyclo complexity, update migrate() to use defer
  mattermost-plugin/.golangci.yml
  server/.golangci.yml
  server/services/store/sqlstore/migrate.go
Labels: 2: Dev Review

#3126 `main` Cherrypick: Hidden card view via direct URL & unfurl (#3071)
  Makefile
  mattermost-plugin/webapp/package-lock.json
  mattermost-plugin/webapp/package.json
  mattermost-plugin/webapp/src/components/boardsUnfurl/__snapshots__/boardsUnfurl.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.scss
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.test.tsx
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.tsx
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
  webapp/i18n/en.json
  webapp/package.json
  webapp/src/blocks/block.ts
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetail.test.tsx.snap
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/cardDetail/cardDetail.test.tsx
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/cardDialog.test.tsx
  webapp/src/components/cardDialog.tsx
  webapp/src/errors.ts
  webapp/src/svg/card-skeleton.tsx
  webapp/src/svg/error-illustration.tsx
  webapp/src/svg/search-illustration.tsx
Labels: 3: Reviews Complete

#3260 fix: handles clientConfig causing board error
  webapp/src/components/onboardingTour/tourTipRenderer/tourTipRenderer.tsx
Labels: Contributor

#3245 update: instructions for prebuild for dev setup
  README.md
Labels: 1: PM Review, Contributor

#3274 Replace date with focalboard version
  webapp/src/components/__snapshots__/topBar.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/sidebarUserMenu.tsx
  webapp/src/components/topBar.tsx
Labels: Enhancement
