Repository mattermost-community/focalboard, pull requests merged in 2022-09, with the labels that each got.

#3709 Refactor schema table migration mechanism
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/schema_table_migration.go
  server/services/store/sqlstore/schema_table_migration_test.go
Labels: 2: Dev Review

#3774 Extra safe MySQL migration
  server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
Labels: CherryPick/Candidate

#3775 Fix migration 27 and update boards_migrator_test to support sqlite
  server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
  server/services/store/sqlstore/migrationstests/boards_migrator_test.go
  server/services/store/sqlstore/migrationstests/fixtures/test27MigrateUserPropsToPreferences.sql
  server/services/store/sqlstore/migrationstests/migration_27_test.go
Labels: 2: Dev Review

#3747 Fix template websocket
  mattermost-plugin/server/manifest.go
  server/app/boards.go
  server/app/boards_test.go
  server/app/onboarding_test.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 3: Reviews Complete

#3778 GH-3768 - Search icon fix
  mattermost-plugin/webapp/src/components/boardSelector.scss
  webapp/src/components/searchDialog/searchDialog.scss
  webapp/src/components/viewHeader/viewHeader.scss
Labels: 2: Dev Review, CherryPick/Approved

#3766 check createdBy instead of team id to determine global templates
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
  webapp/src/constants.ts
Labels: 2: Dev Review

#3794 Add remove templates channel link migration
  server/services/store/sqlstore/migrations/000028_remove_template_channel_link.down.sql
  server/services/store/sqlstore/migrations/000028_remove_template_channel_link.up.sql
  server/services/store/sqlstore/migrationstests/fixtures/test28RemoveTemplateChannelLink.sql
  server/services/store/sqlstore/migrationstests/migration_28_test.go
Labels: 2: Dev Review, CherryPick/Approved

#3817 Read Mattermost s3 timeout value and used a default if not exist
  mattermost-plugin/server/boards/boardsapp_util.go
  server/server/server.go
  server/services/config/config.go
Labels: 2: Dev Review, CherryPick/Approved

#3818 Automated cherry pick of #3817
  mattermost-plugin/server/boards/boardsapp_util.go
  server/server/server.go
  server/services/config/config.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3819 Update to version 7.4.0
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review

#3762 fix: filter out bots for sharing, @mention-ing, and Person property
  Makefile
  server/api/teams.go
  server/app/user.go
  server/integrationtests/pluginteststore.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/swagger/docs/html/index.html
  server/swagger/swagger.yml
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/octoClient.ts
  webapp/src/properties/person/person.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3793 Added corner case check for multiperson property
  webapp/src/properties/multiperson/multiperson.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3828 Automated cherry pick of #3793
  webapp/src/properties/multiperson/multiperson.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3823 Automated cherry pick of #3762
  Makefile
  server/api/teams.go
  server/app/user.go
  server/integrationtests/pluginteststore.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/swagger/docs/html/index.html
  server/swagger/swagger.yml
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/octoClient.ts
  webapp/src/properties/person/person.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3829 Automated cherry pick of #3827
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/confirmAddUserForNotifications.test.tsx.snap
  webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
  webapp/src/components/__snapshots__/dialog.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorItem.test.tsx.snap
  webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
  webapp/src/components/cardDialog.scss
  webapp/src/components/cardDialog.tsx
  webapp/src/components/createCategory/__snapshots__/createCategory.test.tsx.snap
  webapp/src/components/createCategory/createCategory.test.tsx
  webapp/src/components/createCategory/createCategory.tsx
  webapp/src/components/dialog.scss
  webapp/src/components/dialog.tsx
  webapp/src/components/searchDialog/searchDialog.scss
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialog.test.tsx.snap
  webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialogWrapper.test.tsx.snap
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3748 MM-46274 Web App Product POC
  Makefile
  mattermost-plugin/Makefile
  mattermost-plugin/webapp/package-lock.json
  mattermost-plugin/webapp/package.json
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoards.test.tsx.snap
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoardsHeader.test.tsx.snap
  mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoardsHeader.tsx
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/plugin_entry.ts
  mattermost-plugin/webapp/src/remote_entry.ts
  mattermost-plugin/webapp/webpack.config.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/utils.ts
  webapp/static/app-bar-icon.png
  webapp/static/boards-screenshots.png
Labels: 3: Reviews Complete

#3822 Update version banner URL to redirect permalink
  webapp/src/components/messages/versionMessage.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3837 Automated cherry pick of #3822
  webapp/src/components/messages/versionMessage.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3795 test: add snapshot tests to CommentsList
  webapp/src/components/cardDetail/__snapshots__/commentsList.test.tsx.snap
  webapp/src/components/cardDetail/commentsList.test.tsx
Labels: 2: Dev Review

#3820 GH-3797 Update telemetry to send boards count
  server/app/boards.go
  server/app/boards_test.go
  server/server/server.go
  server/services/metrics/metrics.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/boards.go
Labels: 2: Dev Review, CherryPick/Approved

#3838 Automated cherry pick of #3820
  server/app/boards.go
  server/app/boards_test.go
  server/server/server.go
  server/services/metrics/metrics.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/boards.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3839 Fix broken image in plugin
  mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
Labels: 2: Dev Review

#3840 Fix broken main store.getBoardsInTeamByIds
  server/services/store/sqlstore/board.go
  server/services/store/storetests/boards.go
Labels: 2: Dev Review

#3842 Check on GetBoardsForUserAndTeam if the board result list is incomplete and continue if that's the case
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/board.go
  server/services/store/storetests/boards.go
Labels: 2: Dev Review

#3841 fix: display non-explicit members in Share Board modal <Select>
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3844 Automated cherry pick of #3841
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3835 Multiple UI Fixes
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoardItem.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardSelector.scss
  mattermost-plugin/webapp/src/components/boardSelector.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
  webapp/src/components/__snapshots__/addContentMenuItem.test.tsx.snap
  webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/confirmAddUserForNotifications.test.tsx.snap
  webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/__snapshots__/dialog.test.tsx.snap
  webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorItem.test.tsx.snap
  webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
  webapp/src/components/cardActionsMenu/__snapshots__/cardActionsMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetailContentsMenu.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/comment.test.tsx.snap
  webapp/src/components/cardDialog.tsx
  webapp/src/components/createCategory/__snapshots__/createCategory.test.tsx.snap
  webapp/src/components/dialog.scss
  webapp/src/components/dialog.tsx
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
  webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
  webapp/src/components/markdownEditorInput/entryComponent/entryComponent.scss
  webapp/src/components/markdownEditorInput/entryComponent/entryComponent.tsx
  webapp/src/components/markdownEditorInput/markdownEditorInput.scss
  webapp/src/components/searchDialog/searchDialog.scss
  webapp/src/components/searchDialog/searchDialog.tsx
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/teamPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/emptyCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButton.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/newCardButtonTemplateItem.test.tsx.snap
  webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialog.test.tsx.snap
  webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialogWrapper.test.tsx.snap
  webapp/src/properties/multiperson/multiperson.scss
  webapp/src/widgets/menu/menu.scss
  webapp/src/widgets/menu/subMenuOption.tsx
  webapp/src/widgets/menu/switchOption.tsx
  webapp/src/widgets/menu/textOption.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3843 Update user store to return the updated entities after inserting / patching them
  server/api/users.go
  server/app/auth.go
  server/app/auth_test.go
  server/app/onboarding.go
  server/app/onboarding_test.go
  server/app/user.go
  server/integrationtests/permissions_test.go
  server/integrationtests/pluginteststore.go
  server/model/user.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/store.go
  server/services/store/storetests/users.go
  server/services/store/storetests/util.go
Labels: 3: Reviews Complete, CherryPick/Approved

#3836 Fixing minimum board roles behavior
  mattermost-plugin/webapp/src/components/rhsChannelBoardItem.test.tsx
  webapp/src/blocks/board.ts
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/hooks/permissions.tsx
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/properties/person/person.tsx
  webapp/src/store/boards.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#3801 Added single-user check for getUserList
  server/api/users.go
Labels: 2: Dev Review

#3858 Catch exception on failed WS command to avoid interface from breaking
  webapp/src/wsclient.ts
Labels: 2: Dev Review, CherryPick/Approved

#3860 Automated cherry pick of #3858
  webapp/src/wsclient.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3857 Gh 3849 - Fixing menu text and submenu icon
  webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/buttons/buttonWithMenu.scss
  webapp/src/widgets/menu/subMenuOption.scss
  webapp/src/widgets/menu/subMenuOption.tsx
Labels: 2: Dev Review, CherryPick/Approved

#3873 Automated cherry pick of #3857
  webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
  webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
  webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
  webapp/src/widgets/buttons/buttonWithMenu.scss
  webapp/src/widgets/menu/subMenuOption.scss
  webapp/src/widgets/menu/subMenuOption.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3868 Fix a placeholder message when sharing template
  webapp/i18n/en.json
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
Labels: Contributor

#3790 Showing unknown channel and on share board modals if channel is no longer accessible
  mattermost-plugin/server/manifest.go
  webapp/i18n/en.json
  webapp/src/components/shareBoard/__snapshots__/channelPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/channelPermissionsRow.test.tsx
  webapp/src/components/shareBoard/channelPermissionsRow.tsx
  webapp/src/components/viewHeader/filterEntry.tsx
  webapp/src/mutator.ts
Labels: 2: Dev Review, CherryPick/Approved

#3880 GH-3815 Fix for Error Page redirection
  webapp/src/pages/boardPage/boardPage.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3889 Automated cherry pick of #3819
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3893 Automated cherry pick of #3880
  webapp/src/pages/boardPage/boardPage.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3875 Fix members
  server/api/members.go
  server/integrationtests/board_test.go
  server/services/notify/notifymentions/mentions_backend.go
  webapp/i18n/en.json
  webapp/src/blocks/board.ts
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/confirmAddUserForNotifications.scss
  webapp/src/components/confirmAddUserForNotifications.test.tsx
  webapp/src/components/confirmAddUserForNotifications.tsx
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/teamPermissionsRow.test.tsx
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/hooks/permissions.tsx
  webapp/src/mutator.ts
  webapp/src/properties/person/person.tsx
Labels: 2: Dev Review, CherryPick/Candidate

#3887 Gh 3882 - Fixes layout for ConfirmAddUserForNotification
  webapp/src/components/confirmAddUserForNotifications.scss
Labels: 2: Dev Review, CherryPick/Approved

#3897 Automated cherry pick of #3887
  webapp/src/components/confirmAddUserForNotifications.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
