Repository mattermost-community/focalboard, pull requests merged in 2022-02, with the labels that each got.

#2203 Changing active-border to active-border-rgb in the css variables
  webapp/src/components/sidebar/sidebarBoardItem.scss
  webapp/src/theme.ts
Labels: 2: Dev Review

#2173 [GH-2147] URL property improvement
  webapp/cypress/integration/cardURLProperty.ts
  webapp/cypress/support/api_commands.ts
  webapp/cypress/support/index.ts
  webapp/cypress/tsconfig.json
  webapp/i18n/en.json
  webapp/i18n/en_AU.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/propertyValueElement.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/calendar/__snapshots__/fullCalendar.test.tsx.snap
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/components/gallery/galleryCard.scss
  webapp/src/components/kanban/kanbanCard.scss
  webapp/src/components/properties/link/__snapshots__/link.test.tsx.snap
  webapp/src/components/properties/link/link.scss
  webapp/src/components/properties/link/link.test.tsx
  webapp/src/components/properties/link/link.tsx
  webapp/src/components/table/tableRow.scss
  webapp/src/components/viewHeader/__snapshots__/newCardButtonTemplateItem.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeader.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewHeader/viewHeaderActionsMenu.test.tsx
  webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/widgets/icons/edit.scss
  webapp/src/widgets/icons/edit.tsx
Labels: 3: Reviews Complete, Contributor

#2196 Add permissions modal
  server/api/api.go
  server/app/boards.go
  server/client/client.go
  server/integrationtests/board_test.go
  server/model/board.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/board.go
  webapp/i18n/en.json
  webapp/src/components/cardDetail/cardDetail.test.tsx
  webapp/src/components/cardDetail/cardDetailContents.test.tsx
  webapp/src/components/cardDetail/comment.test.tsx
  webapp/src/components/cardDetail/commentsList.test.tsx
  webapp/src/components/cardDialog.test.tsx
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/content/textElement.test.tsx
  webapp/src/components/contentBlock.test.tsx
  webapp/src/components/dialog.scss
  webapp/src/components/dialog.tsx
  webapp/src/components/markdownEditor.test.tsx
  webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
  webapp/src/components/properties/createdBy/createdBy.test.tsx
  webapp/src/components/properties/lastModifiedBy/lastModifiedBy.test.tsx
  webapp/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
  webapp/src/components/properties/user/user.test.tsx
  webapp/src/components/properties/user/user.tsx
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/components/table/table.test.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewTitle.test.tsx
  webapp/src/components/workspace.test.tsx
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
  webapp/src/pages/boardPage.tsx
  webapp/src/store/boards.ts
  webapp/src/store/cards.ts
  webapp/src/store/users.ts
  webapp/src/styles/main.scss
  webapp/src/utils.ts
  webapp/src/widgets/switch.scss
  webapp/src/widgets/switch.tsx
  webapp/src/wsclient.ts
Labels: 3: Reviews Complete

#2167 Upgrade default templates on launch
  server/model/block.go
  server/services/store/generators/transactional_store.go.tmpl
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/archive.go
  server/services/store/sqlstore/initializations/bindata.go
  server/services/store/sqlstore/initializations/templates/templates.json
  server/services/store/sqlstore/initialize.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
Labels: 3: Reviews Complete

#2201 Import/export moved to server + image support + streaming
  linux/go.sum
  mattermost-plugin/go.sum
  server/api/api.go
  server/api/archive.go
  server/api/auth.go
  server/app/blocks.go
  server/app/export.go
  server/app/import.go
  server/go.mod
  server/go.sum
  server/model/block.go
  server/model/import_export.go
  server/model/user.go
  webapp/src/archiver.ts
  webapp/src/blocks/archive.test.ts
  webapp/src/blocks/archive.ts
  webapp/src/lineReader.ts
  webapp/src/mutator.ts
  webapp/src/octoClient.test.ts
  webapp/src/octoClient.ts
Labels: 3: Reviews Complete

#2213 Update dependencies for webapp and mattermost-plugin/webapp
  mattermost-plugin/webapp/package-lock.json
  mattermost-plugin/webapp/package.json
  webapp/package-lock.json
  webapp/package.json
Labels: 3: Reviews Complete

#2218 Fix panic in PropDef.GetValue for `person` property types.
  server/model/properties.go
Labels: 2: Dev Review

#2232 Update CHANGELOG.md for v0.14 release
  CHANGELOG.md
Labels: 3: Reviews Complete, CherryPick/Approved

#2235 Automated cherry pick of #2232
  CHANGELOG.md
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2210 Add importer for Nextcloud Deck
  import/nextcloud-deck/.eslintrc.json
  import/nextcloud-deck/.gitignore
  import/nextcloud-deck/README.md
  import/nextcloud-deck/deck.ts
  import/nextcloud-deck/importDeck.ts
  import/nextcloud-deck/package-lock.json
  import/nextcloud-deck/package.json
  import/nextcloud-deck/tsconfig.json
  import/nextcloud-deck/utils.ts
Labels: Contributor

#2261 Update CHANGELOG.md
  CHANGELOG.md
Labels: 3: Reviews Complete, CherryPick/Approved

#2254 Fix export archive file extension
  webapp/src/archiver.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#2255 Fied a bug where user Cannot edit description block if only a space
  webapp/src/components/markdownEditor.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2253 Copy images when duplicating card/board
  server/api/api.go
  server/app/blocks.go
  server/services/store/sqlstore/blocks.go
  webapp/src/mutator.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#2267 Automated cherry pick of #2253
  server/api/api.go
  server/app/blocks.go
  server/services/store/sqlstore/blocks.go
  webapp/src/mutator.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2265 Automated cherry pick of #2254
  webapp/src/archiver.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2264 Automated cherry pick of #2261
  CHANGELOG.md
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2274 Automated cherry pick of #2260
  Makefile
  webapp/src/components/cardDialog.test.tsx
  webapp/src/components/cardDialog.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2194 Growth Spike - implement imports to help redirect
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.test.tsx
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/sidebar/sidebarSettingsMenu.test.tsx
  webapp/src/components/sidebar/sidebarSettingsMenu.tsx
  webapp/src/constants.ts
  webapp/src/telemetry/telemetryClient.ts
Labels: 3: Reviews Complete

#2256 Reduce noise in logs
  mattermost-plugin/server/plugin.go
  server/ws/helpers_test.go
  server/ws/plugin_adapter.go
Labels: 3: Reviews Complete, CherryPick/Approved

#2259 Fixes "Something went wrong" error when selecting certain templates
  webapp/src/store/contents.ts
Labels: 3: Reviews Complete, CherryPick/Approved

#2284 Automated cherry pick of #2259
  webapp/src/store/contents.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2283 Automated cherry pick of #2256
  mattermost-plugin/server/plugin.go
  server/ws/helpers_test.go
  server/ws/plugin_adapter.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2279 GH-2249 - Updating template selector screen
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorPreview.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
Labels: CherryPick/Approved

#2292 Automated cherry pick of #2279
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorPreview.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2252 Revert "implement registry for channel intro button (#2181)"
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
  webapp/src/telemetry/telemetryClient.ts
Labels: 2: Dev Review, CherryPick/Approved

#2295 Preview the first view of the template
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
Labels: CherryPick/Approved

#2297 Automated cherry pick of #2295
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2286 Growth share board modal
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/shareBoardComponent.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
  webapp/src/components/centerPanel.scss
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/dialog.tsx
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/shareBoardButton.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/shareBoardButton.scss
  webapp/src/components/shareBoard/shareBoardButton.test.tsx
  webapp/src/components/shareBoard/shareBoardButton.tsx
  webapp/src/components/shareBoardComponent.scss
  webapp/src/components/shareBoardComponent.tsx
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
  webapp/src/components/viewHeader/viewHeader.test.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewHeader/viewHeaderActionsMenu.test.tsx
  webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
  webapp/src/pages/dashboard/__snapshots__/centerContent.test.tsx.snap
  webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
  webapp/src/styles/main.scss
  webapp/src/telemetry/telemetryClient.ts
  webapp/src/widgets/switch.scss
  webapp/src/widgets/switch.tsx
Labels: 1: UX Review, 2: Dev Review

#2263 MM-41342 Revert fixes related to using team sidebar in products
  webapp/src/pages/boardPage.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2221 Fixing style problems on hover editable board templates
  webapp/src/blocks/board.ts
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2303 Automated cherry pick of #2221
  webapp/src/blocks/board.ts
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2262 GH-2257: Calculation column order to be based on view
  webapp/src/components/table/calculation/calculationRow.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2304 Automated cherry pick of #2262
  webapp/src/components/table/calculation/calculationRow.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2294 [MM-36643] Use Mattermost SiteURL to determine rudder cookie domain
  mattermost-plugin/webapp/src/index.tsx
Labels: 2: Dev Review

#1309 fixed label and text alignment under hidden columns
  webapp/src/components/kanban/kanban.scss
  webapp/src/widgets/label.scss
Labels: 1: UX Review, 2: Dev Review, Lifecycle/1:stale

#2314 GH-2306 Restore ArchiveUtils for import scripts
  import/asana/importAsana.ts
  import/jira/jiraImporter.ts
  import/notion/importNotion.ts
  import/todoist/importTodoist.ts
  import/trello/importTrello.ts
  import/util/archive.ts
Labels: 3: Reviews Complete

#2332 [GH-1491] Change wrapping in React.memo
  webapp/src/app.tsx
  webapp/src/components/addContentMenuItem.tsx
  webapp/src/components/blockIconSelector.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
  webapp/src/components/cardDetail/cardDetailContents.tsx
  webapp/src/components/cardDetail/cardDetailContentsMenu.tsx
  webapp/src/components/cardDetail/cardDetailProperties.tsx
  webapp/src/components/cardDetail/commentsList.tsx
  webapp/src/components/content/checkboxElement.tsx
  webapp/src/components/content/dividerElement.tsx
  webapp/src/components/content/imageElement.tsx
  webapp/src/components/content/textElement.tsx
  webapp/src/components/contentBlock.tsx
  webapp/src/components/dialog.tsx
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/components/kanban/kanbanColumn.tsx
  webapp/src/components/modal.tsx
  webapp/src/components/modalWrapper.tsx
  webapp/src/components/properties/select/select.tsx
  webapp/src/components/rootPortal.tsx
  webapp/src/components/shareBoard/shareBoardButton.tsx
  webapp/src/components/sidebar/registrationLink.tsx
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarBoardItem.tsx
  webapp/src/components/sidebar/sidebarSettingsMenu.tsx
  webapp/src/components/sidebar/sidebarUserMenu.tsx
  webapp/src/components/table/horizontalGrip.tsx
  webapp/src/components/table/tableGroup.tsx
  webapp/src/components/table/tableGroupHeaderRow.tsx
  webapp/src/components/table/tableHeader.tsx
  webapp/src/components/table/tableRow.tsx
  webapp/src/components/topBar.tsx
  webapp/src/components/viewHeader/emptyCardButton.tsx
  webapp/src/components/viewHeader/filterComponent.tsx
  webapp/src/components/viewHeader/filterEntry.tsx
  webapp/src/components/viewHeader/newCardButton.tsx
  webapp/src/components/viewHeader/newCardButtonTemplateItem.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
  webapp/src/components/viewHeader/viewHeaderDisplayByMenu.tsx
  webapp/src/components/viewHeader/viewHeaderGroupByMenu.tsx
  webapp/src/components/viewHeader/viewHeaderPropertiesMenu.tsx
  webapp/src/components/viewHeader/viewHeaderSortMenu.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/components/viewTitle.tsx
  webapp/src/components/workspace.tsx
  webapp/src/pages/changePasswordPage.tsx
  webapp/src/pages/dashboard/dashboardPage.tsx
  webapp/src/pages/errorPage.tsx
  webapp/src/pages/loginPage.tsx
  webapp/src/pages/registerPage.tsx
  webapp/src/pages/welcome/welcomePage.tsx
  webapp/src/widgets/menuWrapper.tsx
  webapp/src/widgets/propertyMenu.tsx
  webapp/src/widgets/valueSelector.tsx
Labels: 3: Reviews Complete, Contributor

#2334 Fix #2333. Handle export in Mac App
  mac/Focalboard.xcodeproj/project.pbxproj
  mac/Focalboard/DownloadHandler.swift
  mac/Focalboard/ViewController.swift
Labels: CherryPick/Candidate

#2342 Translations update from Mattermost Weblate
  webapp/i18n/hr.json
Labels: Changelog/Not Needed, Docs/Not Needed

#2317 Don't use property value for key construction.
  webapp/src/components/cardDetail/cardDetailProperties.tsx
  webapp/src/components/modal.tsx
  webapp/src/components/properties/dateRange/dateRange.test.tsx
  webapp/src/components/properties/dateRange/dateRange.tsx
  webapp/src/components/propertyValueElement.tsx
Labels: Contributor

#2299 wrap registration block to catch error
  mattermost-plugin/webapp/src/index.tsx
Labels: 2: Dev Review

#2285 MM-41176 Don't send Rudder requests when blocked
  mattermost-plugin/webapp/src/index.tsx
Labels: 3: Reviews Complete

#2352 Fix panic when creating new card in notifysubscriptions
  server/model/blocktype.go
  server/services/notify/notifysubscriptions/subscriptions_backend.go
Labels: 2: Dev Review

#2268 GH-2258: allow date range to overflow
  webapp/src/components/properties/dateRange/dateRange.scss
  webapp/src/components/table/table.scss
Labels: 3: Reviews Complete

#2351 Update readme with accurate Linux standalone app build instructions
  README.md
Labels: 1: PM Review

#2179 [GH-1543] Switch component style fixed
  webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
  webapp/src/pages/dashboard/__snapshots__/centerContent.test.tsx.snap
  webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
  webapp/src/widgets/switch.scss
  webapp/src/widgets/switch.tsx
Labels: 3: Reviews Complete, Contributor

#2222 Adding sever side undelete endpoint
  server/.golangci.yml
  server/api/api.go
  server/app/blocks.go
  server/app/blocks_test.go
  server/client/client.go
  server/integrationtests/blocks_test.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  webapp/src/mutator.ts
  webapp/src/octoClient.ts
Labels: 3: Reviews Complete

#2366 Update _index.md
  website/site/content/guide/user/_index.md
Labels: 2: Dev Review

#2386 Fix notification diff for text blocks
  mattermost-plugin/server/plugin.go
  server/api/api.go
  server/app/blocks.go
  server/app/boards.go
  server/app/boards_and_blocks.go
  server/app/category.go
  server/services/notify/notifysubscriptions/diff.go
  server/services/notify/notifysubscriptions/diff2slackattachments.go
  server/services/notify/notifysubscriptions/notifier.go
  server/services/notify/notifysubscriptions/subscriptions_backend.go
  server/services/notify/plugindelivery/mention_deliver.go
  server/services/notify/plugindelivery/message.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/permissions/mmpermissions/helpers_test.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/boards_and_blocks.go
  server/utils/links.go
Labels: 2: Dev Review

#2414 Fix migration sql error
  server/app/teams_test.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/migrations/migrations_files/000017_add_teams_and_boards.up.sql
Labels: 3: Reviews Complete
