Repository mattermost-community/focalboard, pull requests merged in 2022-12, with the labels that each got.

#4243 [MM-48592] Make my insights available in free tier
  server/app/insights.go
Labels: 2: QA Review

#4270 Update version to v7.7.0
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review

#4284 Fixed bug where boards would move to category of a different team
  server/app/boards_test.go
  server/app/category_boards.go
  server/app/category_boards_test.go
  server/app/category_test.go
  server/app/import_test.go
  server/app/onboarding_test.go
Labels: 3: Reviews Complete, CherryPick/Candidate

#4286 Automated cherry pick of #4284
  server/app/boards_test.go
  server/app/category_boards.go
  server/app/category_boards_test.go
  server/app/category_test.go
  server/app/import_test.go
  server/app/onboarding_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4305 [MM-48592] Make my insights available in free tier
  server/app/insights.go
Labels: 3: Reviews Complete

#4308 Replace SearchBoardsForUserInTeam query with a more efficient one
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review

#4312 Modify query in SearchBoardsForUser to use union.
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#4309 Automated cherry pick of #4308
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4322 Automated cherry pick of #4312
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4323 Automated cherry pick of #4312
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4310 Automated cherry pick of #4308
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4327 Fixes positional arguments in UNION queries
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#4329 Automated cherry pick of #4327
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4331 Automated cherry pick of #4325
  server/services/store/sqlstore/data_migrations.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4317 Update version 7.5.4
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review

#4320 [MM-48883] reflect app <-> product package changes
  mattermost-plugin/product/boards_product.go
Labels: 2: Dev Review

#4335 Update query to only allow open boards for team members
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#4343 Automated cherry pick of #4335
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4330 migrations: update morph dependecy and apply changes (#4208)
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  server/api/insights.go
  server/go.mod
  server/go.sum
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrationstests/boards_migrator_test.go
Labels: 2: Dev Review

#4290 Fix transparent background on weekends
  webapp/src/components/calendar/fullcalendar.scss
Labels: 2: Dev Review, 2: QA Review

#4351 Cherry-pick 4320: reflect app <-> product package changes (#4320)
  mattermost-plugin/product/boards_product.go
Labels: 2: Dev Review

#4328 ToolTip for Table view menu
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRows.test.tsx.snap
  webapp/src/components/table/tableRow.tsx
Labels: 1: UX Review, 2: Dev Review

#4347 Fix default collation on preferences table
  server/services/store/sqlstore/migrations/000026_create_preferences_table.up.sql
Labels: 2: Dev Review

#4341 go.mod: update mattermost-server dependency
  linux/go.mod
  linux/go.sum
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  server/go.mod
  server/go.sum
Labels: 2: Dev Review

#4282 Allow empty dates returned from date property
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/properties/createdTime/property.tsx
  webapp/src/properties/date/property.tsx
  webapp/src/properties/types.tsx
Labels: 2: Dev Review, 2: QA Review

#4350 GH-4332 - Updating card editor classes
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetail.test.tsx.snap
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/dialog.scss
Labels: 2: Dev Review, 2: QA Review

#4253 Idempotent schema and data migrations
  Makefile
  docker-testing/docker-compose-mysql.yml
  docker-testing/docker-compose-postgres.yml
  server/services/permissions/mmpermissions/mocks/mockpluginapi.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrations/000003_blocks_rootid.up.sql
  server/services/store/sqlstore/migrations/000005_blocks_modifiedby.up.sql
  server/services/store/sqlstore/migrations/000008_teams.up.sql
  server/services/store/sqlstore/migrations/000009_blocks_history.up.sql
  server/services/store/sqlstore/migrations/000010_blocks_created_by.up.sql
  server/services/store/sqlstore/migrations/000011_match_collation.up.sql
  server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql
  server/services/store/sqlstore/migrations/000019_populate_categories.up.sql
  server/services/store/sqlstore/migrations/000020_populate_category_blocks.up.sql
  server/services/store/sqlstore/migrations/000021_create_boards_members_history.up.sql
  server/services/store/sqlstore/migrations/000022_create_default_board_role.up.sql
  server/services/store/sqlstore/migrations/000023_persist_category_collapsed_state.up.sql
  server/services/store/sqlstore/migrations/000024_mark_existing_categories_collapsed.down.sql
  server/services/store/sqlstore/migrations/000024_mark_existing_categories_collapsed.up.sql
  server/services/store/sqlstore/migrations/000025_indexes_update.up.sql
  server/services/store/sqlstore/migrations/000026_create_preferences_table.up.sql
  server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
  server/services/store/sqlstore/migrations/000029_add_category_type_field.up.sql
  server/services/store/sqlstore/migrations/000030_add_category_sort_order.up.sql
  server/services/store/sqlstore/migrations/000031_add_category_boards_sort_order.up.sql
  server/services/store/sqlstore/migrations/000032_move_boards_category_to_end.up.sql
  server/services/store/sqlstore/migrations/README.md
  server/services/store/sqlstore/migrationstests/boards_migrator_test.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/util.go
  server/ws/mocks/mockpluginapi.go
Labels: 3: Reviews Complete

#4291 Search boards by prop
  server/api/search.go
  server/app/boards.go
  server/client/client.go
  server/integrationtests/pluginteststore.go
  server/model/board.go
  server/model/error.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/boards.go
Labels: 3: Reviews Complete

#4358 Automated cherry pick of #4355
  mattermost-plugin/server/manifest.go
  webapp/src/styles/main.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4359 Automated cherry pick of #4350
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetail.test.tsx.snap
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/dialog.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4297 Fixed delete menu hover issue
  webapp/src/components/content/attachmentElement.scss
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#4296 Fixed the length
  webapp/src/components/content/attachmentElement.tsx
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#4364 Automated cherry pick of #4297
  webapp/src/components/content/attachmentElement.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4365 Automated cherry pick of #4296
  webapp/src/components/content/attachmentElement.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4337 Dnd remove default column value
  server/services/store/sqlstore/category.go
  server/services/store/sqlstore/migrations/000030_add_category_sort_order.up.sql
  server/services/store/sqlstore/migrations/000031_add_category_boards_sort_order.up.sql
Labels: 2: Dev Review, CherryPick/Approved

#4367 Rename migration 24 back to original name
  server/services/store/sqlstore/migrations/000024_mark_existsing_categories_collapsed.down.sql
  server/services/store/sqlstore/migrations/000024_mark_existsing_categories_collapsed.up.sql
Labels: 2: Dev Review, CherryPick/Approved

#4362 GH-4298 - Updating link boards modal item
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelectorItem.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardSelectorItem.scss
  mattermost-plugin/webapp/src/components/boardSelectorItem.tsx
Labels: 2: Dev Review, CherryPick/Approved

#4370 Automated cherry pick of #4362
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelectorItem.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardSelectorItem.scss
  mattermost-plugin/webapp/src/components/boardSelectorItem.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4268 Disable cloud limits
  mattermost-plugin/server/boards/boardsapp.go
  server/app/blocks.go
  server/app/blocks_test.go
  server/app/cloud.go
  server/app/cloud_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#4393 Automated cherry pick of #4268
  mattermost-plugin/server/boards/boardsapp.go
  server/app/blocks.go
  server/app/blocks_test.go
  server/app/cloud.go
  server/app/cloud_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4353 GH-4316 - if no title, use 'untitled board' in message
  server/app/boards.go
Labels: 2: Dev Review, CherryPick/Approved

#4387 GH-4385 - Updating padding for boardselectoritem
  mattermost-plugin/webapp/src/components/boardSelectorItem.scss
Labels: 2: Dev Review, CherryPick/Approved

#4397 Automated cherry pick of #4387
  mattermost-plugin/webapp/src/components/boardSelectorItem.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4372 Expose boards APIs for MPA
  mattermost-plugin/product/boards_product.go
  mattermost-plugin/server/boards/boards_service_api.go
  server/app/app.go
  server/app/permissions.go
  server/model/board.go
Labels: 2: Dev Review

#4395 services/store: use mattermost sql settings for migration connections
  mattermost-plugin/server/boards/boardsapp.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/params.go
  server/services/store/sqlstore/sqlstore.go
Labels: 3: Reviews Complete

#4400 Add DuplicateBoard to service API
  mattermost-plugin/server/boards/boards_service_api.go
Labels: 3: Reviews Complete

#4348 Fixed the CSV export for created by property
  webapp/src/csvExporter.ts
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#4394 Automated cherry pick of #4353
  server/app/boards.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
