Repository mattermost-community/focalboard, pull requests merged in 2022-05, with the labels that each got.

#2986 GH-2970 - Check for propertyValue not null
  webapp/src/store/cards.ts
Labels: 2: Dev Review, CherryPick/Approved

#2997 GH-2995- Fix for following
  webapp/src/pages/boardPage/websocketConnection.tsx
Labels: 2: Dev Review, CherryPick/Approved

#2937 Last updated by aligement fixed
  webapp/src/components/properties/lastModifiedBy/__snapshots__/lastModifiedBy.test.tsx.snap
  webapp/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/table.test.tsx
Labels: CherryPick/Approved, Contributor

#3007 Automated cherry pick of #2986
  webapp/src/store/cards.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3008 Automated cherry pick of #2997
  webapp/src/pages/boardPage/websocketConnection.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3009 Automated cherry pick of #2937
  webapp/src/components/properties/lastModifiedBy/__snapshots__/lastModifiedBy.test.tsx.snap
  webapp/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/table.test.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3004 Fixed incorrect navigation bug
  mattermost-plugin/server/manifest.go
  webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx
Labels: CherryPick/Approved

#2940 Feature added: Pressing enter should create a category
  webapp/src/components/createCategory/createCategory.tsx
Labels: CherryPick/Approved, Contributor

#3011 GH- 2987 - Add "copy" to board title when duplicated
  server/services/store/sqlstore/boards_and_blocks.go
Labels: CherryPick/Approved

#2969 Displayed only board members in autocomplete
  webapp/src/store/boards.ts
Labels: CherryPick/Approved

#3023 Automated cherry pick of #3011
  server/services/store/sqlstore/boards_and_blocks.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3024 Automated cherry pick of #2969
  webapp/src/store/boards.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#2925 2889 - Hiding images on share modal on personal
  mattermost-plugin/webapp/src/plugin.scss
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/styles/_modifiers.scss
  webapp/src/styles/main.scss
  webapp/src/theme.ts
Labels: 1: PM Review, 2: Dev Review, CherryPick/Approved

#3027 Automated cherry pick of #2925
  mattermost-plugin/webapp/src/plugin.scss
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.scss
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/styles/_modifiers.scss
  webapp/src/styles/main.scss
  webapp/src/theme.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3026 GH-2469 Add board-bot to team
  mattermost-plugin/server/notifications.go
  server/services/notify/notifysubscriptions/delivery.go
  server/services/notify/notifysubscriptions/notifier.go
  server/services/notify/plugindelivery/mention_deliver.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/subscription_deliver.go
  server/services/notify/plugindelivery/user_test.go
Labels: 2: Dev Review

#3030 Automated cherry pick of #3012
  server/app/blocks.go
  server/app/boards.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3031 Standardize env variable naming
  Makefile
  mattermost-plugin/Makefile
  server/services/store/sqlstore/util.go
  server/utils/debug.go
  server/web/webserver.go
Labels: 2: Dev Review

#2383 Added delete feature in Table view
  webapp/i18n/en.json
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableRows.test.tsx.snap
  webapp/src/components/table/table.scss
  webapp/src/components/table/table.test.tsx
  webapp/src/components/table/tableRow.scss
  webapp/src/components/table/tableRow.tsx
Labels: 2: Dev Review, Lifecycle/1:stale, Contributor

#3051 Fix broken webapp in main
  webapp/src/components/table/table.test.tsx
Labels: 2: Dev Review

#3045 GH-3039 - Backport notify fixes
  .gitignore
  mattermost-plugin/server/notifications.go
  server/services/notify/notifymentions/mentions_backend.go
  server/services/notify/notifysubscriptions/delivery.go
  server/services/notify/notifysubscriptions/notifier.go
  server/services/notify/notifysubscriptions/subscriptions_backend.go
  server/services/notify/plugindelivery/mention_deliver.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/subscription_deliver.go
  server/services/notify/plugindelivery/user_test.go
Labels: 2: Dev Review

#3046 [Main] Add Cloud Message to Personal server/desktop
  server/api/api.go
  webapp/src/components/messages/__snapshots__/cloudMessage.test.tsx.snap
  webapp/src/components/messages/cloudMessage.scss
  webapp/src/components/messages/cloudMessage.test.tsx
  webapp/src/components/messages/cloudMessage.tsx
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/store/users.ts
  webapp/src/telemetry/telemetryClient.ts
  webapp/src/widgets/buttons/iconButton.scss
Labels: 3: Reviews Complete

#3047 [release-7.0] Add Cloud Message to Personal server/desktop
  server/api/api.go
  webapp/src/components/messages/__snapshots__/cloudMessage.test.tsx.snap
  webapp/src/components/messages/cloudMessage.scss
  webapp/src/components/messages/cloudMessage.test.tsx
  webapp/src/components/messages/cloudMessage.tsx
  webapp/src/pages/boardPage.tsx
  webapp/src/store/users.ts
  webapp/src/telemetry/telemetryClient.ts
  webapp/src/widgets/buttons/iconButton.scss
Labels: 3: Reviews Complete

#3067 Fix for null propertyValue
  webapp/src/store/cards.ts
Labels: 3: Reviews Complete

#3063 GH-3060 Fix Read-only calendar
  webapp/src/components/calendar/__snapshots__/fullCalendar.test.tsx.snap
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/calendar/fullcalendar.scss
  webapp/src/components/messages/cloudMessage.tsx
Labels: 3: Reviews Complete

#3058 Add an endpoint and client method to fetch the boards cloud limits
  linux/go.mod
  linux/go.sum
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  mattermost-plugin/server/plugin.go
  server/api/api.go
  server/app/app.go
  server/app/cloud.go
  server/go.mod
  server/go.sum
  server/model/cloud.go
  server/server/params.go
  server/server/server.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/storetests/blocks.go
  server/ws/mocks/mockpluginapi.go
  webapp/src/boardsCloudLimits/index.ts
  webapp/src/octoClient.ts
Labels: 2: Dev Review

#3032 [GH-2442] Improve performance for table column resize
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/calculations/__snapshots__/calculation.test.tsx.snap
  webapp/src/components/calculations/calculation.test.tsx
  webapp/src/components/calculations/calculation.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableHeader.test.tsx.snap
  webapp/src/components/table/__snapshots__/tableHeaders.test.tsx.snap
  webapp/src/components/table/calculation/calculationRow.test.tsx
  webapp/src/components/table/calculation/calculationRow.tsx
  webapp/src/components/table/horizontalGrip.tsx
  webapp/src/components/table/table.tsx
  webapp/src/components/table/tableColumnResizeContext.tsx
  webapp/src/components/table/tableGroup.tsx
  webapp/src/components/table/tableGroupHeaderRow.test.tsx
  webapp/src/components/table/tableGroupHeaderRow.tsx
  webapp/src/components/table/tableHeader.test.tsx
  webapp/src/components/table/tableHeader.tsx
  webapp/src/components/table/tableHeaders.test.tsx
  webapp/src/components/table/tableHeaders.tsx
  webapp/src/components/table/tableRow.test.tsx
  webapp/src/components/table/tableRow.tsx
  webapp/src/components/table/tableRows.test.tsx
  webapp/src/components/table/tableRows.tsx
  webapp/src/constants.ts
Labels: 3: Reviews Complete, Contributor

#3054 Backport GetBoardMetadata()
  server/api/api.go
  server/app/auth_test.go
  server/app/boards.go
  server/client/client.go
  server/integrationtests/board_test.go
  server/integrationtests/clienttestlib.go
  server/integrationtests/teststore.go
  server/model/board.go
  server/model/user.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/boards.go
  server/swagger/docs/html/.openapi-generator/VERSION
  server/swagger/docs/html/index.html
  server/swagger/swagger.yml
Labels: 3: Reviews Complete

#2828 GH-1919 fix unexpected dialog close
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
  webapp/src/components/__snapshots__/dialog.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorItem.test.tsx.snap
  webapp/src/components/dialog.scss
  webapp/src/components/dialog.tsx
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
Labels: 3: Reviews Complete, Contributor

#3052 Added fileinfo tracking
  linux/go.mod
  linux/go.sum
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  server/api/api.go
  server/app/files.go
  server/app/files_test.go
  server/go.mod
  server/go.sum
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/file.go
  server/services/store/sqlstore/migrations/bindata.go
  server/services/store/sqlstore/migrations/migrations_files/000017_add_file_info.down.sql
  server/services/store/sqlstore/migrations/migrations_files/000017_add_file_info.up.sql
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  webapp/package-lock.json
  webapp/src/blocks/block.ts
  webapp/src/components/content/__snapshots__/imageElement.test.tsx.snap
  webapp/src/components/content/archivedFile/archivedFile.scss
  webapp/src/components/content/archivedFile/archivedFile.tsx
  webapp/src/components/content/imageElement.test.tsx
  webapp/src/components/content/imageElement.tsx
  webapp/src/components/contentBlock.test.tsx
  webapp/src/components/gallery/galleryCard.test.tsx
  webapp/src/octoClient.ts
  webapp/src/utils.ts
  webapp/src/widgets/icons/brokenFile.tsx
Labels: 3: Reviews Complete

#3090 GH-2988 Don't redundantly send config chg messages to cluster nodes
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_cluster.go
Labels: 3: Reviews Complete

#3088 Add cypress:debug script to webapp/package.json
  webapp/package.json
Labels: 2: Dev Review, Contributor

#3037 Added Tests for NewServer() , snapshot matching
  server/web/webserver_test.go
Labels: 3: Reviews Complete, Contributor

#3089 View limits
  mattermost-plugin/server/plugin.go
  mattermost-plugin/webapp/src/components/cloudUpgradeNudge/cloudUpgradeNudge.tsx
  mattermost-plugin/webapp/src/index.tsx
  server/api/api.go
  server/app/blocks.go
  server/app/cloud.go
  server/app/cloud_test.go
  server/model/cloud.go
  server/model/user.go
  server/server/params.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/user.go
  server/services/store/sqlstore/workspaces.go
  server/services/store/store.go
  server/utils/utils.go
  webapp/i18n/en.json
  webapp/src/boardsCloudLimits/index.ts
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.test.tsx
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/messages/cloudMessage.test.tsx
  webapp/src/components/viewHeader/viewHeader.test.tsx
  webapp/src/components/viewHeader/viewHeader.tsx
  webapp/src/components/viewLimitDialog/viewLimitDialog.scss
  webapp/src/components/viewLimitDialog/viewLimitDialog.tsx
  webapp/src/components/viewMenu.test.tsx
  webapp/src/components/viewMenu.tsx
  webapp/src/components/workspace.test.tsx
  webapp/src/octoClient.ts
  webapp/src/store/index.ts
  webapp/src/store/initialLoad.ts
  webapp/src/store/limits.ts
  webapp/src/telemetry/telemetryClient.ts
  webapp/src/user.tsx
  webapp/src/utils.ts
  webapp/static/upgrade.png
Labels: 2: Dev Review

#3087 Add cloud limits
  .vscode/launch.json
  Makefile
  mattermost-plugin/server/plugin.go
  mattermost-plugin/webapp/src/index.tsx
  modd-servertest.conf
  modd.conf
  server/api/api.go
  server/app/app.go
  server/app/blocks.go
  server/app/cloud.go
  server/app/cloud_test.go
  server/model/block.go
  server/server/server.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/cloud.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/store.go
  server/services/store/storetests/cloud.go
  server/utils/utils.go
  server/ws/adapter.go
  server/ws/common.go
  server/ws/plugin_adapter.go
  server/ws/server.go
  webapp/src/blocks/block.ts
  webapp/src/blocks/card.ts
  webapp/src/blocks/imageBlock.ts
  webapp/src/components/workspace.tsx
  webapp/src/wsclient.ts
Labels: 2: Dev Review

#3071 Hidden card view via direct URL & unfurl
  Makefile
  mattermost-plugin/webapp/package-lock.json
  mattermost-plugin/webapp/package.json
  mattermost-plugin/webapp/src/components/boardsUnfurl/__snapshots__/boardsUnfurl.test.tsx.snap
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.scss
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.test.tsx
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.tsx
  mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
  webapp/i18n/en.json
  webapp/package.json
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/cardDetail/__snapshots__/cardDetail.test.tsx.snap
  webapp/src/components/cardDetail/cardDetail.scss
  webapp/src/components/cardDetail/cardDetail.test.tsx
  webapp/src/components/cardDetail/cardDetail.tsx
  webapp/src/components/cardDialog.test.tsx
  webapp/src/components/cardDialog.tsx
  webapp/src/components/workspace.tsx
  webapp/src/errors.ts
  webapp/src/svg/card-skeleton.tsx
Labels: 2: Dev Review

#3076 GH-2992 - Drag drop card to groups doesn't work
  webapp/src/components/table/table.tsx
Labels: 3: Reviews Complete

#3074 Notification box for card limit
  webapp/src/app.tsx
  webapp/src/components/cardBadges.test.tsx
  webapp/src/components/cardLimitNotification.scss
  webapp/src/components/cardLimitNotification.tsx
  webapp/src/components/centerPanel.scss
  webapp/src/components/centerPanel.tsx
  webapp/src/components/gallery/gallery.test.tsx
  webapp/src/components/workspace.tsx
  webapp/src/store/cards.ts
  webapp/src/store/index.ts
  webapp/src/store/limits.ts
  webapp/src/store/users.ts
  webapp/src/styles/main.scss
  webapp/src/telemetry/telemetryClient.ts
  webapp/src/widgets/__snapshots__/notification-box.test.tsx.snap
  webapp/src/widgets/editable.scss
  webapp/src/widgets/editableDayPicker.scss
  webapp/src/widgets/icons/alert.tsx
  webapp/src/widgets/notification-box.scss
  webapp/src/widgets/notification-box.test.tsx
  webapp/src/widgets/notification-box.tsx
  webapp/src/wsclient.ts
Labels: 1: UX Review, 2: Dev Review

#3107 Improve apply cloud limits to leave templates unlimited
  mattermost-plugin/server/plugin.go
  server/api/api.go
  server/app/cloud.go
  server/app/cloud_test.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
Labels: 2: Dev Review

#3102 Fix #3072. Add docs on how to auth to API readme.
  server/swagger/README.md
Labels: 2: Dev Review, 2. Editor Review

#3127 Forbid updating limited cards
  server/api/api.go
  server/app/app.go
  server/app/blocks.go
  server/app/blocks_test.go
  server/app/cloud.go
  server/app/cloud_test.go
  server/client/client.go
  server/model/block.go
Labels: 2: Dev Review

#3139 Don't fetch blocks that belong to deleted boards
  server/services/store/sqlstore/blocks.go
  server/services/store/storetests/blocks.go
Labels: 2: Dev Review

#3141 Cypress test `wait` increase
  webapp/cypress/integration/createBoard.ts
Labels: 2: Dev Review

#3142 GH-3123 Fix notify admin on request upgrade
  server/api/api.go
  server/app/app.go
  server/server/server.go
  webapp/cypress/integration/createBoard.ts
  webapp/src/octoClient.ts
Labels: 2: Dev Review

#3125 fix(webapp): template from global is modifiable
  webapp/src/mutator.ts
Labels: 2: Dev Review

#3094 Feature to show hidden card count
  webapp/i18n/en.json
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.test.tsx
  webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
  webapp/src/components/centerPanel.test.tsx
  webapp/src/components/centerPanel.tsx
  webapp/src/components/content/checkboxElement.test.tsx
  webapp/src/components/content/contentElement.test.tsx
  webapp/src/components/content/imageElement.test.tsx
  webapp/src/components/content/textElement.test.tsx
  webapp/src/components/gallery/__snapshots__/gallery.test.tsx.snap
  webapp/src/components/gallery/gallery.scss
  webapp/src/components/gallery/gallery.test.tsx
  webapp/src/components/gallery/gallery.tsx
  webapp/src/components/hiddenCardCount/hiddenCardCount.scss
  webapp/src/components/hiddenCardCount/hiddenCardCount.tsx
  webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
  webapp/src/components/kanban/kanban.scss
  webapp/src/components/kanban/kanban.test.tsx
  webapp/src/components/kanban/kanban.tsx
  webapp/src/components/kanban/kanbanHiddenColumnItem.test.tsx
  webapp/src/components/kanban/kanbanHiddenColumnItem.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/table.test.tsx
  webapp/src/components/table/table.tsx
  webapp/src/components/workspace.tsx
  webapp/src/store/cards.ts
  webapp/src/test/testBlockFactory.ts
Labels: 1: UX Review, 2: Dev Review

#3150 fix: filter bots in person property select
  webapp/src/components/properties/user/user.tsx
Labels: 2: Dev Review

#3149 Update limit timestamp after running an import
  server/app/import.go
Labels: 2: Dev Review
