Repository mattermost-community/focalboard, pull requests merged in 2023-07, with the labels that each got.

#4798 Automated cherry pick of #4797
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4802 Filter the fileinfo deletion query on block child deletion
  server/services/store/sqlstore/blocks.go
Labels: 3: Reviews Complete, QA Verified

#4810 Automated cherry pick of #4802
  server/services/store/sqlstore/blocks.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4809 Automated cherry pick of #4802
  server/services/store/sqlstore/blocks.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4808 Automated cherry pick of #4802
  server/services/store/sqlstore/blocks.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4807 Automated cherry pick of #4802
  server/services/store/sqlstore/blocks.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4815 Adds a database migration to restore the fileinfos that are deleted
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.down.sql
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.up.sql
  server/services/store/sqlstore/migrationstests/fixtures/test40FixFileinfoSoftDeletes.sql
  server/services/store/sqlstore/migrationstests/migration40_test.go
Labels: 2: Dev Review

#4816 Automated cherry pick of #4815
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.down.sql
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.up.sql
  server/services/store/sqlstore/migrationstests/fixtures/test40FixFileinfoSoftDeletes.sql
  server/services/store/sqlstore/migrationstests/migration40_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4819 Automated cherry pick of #4815
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.down.sql
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.up.sql
  server/services/store/sqlstore/migrationstests/fixtures/test40FixFileinfoSoftDeletes.sql
  server/services/store/sqlstore/migrationstests/migration40_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4818 Automated cherry pick of #4815
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.down.sql
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.up.sql
  server/services/store/sqlstore/migrationstests/fixtures/test40FixFileinfoSoftDeletes.sql
  server/services/store/sqlstore/migrationstests/migration40_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4817 Automated cherry pick of #4815
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.down.sql
  server/services/store/sqlstore/migrations/000040_fix_fileinfo_soft_deletes.up.sql
  server/services/store/sqlstore/migrationstests/fixtures/test40FixFileinfoSoftDeletes.sql
  server/services/store/sqlstore/migrationstests/migration40_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4820 Sanitize user following config for ShowFullName and ShowEmailAddress
  server/api/users.go
  server/app/user.go
  server/model/user.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mattermostauthlayer/mattermostauthlayer_test.go
Labels: 3: Reviews Complete
