Repository mattermost-community/focalboard, pull requests merged in 2023-03, with the labels that each got.

#4608 Disable patches on read-only unmount for url property
  webapp/src/properties/url/url.tsx
Labels: 3: Reviews Complete, QA Verified

#4609 Updating welcome screen for small sizes
  webapp/src/pages/welcome/__snapshots__/welcomePage.test.tsx.snap
  webapp/src/pages/welcome/welcomePage.scss
  webapp/src/pages/welcome/welcomePage.tsx
Labels: 1: PM Review, 2: Dev Review

#4597 Updating date when prop has changed
  webapp/src/properties/date/__snapshots__/date.test.tsx.snap
  webapp/src/properties/date/date.test.tsx
  webapp/src/properties/date/date.tsx
Labels: QA Verified

#4604 Monorepo: remove standalone entry/build
  .dockerignore
  Dockerfile.build
  app-config.json
  config.json
  docker/Dockerfile
  docker/README.md
  docker/config.json
  docker/docker-compose-db-nginx.yml
  docker/docker-compose.yml
  docker/server_config.json
  server-config.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/blocksEditor/devmain.scss
  webapp/src/components/blocksEditor/devmain.tsx
  webapp/src/main.tsx
  webapp/webpack.common.js
  webapp/webpack.dev.js
  webapp/webpack.editor.js
  webapp/webpack.prod.js
Labels: 3: Reviews Complete

#4620 check permissions to channel before patching via api
  server/app/boards.go
  server/app/boards_test.go
Labels: 3: Reviews Complete, CherryPick/Approved

#4614 Deduplicate category boards
  mattermost-plugin/server/manifest.go
  server/services/store/sqlstore/data_migrations.go
  server/services/store/sqlstore/migrate.go
  server/services/store/sqlstore/migrations/000036_category_board_add_unique_constraint.up.sql
  server/services/store/storetests/system.go
Labels: 3: Reviews Complete, CherryPick/Approved

#4635 fix path for static files
  webapp/src/widgets/emojiPicker.tsx
Labels: 2: Dev Review

#4653 Adds escaping when normalizing table names for MySQL on DB helpers
  server/services/store/sqlstore/migrate.go
Labels: 2: Dev Review, CherryPick/Approved

#4669 Fix CI after mono-repo
  .github/workflows/ci.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
Labels: 2: Dev Review

#4672 only send category updates to user
  server/ws/server.go
  server/ws/server_test.go
Labels: 2: Dev Review

#4685 need url for emoji picker
  webapp/src/widgets/emojiPicker.tsx
Labels: 2: Dev Review, CherryPick/Approved, QA Verified
