Repository mattermost-community/focalboard, pull requests merged in 2023-01, with the labels that each got.

#4418 Update snapshots for date format
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoardItem.test.tsx.snap
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoards.test.tsx.snap
Labels: 2: Dev Review

#4392 Menu consistent for table view
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/cardActionsMenu/cardActionsMenu.test.tsx
  webapp/src/components/cardActionsMenu/cardActionsMenu.tsx
  webapp/src/components/cardDialog.tsx
  webapp/src/components/gallery/galleryCard.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/components/table/__snapshots__/table.test.tsx.snap
  webapp/src/components/table/table.test.tsx
  webapp/src/components/table/tableRow.tsx
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#4419 don't check date fields for text search
  webapp/src/store/cards.ts
Labels: 2: Dev Review, 2: QA Review

#4373 Added unregister change handler to useEffect
  webapp/src/components/sidebar/sidebar.tsx
Labels: 3: Reviews Complete

#4154 Disable the view dropdown selector on public "read-only"
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/viewHeader.test.tsx.snap
  webapp/src/components/viewHeader/viewHeader.tsx
Labels: Lifecycle/1:stale, Contributor

#4412 Implement Date Filter
  webapp/src/blocks/filterClause.test.ts
  webapp/src/blocks/filterClause.ts
  webapp/src/cardFilter.test.ts
  webapp/src/cardFilter.ts
  webapp/src/components/calendar/fullCalendar.tsx
  webapp/src/components/viewHeader/__snapshots__/dateFilter.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterComponent.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
  webapp/src/components/viewHeader/dateFilter.scss
  webapp/src/components/viewHeader/dateFilter.test.tsx
  webapp/src/components/viewHeader/dateFilter.tsx
  webapp/src/components/viewHeader/filterEntry.test.tsx
  webapp/src/components/viewHeader/filterEntry.tsx
  webapp/src/components/viewHeader/filterValue.test.tsx
  webapp/src/components/viewHeader/filterValue.tsx
  webapp/src/components/viewHeader/viewHeaderDisplayByMenu.tsx
  webapp/src/components/workspace.tsx
  webapp/src/octoUtils.tsx
  webapp/src/properties/createdTime/property.tsx
  webapp/src/properties/date/property.tsx
  webapp/src/properties/types.tsx
  webapp/src/properties/updatedTime/property.tsx
Labels: 2: Dev Review, 2: QA Review

#4463 MM-49637 Make chunk filenames generated for MPA unique
  mattermost-plugin/webapp/webpack.config.js
Labels: 3: Reviews Complete, CherryPick/Approved

#4465 Automated cherry pick of #4463
  mattermost-plugin/webapp/webpack.config.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4466 Automated cherry pick of #4463
  mattermost-plugin/webapp/webpack.config.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4458 Adjusting modals and updating close icon on input
  mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/__snapshots__/confirmAddUserForNotifications.test.tsx.snap
  webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
  webapp/src/components/__snapshots__/dialog.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorItem.test.tsx.snap
  webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
  webapp/src/components/cardDialog.scss
  webapp/src/components/confirmationDialogBox.scss
  webapp/src/components/confirmationDialogBox.tsx
  webapp/src/components/createCategory/__snapshots__/createCategory.test.tsx.snap
  webapp/src/components/createCategory/createCategory.scss
  webapp/src/components/createCategory/createCategory.tsx
  webapp/src/components/dialog.scss
  webapp/src/components/dialog.tsx
  webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialog.test.tsx.snap
  webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialogWrapper.test.tsx.snap
Labels: 2: Dev Review

#4467 Change board serverRoot from '/plugins/focalboard' to '/boards'
  mattermost-plugin/server/boards/boardsapp_util.go
Labels: 2: QA Review

#4473 Bump mm-server version to v6.0.0-20230116174708-240304ad0728
  server/go.mod
  server/go.sum
Labels: 2: Dev Review

#4414 Implement Person filter and groupBy
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  webapp/i18n/en.json
  webapp/src/boardUtils.ts
  webapp/src/cardFilter.test.ts
  webapp/src/cardFilter.ts
  webapp/src/components/__snapshots__/personSelector.test.tsx.snap
  webapp/src/components/centerPanel.tsx
  webapp/src/components/kanban/kanbanColumnHeader.tsx
  webapp/src/components/personSelector.scss
  webapp/src/components/personSelector.test.tsx
  webapp/src/components/personSelector.tsx
  webapp/src/components/table/tableGroupHeaderRow.tsx
  webapp/src/components/table/tableRow.tsx
  webapp/src/components/viewHeader/__snapshots__/filterComponent.test.tsx.snap
  webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
  webapp/src/components/viewHeader/filterEntry.tsx
  webapp/src/components/viewHeader/filterValue.tsx
  webapp/src/components/viewHeader/multiperson.scss
  webapp/src/components/viewHeader/multipersonFilterValue.tsx
  webapp/src/octoUtils.tsx
  webapp/src/properties/createdBy/property.tsx
  webapp/src/properties/multiperson/multiperson.test.tsx
  webapp/src/properties/multiperson/multiperson.tsx
  webapp/src/properties/multiperson/property.tsx
  webapp/src/properties/person/__snapshots__/confirmPerson.test.tsx.snap
  webapp/src/properties/person/confirmPerson.test.tsx
  webapp/src/properties/person/confirmPerson.tsx
  webapp/src/properties/person/person.tsx
  webapp/src/properties/person/property.tsx
  webapp/src/properties/types.tsx
  webapp/src/properties/updatedBy/property.tsx
Labels: 2: Dev Review, 2: QA Review

#4455 Update the filter condition if property changes and not supported
  webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
  webapp/src/components/viewHeader/filterEntry.test.tsx
  webapp/src/components/viewHeader/filterEntry.tsx
  webapp/src/octoUtils.test.ts
  webapp/src/octoUtils.tsx
Labels: 2: Dev Review, 2: QA Review

#4484 Update configuration to use 'ProductSettings.EnablePublicSharedBoards'
  mattermost-plugin/server/boards/configuration.go
Labels: 2: Dev Review, 2: QA Review

#4487 Fix panic when notifying of block change (getDirectChannel returning nil,nil)
  server/services/notify/plugindelivery/subscription_deliver.go
Labels: 2: Dev Review

#4422 Export Import Memberships is retained
  server/app/export.go
  server/app/import.go
  server/app/import_test.go
Labels: 2: Dev Review

#4477 [GH-4300]: Fix menu closing on toggling random icons.
  webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
  webapp/src/components/sidebar/sidebarSettingsMenu.tsx
Labels: Contributor

#4486 Suppress error message on unfound option id
  webapp/src/boardUtils.ts
Labels: 2: Dev Review

#4485 Gh 4482 fix empty filters
  webapp/src/cardFilter.test.ts
  webapp/src/cardFilter.ts
Labels: 2: Dev Review

#4437 Update footer.html
  website/site/layouts/partials/footer.html
Labels: 1: PM Review, Contributor

#4453 Update en.json
  webapp/cypress/integration/createBoard.ts
  webapp/cypress/support/ui_commands.ts
  webapp/i18n/en.json
Labels: 3: Reviews Complete

#4496 Use GetDirectChannelOrCreate when notifying block chg in MPA mode
  mattermost-plugin/product/api_adapter.go
  mattermost-plugin/server/api_adapter.go
  mattermost-plugin/server/manifest.go
  server/model/mocks/mockservicesapi.go
  server/model/services_api.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/subscription_deliver.go
  server/services/notify/plugindelivery/user_test.go
Labels: 2: Dev Review, CherryPick/Approved

#4498 Automated cherry pick of #4496
  mattermost-plugin/product/api_adapter.go
  mattermost-plugin/server/api_adapter.go
  mattermost-plugin/server/manifest.go
  server/model/mocks/mockservicesapi.go
  server/model/services_api.go
  server/services/notify/plugindelivery/plugin_delivery.go
  server/services/notify/plugindelivery/subscription_deliver.go
  server/services/notify/plugindelivery/user_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4489 MM-49703: Bump to Go 1.19
  .github/workflows/ci.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
  .gitlab-ci.yml
  build/gowork/main.go
  linux/go.mod
  mattermost-plugin/build/go.mod
  mattermost-plugin/go.mod
  server/.golangci.yml
  server/api/api.go
  server/api/audit.go
  server/api/auth.go
  server/api/members.go
  server/app/insights.go
  server/app/insights_test.go
  server/assets/assets.go
  server/go.mod
  server/go.tools.mod
  server/integrationtests/cards_test.go
  server/main/main.go
  server/server/server.go
  server/services/audit/audit.go
  server/services/metrics/service.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board_insights.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/store.go
  server/services/store/storetests/board_insights.go
  server/web/webserver.go
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_cluster.go
Labels: 3: Reviews Complete

#4502 MM-49703: Bump to Go 1.19 (#4489)
  .github/workflows/ci.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
  .gitlab-ci.yml
  build/gowork/main.go
  linux/go.mod
  mattermost-plugin/build/go.mod
  mattermost-plugin/go.mod
  server/.golangci.yml
  server/api/api.go
  server/api/audit.go
  server/api/auth.go
  server/api/members.go
  server/app/insights.go
  server/app/insights_test.go
  server/assets/assets.go
  server/go.mod
  server/go.tools.mod
  server/integrationtests/cards_test.go
  server/main/main.go
  server/server/server.go
  server/services/audit/audit.go
  server/services/metrics/service.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board_insights.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/store.go
  server/services/store/storetests/board_insights.go
  server/web/webserver.go
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_cluster.go
Labels: 3: Reviews Complete

#4507 Cherry-pick: MM-49703: Bump to Go 1.19 (#4489) (#4502)
  .github/workflows/ci.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
  .gitlab-ci.yml
  build/gowork/main.go
  linux/go.mod
  mattermost-plugin/build/go.mod
  mattermost-plugin/go.mod
  server/.golangci.yml
  server/api/api.go
  server/api/audit.go
  server/api/auth.go
  server/api/members.go
  server/app/insights.go
  server/app/insights_test.go
  server/assets/assets.go
  server/go.mod
  server/go.tools.mod
  server/integrationtests/cards_test.go
  server/main/main.go
  server/server/server.go
  server/services/audit/audit.go
  server/services/metrics/service.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board_insights.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/store.go
  server/services/store/storetests/board_insights.go
  server/web/webserver.go
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_cluster.go
Labels: 2: Dev Review

#4503 Multiple UI Fixes (Modals and person property label)
  webapp/src/components/cardDialog.scss
  webapp/src/components/dialog.scss
  webapp/src/components/kanban/kanban.scss
Labels: 2: Dev Review

#4504 MM-43342: More strict permissions on categories
  server/api/categories.go
  server/integrationtests/permissions_test.go
Labels: 3: Reviews Complete

#4506 File attachment in personal server
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/cardDialog.tsx
Labels: 2: QA Review, CherryPick/Approved

#4527 Revert "MM-49703: Bump to Go 1.19 (#4489)" (#4499)
  .github/workflows/ci.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
  .gitlab-ci.yml
  build/gowork/main.go
  linux/go.mod
  mattermost-plugin/build/go.mod
  mattermost-plugin/go.mod
  server/.golangci.yml
  server/api/api.go
  server/api/audit.go
  server/api/auth.go
  server/api/members.go
  server/app/insights.go
  server/app/insights_test.go
  server/assets/assets.go
  server/go.mod
  server/go.tools.mod
  server/integrationtests/cards_test.go
  server/main/main.go
  server/server/server.go
  server/services/audit/audit.go
  server/services/metrics/service.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/board_insights.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/store.go
  server/services/store/storetests/board_insights.go
  server/web/webserver.go
  server/ws/plugin_adapter.go
  server/ws/plugin_adapter_cluster.go
Labels: 3: Reviews Complete

#4483 fix string vs string[] in hiding rows
  webapp/src/components/table/tableRow.tsx
  webapp/src/mutator.ts
  webapp/src/properties/person/confirmPerson.tsx
Labels: 3: Reviews Complete

#4411 [MM-49159] Fix status dropdown menu avatar on click
  webapp/src/widgets/menu/menu.scss
Labels: 3: Reviews Complete, CherryPick/Approved
