Repository mattermost-community/focalboard, pull requests merged in 2023-09, with the labels that each got.

#4862 Transitioning Mattermost Boards > Focalboards plugin docs
  docs/board-metrics.md
  docs/create-new-board.md
  docs/dev-tips.md
  docs/focalboard-dev-guide.md
  docs/focalboard-plugin-end-user-guide.md
  docs/get-started-with-board-templates.md
  docs/group-filter-sort-boards.md
  docs/import-export-backup-data.md
  docs/index.md
  docs/link-boards-to-mattermost-channels.md
  docs/manage-boards.md
  docs/manage-plugin-preferences.md
  docs/plugin-data-being-collected.md
  docs/share-collaborate.md
  docs/work-with-board-views.md
  docs/work-with-cards.md
Labels: 3: Reviews Complete

#4871 MM-54366 Check guest access to other members
  server/api/users.go
  server/client/client.go
  server/integrationtests/pluginteststore.go
  server/integrationtests/user_test.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: 2: Dev Review, CherryPick/Approved

#4889 Automated cherry pick of #4884
  server/api/users.go
  server/client/client.go
  server/integrationtests/pluginteststore.go
  server/integrationtests/user_test.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4888 Automated cherry pick of #4884
  server/api/users.go
  server/client/client.go
  server/integrationtests/pluginteststore.go
  server/integrationtests/user_test.go
  server/services/store/mattermostauthlayer/mattermostauthlayer.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
