Repository mattermost-community/focalboard, pull requests merged in 2023-06, with the labels that each got.

#4415 Fix Chinese lang code
  webapp/src/constants.ts
  webapp/src/i18n.tsx
Labels: 1: PM Review, Lifecycle/1:stale, 2. Editor Review, Contributor

#4759 [MM-52996] fix server ci after renaming the project
  .github/workflows/ci.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
  build/gowork/main.go
  mattermost-plugin/Makefile
Labels: 3: Reviews Complete

#4761 Fix boards share dialog
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: CherryPick/Approved

#4765 Automated cherry pick of #4761
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4764 Automated cherry pick of #4761
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4763 Automated cherry pick of #4761
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4762 Automated cherry pick of #4761
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4760 Upgrade Scorecards action version
  .github/workflows/scorecards-analysis.yml
Labels: 3: Reviews Complete

#4766 Automated cherry pick of #4760
  .github/workflows/scorecards-analysis.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4771 Update ubuntu version to use latest LTS
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
  .github/workflows/scorecards-analysis.yml
Labels: 2: Dev Review, CherryPick/Candidate

#4774 Automated cherry pick of #4771
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
  .github/workflows/scorecards-analysis.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4773 Automated cherry pick of #4771
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dev-release.yml
  .github/workflows/lint-server.yml
  .github/workflows/prod-release.yml
  .github/workflows/scorecards-analysis.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4777 Automated cherry pick of #4739
  server/auth/auth.go
  server/integrationtests/permissions_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4779 Automated cherry pick of #4739
  server/auth/auth.go
  server/integrationtests/permissions_test.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4785 MM-53240-older attachment files don't work.
  server/app/files.go
Labels: 3: Reviews Complete, CherryPick/Approved

#4786 Automated cherry pick of #4785
  server/app/files.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4787 cherry-pick: check 'path' for 'empty' as well (#4785)
  server/app/files.go
Labels: 2: Dev Review

#4788 Updates import to read with a scanner
  server/app/import.go
Labels: 3: Reviews Complete, CherryPick/Approved

#4789 Automated cherry pick of #4788
  server/app/import.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4790 Unify and enhance block validation
  server/api/api_test.go
  server/model/block.go
  server/model/error.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/legacy_blocks.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/boards_and_blocks.go
Labels: 3: Reviews Complete

#4793 Automated cherry pick of #4790
  server/api/api_test.go
  server/model/block.go
  server/model/error.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/legacy_blocks.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/boards_and_blocks.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
