Repository mattermost-community/focalboard, pull requests merged in 2023-02, with the labels that each got.

#4526 Automated cherry pick of #4506
  webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
  webapp/src/components/cardDialog.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4285 Compliance (export/history) APIs
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  server/api/api.go
  server/api/archive.go
  server/api/compliance.go
  server/app/app.go
  server/app/compliance.go
  server/client/client.go
  server/go.mod
  server/go.sum
  server/integrationtests/board_test.go
  server/integrationtests/clienttestlib.go
  server/integrationtests/compliance_test.go
  server/integrationtests/pluginteststore.go
  server/model/compliance.go
  server/model/mocks/propValueResolverMock.go
  server/services/store/generators/main.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/compliance.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/compliance.go
  server/services/store/storetests/util.go
Labels: 2: Dev Review, 3: Reviews Complete

#4540 add admin user on import
  server/app/import.go
  server/app/import_test.go
Labels: 2: Dev Review, CherryPick/Approved

#4534 Automated cherry pick of #4411
  webapp/src/widgets/menu/menu.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4541 Add a test to help detect potential sync issues with work template
  server/integrationtests/work_template_test.go
Labels: 2: Dev Review

#4508 Fix notifications for deleted card content blocks
  mattermost-plugin/server/boards/notifications.go
  server/model/block.go
  server/model/blocktype.go
  server/services/notify/notifysubscriptions/app_api.go
  server/services/notify/notifysubscriptions/diff.go
  server/services/notify/notifysubscriptions/diff2slackattachments.go
  server/services/notify/notifysubscriptions/notifier.go
  server/services/notify/notifysubscriptions/subscriptions_backend.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  server/utils/utils.go
Labels: 3: Reviews Complete, CherryPick/Approved

#4530 GH-4520 - Check isBot property before displaying BotBadge
  webapp/src/components/markdownEditorInput/entryComponent/entryComponent.tsx
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#4535 GH-4475 - Save date change to database when closing form
  webapp/src/properties/date/date.tsx
Labels: 2: Dev Review, 3: Reviews Complete

#4558 Cherry-pick 4285 Compliance export into release-7.8
  mattermost-plugin/go.mod
  mattermost-plugin/go.sum
  server/api/api.go
  server/api/archive.go
  server/api/compliance.go
  server/app/app.go
  server/app/compliance.go
  server/client/client.go
  server/go.mod
  server/go.sum
  server/integrationtests/board_test.go
  server/integrationtests/clienttestlib.go
  server/integrationtests/compliance_test.go
  server/integrationtests/pluginteststore.go
  server/model/compliance.go
  server/model/mocks/propValueResolverMock.go
  server/services/store/generators/main.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/compliance.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/sqlstore/sqlstore.go
  server/services/store/sqlstore/sqlstore_test.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  server/services/store/storetests/compliance.go
  server/services/store/storetests/util.go
Labels: 2: Dev Review

#4546 Automated cherry pick of #4508
  mattermost-plugin/server/boards/notifications.go
  server/model/block.go
  server/model/blocktype.go
  server/services/notify/notifysubscriptions/app_api.go
  server/services/notify/notifysubscriptions/diff.go
  server/services/notify/notifysubscriptions/diff2slackattachments.go
  server/services/notify/notifysubscriptions/notifier.go
  server/services/notify/notifysubscriptions/subscriptions_backend.go
  server/services/store/mockstore/mockstore.go
  server/services/store/sqlstore/blocks.go
  server/services/store/sqlstore/board.go
  server/services/store/sqlstore/public_methods.go
  server/services/store/store.go
  server/services/store/storetests/blocks.go
  server/utils/utils.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4542 Used Shared resource from MM-server for attachment serving
  server/api/files.go
Labels: CherryPick/Approved

#4560 Automated cherry pick of #4542
  server/api/files.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4444 Fixed duplicate attachment in board template
  server/app/blocks.go
  server/app/boards.go
  webapp/cypress/integration/cardURLProperty.ts
  webapp/src/components/cardDetail/attachment.scss
  webapp/src/mutator.ts
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/store/attachments.ts
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#4562 Automated cherry pick of #4444
  server/app/blocks.go
  server/app/boards.go
  webapp/cypress/integration/cardURLProperty.ts
  webapp/src/components/cardDetail/attachment.scss
  webapp/src/mutator.ts
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/store/attachments.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4565 Automated cherry pick of #4542
  server/api/files.go
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4570 use specific class, rather than NOT an unrelated ID
  webapp/src/widgets/menu/menu.scss
Labels: 2: Dev Review, CherryPick/Approved

#4572 Automated cherry pick of #4570
  webapp/src/widgets/menu/menu.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4557 Use `name` column to determine if schema_migrations table is correct format
  mattermost-plugin/server/manifest.go
  server/services/store/sqlstore/schema_table_migration.go
Labels: 3: Reviews Complete

#4574 Update version to v7.8.2
  mattermost-plugin/plugin.json
  mattermost-plugin/server/manifest.go
  server/model/version.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/constants.ts
Labels: 2: Dev Review

#4301 Added the bot-notification changes for attachment
  server/services/notify/notifysubscriptions/diff2slackattachments.go
  webapp/src/components/cardDialog.tsx
Labels: 2: Dev Review, 2: QA Review

#4531 Fix today
  webapp/src/properties/date/date.test.tsx
  webapp/src/properties/date/date.tsx
Labels: 2: Dev Review, 2: QA Review

#4537 initial implementation of SysAdmin/TeamAdmin feature
  server/api/members.go
  server/api/teams.go
  server/api/users.go
  server/app/boards.go
  server/app/boards_test.go
  server/app/category_boards_test.go
  server/app/helper_test.go
  server/app/onboarding_test.go
  server/app/user.go
  server/app/user_test.go
  server/integrationtests/clienttestlib.go
  server/model/permission.go
  server/model/user.go
  server/services/permissions/localpermissions/localpermissions.go
  server/services/permissions/localpermissions/localpermissions_test.go
  server/services/permissions/mmpermissions/helpers_test.go
  server/services/permissions/mmpermissions/mmpermissions.go
  server/services/permissions/mmpermissions/mmpermissions_test.go
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/userPermissionsRow.test.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/octoClient.ts
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/store/boards.ts
  webapp/src/user.tsx
  webapp/src/widgets/adminBadge/__snapshots__/adminBadge.test.tsx.snap
  webapp/src/widgets/adminBadge/adminBadge.scss
  webapp/src/widgets/adminBadge/adminBadge.test.tsx
  webapp/src/widgets/adminBadge/adminBadge.tsx
Labels: 3: Reviews Complete

#4581 Fix for users adding board links to Read-only channels
  mattermost-plugin/server/manifest.go
  mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoards.test.tsx.snap
  mattermost-plugin/webapp/src/components/rhsChannelBoards.test.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
  mattermost-plugin/webapp/src/index.tsx
  server/api/users.go
  server/app/user.go
  server/app/user_test.go
  server/integrationtests/clienttestlib.go
  server/model/permission.go
  webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
  webapp/src/constants.ts
  webapp/src/octoClient.ts
Labels: 2: Dev Review, 2: QA Review

#4583 Removing references to isFocalboardPlugin and isFocalboardLegacy
  mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.test.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
  mattermost-plugin/webapp/src/components/rhsChannelBoardsHeader.tsx
  mattermost-plugin/webapp/src/index.tsx
  mattermost-plugin/webapp/webpack.config.js
  webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
  webapp/src/components/__snapshots__/topBar.test.tsx.snap
  webapp/src/components/__snapshots__/workspace.test.tsx.snap
  webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
  webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
  webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
  webapp/src/components/cardDialog.test.tsx
  webapp/src/components/cardDialog.tsx
  webapp/src/components/kanban/kanbanCard.tsx
  webapp/src/components/messages/__snapshots__/cloudMessage.test.tsx.snap
  webapp/src/components/messages/cloudMessage.test.tsx
  webapp/src/components/messages/cloudMessage.tsx
  webapp/src/components/onboardingTour/addComments/addComments.tsx
  webapp/src/components/onboardingTour/addDescription/add_description.tsx
  webapp/src/components/onboardingTour/addProperties/add_properties.tsx
  webapp/src/components/onboardingTour/addView/add_view.tsx
  webapp/src/components/onboardingTour/copyLink/copy_link.tsx
  webapp/src/components/onboardingTour/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/__snapshots__/channelPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/teamPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
  webapp/src/components/shareBoard/channelPermissionsRow.test.tsx
  webapp/src/components/shareBoard/channelPermissionsRow.tsx
  webapp/src/components/shareBoard/shareBoard.test.tsx
  webapp/src/components/shareBoard/shareBoard.tsx
  webapp/src/components/shareBoard/shareBoardLoginButton.tsx
  webapp/src/components/shareBoard/teamPermissionsRow.test.tsx
  webapp/src/components/shareBoard/teamPermissionsRow.tsx
  webapp/src/components/shareBoard/userPermissionsRow.test.tsx
  webapp/src/components/shareBoard/userPermissionsRow.tsx
  webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
  webapp/src/components/sidebar/sidebar.tsx
  webapp/src/components/sidebar/sidebarUserMenu.scss
  webapp/src/components/sidebar/sidebarUserMenu.tsx
  webapp/src/components/topBar.test.tsx
  webapp/src/components/topBar.tsx
  webapp/src/components/viewLImitDialog/viewLimitDialog.tsx
  webapp/src/components/withWebSockets.tsx
  webapp/src/components/workspace.test.tsx
  webapp/src/hooks/permissions.tsx
  webapp/src/pages/boardPage/boardPage.tsx
  webapp/src/pages/boardPage/setWindowTitleAndIcon.tsx
  webapp/src/pages/errorPage.tsx
  webapp/src/pages/welcome/welcomePage.tsx
  webapp/src/route.tsx
  webapp/src/router.tsx
  webapp/src/store/users.ts
  webapp/src/theme.ts
  webapp/src/types/index.d.ts
  webapp/src/utils.test.ts
  webapp/src/utils.ts
  webapp/src/wsclient.ts
Labels: 2: Dev Review

#4605 MM-50810 Fix module loading issues caused by shared modules
  mattermost-plugin/webapp/webpack.config.js
Labels: 3: Reviews Complete
